### ISSUE TITLE
Error loading repositories

### ISSUE THREAD

**Issue by davebanthorpe** [Azure/acr#101]
I have a container registry that I have been using successfully over the last few days. This afternoon it suddenly stopped allowing me to push new images from VSCode. A quick look in the portal, and clicking on Repositories results in the error "Error loading repositories".

Is this a problem with my registry or a general service error?

```
{"type":"MsPortalFx.Errors.FetchDataError","baseTypes":["MsPortalFx.Errors.FetchDataError","MsPortalFx.Errors.DataError","MsPortalFx.Errors.Error"],"_errorData":{"readyState":0,"status":0,"statusText":"error"},"extension":"Microsoft_Azure_ContainerRegistries","errorLevel":2,"timestamp":717119.2802145145,"source":"KraterExtension.DataModels.RepositoryEntity:DataCache:4:13","message":"","name":"Error","innerErrors":[],"dataSetName":"KraterExtension.DataModels.RepositoryEntity:DataCache:4:13"}
--

```

**Comment by davebanthorpe** [comment]
cheers - mail sent

**Comment by sajayantony** [comment]
@davebanthorpe - Sorry about the incident. This has now been resolved. Please reopen if you see this happening.
