### ISSUE TITLE
`az acr login` doesn't support custom domain

### ISSUE THREAD

**Issue by jodok** [Azure/acr#102]
we'd like to keep our custom domain and followed the instructions at https://github.com/Azure/acr/tree/master/docs/custom-domain 
however i didn't find a way to log in to that registry (apart from using the master/admin user and static password). 

one possibility would be to support an additional parameter such as `--domain` - and run sth. like `az acr login --name myregistry --domain myregistry.mydomain.com`

another possibilty would be that `az acr credential show` can output valid credentials based on the AD user - and not only the admin user.

the flow described at https://github.com/Azure/acr/blob/master/docs/AAD-OAuth.md is overly complicated for everyday shell usage. but maybe i'm missing an easy way to achieve this?

**Comment by sivagms** [comment]
what is the error you see when trying to 'az acr login --name myregistry'?

**Comment by jodok** [comment]
if i do a run for the very first time:

```
az acr login --name registry.mydomain.com
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

if i start docker on my local machine afterwards:

```
az acr login --name registry.mydomain.com
Error response from daemon: Bad response from Docker engine
```

if i login to the registry directly:

```
az acr login --name my_azure_identifier
Login Succeeded
```

if i then try to login to my proxied registry:

```
az acr login --name registry.mydomain.net
The resource with name 'registry.mydomain.net' and type 'Microsoft.ContainerRegistry/registries' could not be found in subscription 'crate (7265ef4a-08f2-4f45-9521-b795bfbee7e8)'
```

the access logs of the proxy server also show that now request is being issued to the domain.

**Comment by sivagms** [comment]
This is the correct and expected usage: 
```
az acr login --name my_azure_identifier
```

This one doesn't work because az cli or ACR service doesn't know about the custom domain you configured.
`az acr login --name registry.mydomain.net`

**Comment by jodok** [comment]
so, how should i push to the registry using the proxied name?

**Comment by jodok** [comment]
@sivagms so you're saying - authentication against custom domains is not supported? unfortunately we're blocked by this issue.

**Comment by jodok** [comment]
this works - but would require one service principal per user to be authenticated. right?

**Comment by sivagms** [comment]
or all of them use the same service principal.  If you want each user to have separate credentials, then we can look into supporting something like  'az acr login --name my_azure_identifier --custom-domain registry.mydomain.net'  so that you don't have to create one SP per user.

**Comment by jodok** [comment]
yes, we would like to use individual users for our customers and therefor a second argument would be awesome.

**Comment by sivagms** [comment]
can you please log a feature request here - https://feedback.azure.com/forums/903958-azure-container-registry

**Comment by jodok** [comment]
done. thank you: https://feedback.azure.com/forums/903958-azure-container-registry/suggestions/34888780-allow-to-authenticate-via-az-acr-login-via-custo

**Comment by sajayantony** [comment]
@djyou  - this should be possible if we take loginserver for acr-login? is that correct?

**Comment by sajayantony** [comment]
Closing this since we have no plan to support it at this point. Please raise a request on https://aka.ms/acr/uservoice

**Comment by saulobejo** [comment]
You didn't hear it from me:

```shell
  az login --identity
  az acr login -n myregistry
  sed -i 's/myregistry.azurecr.io/registry.mydomain.com/' ~/.docker/config.json
```
