### ISSUE TITLE
Excessive `Unauthorized: Authentication required`

### ISSUE THREAD

**Issue by beaudryj** [Azure/acr#103]
We have been getting flooded with failing builds due to Excessive `Unauthorized: Authentication required` and I Wanted to help pinpoint what may be causing the issue as right now it is an uncomfortable back and fourth between app build team and IT. 

- I have tried a mix of Azure CLI and Docker Log in to log into the container registry prior to pushing and I have even gotten to the point where I do both. 
- I wanted to see if there is chance that concurrent pushes may invalidate each other
- Is there time out on the login that may be occuring as some of these images are quite large as we are pushing Windows 2016 LTSC containers
- Should I be using windows cred store vs. AZ CLI or Docker login? 
- If there is a timeout can I set a larger timeout on the client?

**Comment by sivagms** [comment]
could you send me your registry name for further investigation..
Concurrent pushes won't invalidate each other. one of them (latest manifest push) will succeed.
Timeout won't cause Unauthorized error.
docker login with Service principal is ideal - but az cli should work too

**Comment by beaudryj** [comment]
I emailed you my info if that helps

**Comment by sivagms** [comment]
docker login shouldn't time out because of image size in the registry. I see in our backend that all the requests for the registry are either successful or rejected due to auth issues.
 'az acr login'  gets a token that expires after one hour. Could you please use just  docker login before pushing image and see if the issue persists..

**Comment by beaudryj** [comment]
I used that first and switched to the az acr login due to frustration with the auth issues

**Comment by beaudryj** [comment]
Could you please go into more detail on 
```
I see in our backend that all the requests for the registry are either successful or rejected due to auth issues.
```

So I can work with our IT department and pinpoint whats happening to the traffic

**Comment by sivagms** [comment]
The failures are due to missing auth credentials.  is it continuously failing or is it occasional failure? could you let me know more details about the environment - is it AKS that you are using ?

**Comment by beaudryj** [comment]
It's inconsistent and fairly frequent. My environment is a physical data center just running docker pushes all of this is being built by Teamcity and powershell scripts. We have a script building our image and then trying to push it to acr

**Comment by sivagms** [comment]
I have sent you separate email.
if you can give me the timestamp when it failed, I can gather more details.

**Comment by shershen08** [comment]
I might have similar situation:
```
$ az account show
{
  "environmentName": "AzureCloud",
  "id": "7e5cef80-1081-4d26-xxxxx",
  "isDefault": true,
  "name":
```
but pushing new images to aks fails: 
```
docker push myproject.azurecr.io/myproject-api:latest
The push refers to repository [myproject.azurecr.io/myproject-api]
56213f12629a: Preparing
2419737d333b: Preparing
...
unauthorized: authentication required
make: *** [myproject.azurecr.io/myproject-api] Error 1
```
I have following:
$ kubectl version - Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3",
$ docker version - Client: Version:      18.05.0-ce .  API version:  1.37
MacOS 10.12

**Comment by techthumb** [comment]
Are there any workarounds to this?

**Comment by sajayantony** [comment]
@sivagms  is this due to the AAD? 
@techthumb  - is `az acr login` successful?

**Comment by techthumb** [comment]
@sajayantony `az acr login` does succeed in both, proxy and no proxy modes.

However, `docker push myproject.azurecr.io/myproject-api:latest` :
- fails when behind a corporate NTLM proxy
- succeeds when no proxy is involved

**Comment by sivagms** [comment]
@techthumb  can you give the exact failure  that you see when push fails

**Comment by techthumb** [comment]
@sivagms I no longer have access to the environment.

I'll describe my environment setup.

We have a corporate NTLM proxy in place.
I run [CNTLM](http://cntlm.sourceforge.net) on my local machine.
CLI based apps talk to the local CNTLM proxy which does all the NTLM Proxy negotiation.

Running `docker push` to `*.azurecr.io` would fail with an error saying authorization failed.

HTH

**Comment by sivagms** [comment]
@techthumb we will need the registry name and docker debug logs to figure out the issue. if you can't share it here, can you email me @ sivag@microsoft.com

**Comment by sajayantony** [comment]
Closing this since we haven't see any activity in over 30 days.
