### ISSUE TITLE
Webhook & Web App for Containers

### ISSUE THREAD

**Issue by YvonneArnoldus** [Azure/acr#106]
In our ACR we have 2 Webhooks 1 create bij Web App for Containers for auto deployment and 1 for Slack notification (delete & push).

We experience the following problems:

- The auto deployment webhook is not called and the webhook for slack notification is and gives a 200.
- The auto deployment webhook is called but give a 504 and the webhook for slack notification is and gives a 200.

**Comment by YvonneArnoldus** [comment]
I did some more testing and could fix the problem but the way go get there is a bit tedious. 

Steps:

- Remove the automatic deployment from the Web App for Containers. (This does not physically remove the webhook)
- Remove the webhook for the automatic deployment.
- Add automatic deployment to the Web App for Containers.

These steps solved the problem now both webhooks are triggered and give a 200 OK.

But I don't have time to check the webhooks every day to see if they are still working. Is there away to sent alerts when this happens or better yet solve this problem.

**Comment by sajayantony** [comment]
Closing this since there is no action at this point. Feel free to open if you want us to look into it.
