### ISSUE TITLE
ACR Build allow specifying platform

### ISSUE THREAD

**Issue by northtyphoon** [Azure/acr#108]
Problems

- If Dockerfile references a multi-platform base image (eg, linux/amd64, linux/arm32v7), currently the users cannot choose to build against arm32v7 in ACR Build.
- If Dockerfile references an arm32v7 base image by a tag, even though users can successfully build the image but the manifest is annotated as amd64.

Proposal

-  Introduce a new platform option which is compatible with docker cli, here are some examples using `az acr build` command. 
``` 
  az acr build --platform arm
  az acr build --platform windows/amd64
  az acr build --platform linux/arm/v7
```
NOTE: Evaluate merging with existing --os build option.

**Comment by northtyphoon** [comment]
We have enabled --platform flag in the latest azure-cli: 2.0.60.

**Comment by Hades32** [comment]
should this also work for arm64(v8)?

Currently when I specify `linux/arm/v8` (Dockerfile is just `FROM debian`) I get an image that is marked as `Architecure:arm` instead of `Architecture:arm64` when I build on my target directly...

**Comment by northtyphoon** [comment]
@Hades32  thanks for reporting it. we will investigate to remove the blocking on arm64.

**Comment by calvintam236** [comment]
Tried to build i386 image (specified `--platform linux/x86`), and it fails.

ACR Task log:
```console
2019/06/06 22:31:50 Downloading source code...
2019/06/06 22:31:52 Finished downloading source code
2019/06/06 22:31:52 Using acb_vol_XXX as the home volume
2019/06/06 22:31:52 Setting up Docker configuration...
2019/06/06 22:31:53 Successfully set up Docker configuration
2019/06/06 22:31:53 Logging in to registry: xxx.azurecr.io
2019/06/06 22:31:54 Successfully logged into xxx.azurecr.io
2019/06/06 22:31:54 Executing step ID: build. Timeout(sec): 28800, Working directory: '', Network: ''
2019/06/06 22:31:54 Scanning for dependencies...
2019/06/06 22:31:55 Successfully scanned dependencies
2019/06/06 22:31:55 Launching container with name: build
Sending build context to Docker daemon  18.94kB
Step 1/9 : FROM debian:stretch-slim
stretch-slim: Pulling from library/debian
no matching manifest for linux/x86 in the manifest list entries
2019/06/06 22:32:01 Container failed during run: build. No retries remaining.
failed to run step ID: build: exit status 1

Run ID: XXX failed after 12s. Error: failed during run, err: exit status 1
```

PS: If you specified `--platform linux/x86/`, the console message says `Some of the properties of 'taskCreateParameters' are invalid. InnerErrors: PlatformProperties:Value of the property 'Variant' is not valid. Supported values are v6,v7,v8.`, which should not have have options for `amd64` nor `x86`. Looks like a bug to me.

**Comment by northtyphoon** [comment]
@calvintam236 thanks for reporting. While we are working on the fix, you can try multi-step tasks.

1. Create `acb.yaml` file with the following content

```
version: v1.0.0
steps:
  - build: --pull --platform linux/386 -t {{.Run.Registry}}/myimage:386 -f Dockerfile .
  - push:
    - {{.Run.Registry}}/myimage:386
```

2. Run 
```
az acr run -r myregistry -f acb.yaml .
```

**Comment by calvintam236** [comment]
@northtyphoon any updates?

**Comment by shahzzzam** [comment]
Hi @calvintam236 , you can now pass `linux/386` as the `--platform`.

**Comment by corwestermaniddink** [comment]
> linux/arm/v8

Any update on this?

**Comment by corwestermaniddink** [comment]
> @Hades32 thanks for reporting it. we will investigate to remove the blocking on arm64.

@Hades32 Any update about this?
