### ISSUE TITLE
Error response from daemon when searching registry

### ISSUE THREAD

**Issue by ddobric** [Azure/acr#109]
When trying to search for repositories in the ACR, getting following error:

_Error response from daemon: Unexpected status code 404_

Command:
`docker search myregistry.azurecr.io/my`

Note, I have previously correctly logged in. I can pull images from registry.

**Comment by ddobric** [comment]
Thanks.
I guess, this is on the roadmap?

**Comment by sajayantony** [comment]
Unfortunately not. But you could make an item on uservoice.

**Comment by sajayantony** [comment]
Closing since this uservoice is the prioritization mechanism for this.
