### ISSUE TITLE
ACR build fails for Windows based image

### ISSUE THREAD

**Issue by artisticcheese** [Azure/acr#115]
Trying to run following in ACR build and it fails with error below

`az acr build --os windows -r whoamiregistry --image whoami:v1 https://github.com/artisticcheese/artisticcheesecontainer.git#master:whoami`

Error
```
time="2018-07-23T12:55:27-07:00" level=info msg="Running command docker login -u 00000000-0000-0000-0000-000000000000 --password-stdin whoamiregistry.azurecr.io"
WARNING: Error loading config file: C:\Users\ContainerAdministrator\.docker\config.json: invalid character 'ÿ' looking for beginning of value
WARNING! Your password will be stored unencrypted in C:\Users\ContainerAdministrator\.docker\config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
Login Succeeded
time="2018-07-23T12:55:31-07:00" level=info msg="Running command git rev-parse --verify HEAD"
1281de13c98bc6b986a2e91ac15ebe54f5ba0310
time="2018-07-23T12:55:31-07:00" level=error msg="invalid reference format"
Build ID: add failed after 21.8481445s
```

**Comment by ehotinger** [comment]
@northtyphoon  / @mnltejaswini try the Dockerfile without quotes in the args to see if it's successful, i.e.
```
ARG buildimagetag="2.1-sdk"
-> ARG buildimagetag=2.1-sdk
```

Add a bug for this case to the builder for the dependency scanner if that's the root cause.

**Comment by northtyphoon** [comment]
Thanks @ehotinger . It failed to handled the quote.

**Comment by ehotinger** [comment]
@artisticcheese try removing quotes in the Dockerfile for now to unblock yourself, we'll fix it but it'll take some time to roll out. Thanks for reporting this!

**Comment by sajayantony** [comment]
So can this be closed now?
