### ISSUE TITLE
Manual build jobs hangs

### ISSUE THREAD

**Issue by FrodeHus** [Azure/acr#122]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened?**:
I ran `az acr build -t <imagename> -f ./Dockerfile -r <registry name> .` and I got the following output:
```Packing source code into tar file to upload...
Sending build context (215.504 KiB) to ACR...
Queued a build with build ID: ag2
Waiting for build agent...
2018/08/17 07:53:02 Using acb_vol_fa3b629f-f187-40ff-bd25-e57e8d3e9b89 as the home volume
2018/08/17 07:53:02 Setting up Docker configuration...
2018/08/17 07:53:03 Successfully set up Docker configuration
2018/08/17 07:53:03 Logging in to registry: chaos.azurecr.io
2018/08/17 07:53:26 Successfully logged in
```
After that, the log output just hangs. If I run `az acr build-task list-builds -r <registry name> -g <group> -o table` this shows:
```
BUILD ID    TASK    PLATFORM    STATUS    TRIGGER    STARTED               DURATION
----------  ------  ----------  --------  ---------  --------------------  ----------
ag2                 Linux       Running   Manual     2018-08-17T07:53:01Z
ag1                 Linux       Running   Manual     2018-08-17T07:07:03Z
```
Both builds have been running for over an hour and this is a simple Hello World-type .NET Core application.

**What did you expect to happen?**:
Actual docker build output from the log and the build to actually finish instead of hanging with status `Running`.

**How do you reproduce it (as minimally and precisely as possible)?**:
It happens every time I run the manual `az acr build` command specified above.

**Anything else we need to know?**:

**Environment (if applicable to the issue)**:

**Comment by ehotinger** [comment]
@FrodeHus I looked at this quickly since it's quite late in the AM over here, but I'll pick it up again first thing in the morning. I believe it's a bug in the decompression algorithm for the specific tar you're generating here; it seems to be hanging there. This will take more debugging. It seems like you're using a git repository for this as well, so would you mind using a git context as opposed to a tar context to try and confirm this and use it as a workaround? I.e., `az acr build https://github.com/foo/scratch.git`

**Comment by FrodeHus** [comment]
Using the git context worked - I'll use that for now, thanks

**Comment by ehotinger** [comment]
@FrodeHus glad to hear! I'll post an update when this is all fixed and deployed. I've also added a few additional issues here to track to make sure we time out within a reasonable timeframe in cases like this. Thanks for reporting the issue.

**Comment by ehotinger** [comment]
Closing for now since all of these related issues have been deployed.
