### ISSUE TITLE
Az Acr Build - I just love pulling base images...... (--os Windows)

### ISSUE THREAD

**Issue by beaudryj** [Azure/acr#125]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature Request

**What happened?**:  Can the build images have MSSQL or Pre-Pulled, or windows server prepulled, I hate that about 5-10 minutes are burned just pulling the base images... I Would love to have the dynamicism of these cloud build agents, but On-Prem ends up better due to not needing to pull as many layers

**Comment by beaudryj** [comment]
I would love to see 
microsoft/mssql-server-windows
microsoft/dotnet-framework

Both of these builds are taking like 8-10 minutes... and about 4-5 minutes of that are just pulling the images.

**Comment by sajayantony** [comment]
@northtyphoon will follow up on the cache update and figure out if this affects the overall disk size. 
We are currently heads down on moving build to GA but will try to evaluate this this.

**Comment by beaudryj** [comment]
@sajayantony Any word? Love to be able to start adopting this :)

**Comment by beaudryj** [comment]
@sajayantony been about 3 weeks, just wanted to check in and see if you have any good news for me

**Comment by sajayantony** [comment]
@beaudryj Sorry about not responding here. Team has been busy with moving this to GA.

@norrhthphoon could you evaluate how big this image is and see if we can cache it?

**Comment by northtyphoon** [comment]
@beaudryj thanks for the feedback. A couple of questions.

1. I don't see `microsoft/mssql-server-windows`. Do you mean `microsoft/mssql-server-windows-developer` or `microsoft/mssql-server-windows-express`? If yes, which tag? 
2. Which tag do you use for `microsoft/dotnet-framework`? 

I looked at the last 30 days history, I saw quite a few builds using `microsoft/dotnet-framework:4.7.2*` images but just 2 builds using `microsoft/mssql-server-windows-developer` image.

**Comment by beaudryj** [comment]
Here are the images we would be frequently pulling:

microsoft/mssql-server-windows-express:lastest
microsoft/mssql-server-windows-express:1709
microsoft/dotnet-framework:4.7.2-sdk
microsoft/dotnet-framework:4.7.2-windowsservercore-1709-sdk

**Comment by beaudryj** [comment]
any updates? on this

**Comment by northtyphoon** [comment]
We plan to cache the latest dotnet-framework images in short-term. For others, we are working with Windows team on a long-term solution to allow us serve more image cache requests.

**Comment by beaudryj** [comment]
so no plans to speed up my SQL builds :/ Would love to cut down those 40 minute Pull/Builds

**Comment by vin-yu** [comment]
Member from the SQL Server team here. We're planning to have up-to-date/regularly updated SQL Server + Windows containers that works with all editions in the future. In the meantime, instead of building on top of the existing microsoft/mssql-server-windows-developer (not kept up-to-date and hence the slow pulls because this pulls old windows layers), we recommend building your own with something like this: 

https://github.com/Microsoft/mssql-docker/blob/master/windows/mssql-server-windows-developer/dockerfile

**Comment by sajayantony** [comment]
We are working to improve the overall experience and this is now tracked as a part of the task startup performance work. Closing since the only work around is as @vin-yu pointed out.
