### ISSUE TITLE
Webhooks not firing on Delete when using AZ CLI TO Delete

### ISSUE THREAD

**Issue by beaudryj** [Azure/acr#126]
**BUG REPORT**:

**What happened?**: I spent a bit of my day writing out an azure function to post `Deletes` to my Slack and upon running my shiny new Delete Script I noticed that the Azure Container registry Webhooks were not being fired when I interacted with my registry via Az CLI. 

Additionally could tag be added to the "Delete Event Schema" like in Push 

```
{
  "id": "cb8c3971-9adc-488b-bdd8-43cbb4974ff5",
  "timestamp": "2017-11-17T16:52:01.343145347Z",
  "action": "push",
  "target": {
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "size": 524,
    "digest": "sha256:80f0d5c8786bb9e621a45ece0db56d11cdc624ad20da9fe62e9d25490f331d7d",
    "length": 524,
    "repository": "hello-world",
    "tag": "v1"
  },
```
Here is the push schema, would love to have a tag field on Delete I could use instead of looking like I kill my Repo everytime

**Comment by sajayantony** [comment]
Sorry that this wasn't followed up on time. @beaudryj could you please reopen if you are still facing this.
