### ISSUE TITLE
Enable AKS to use ACR with Content Trust Enabled

### ISSUE THREAD

**Issue by marty2bell** [Azure/acr#127]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature

**What happened?**:
Content Trust has been released in preview for ACR, but I can't see anywhere were we can enable content trust within AKS as a consumer of the ACR?

**What did you expect to happen?**:
Pull docker images with content trust enabled

**How do you reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment (if applicable to the issue)**:

**Comment by sajayantony** [comment]
Should be tracking this as an AKS issue 
@iainfoulds any way to move this over to the right repo?

**Comment by squillace** [comment]
This should be added to https://github.com/Azure/AKS.

**Comment by SteveLasker** [comment]
@marty2bell, I'd clone this for you, but it would lose your tracking abilities. Please just copy/paste this over to https://github.com/Azure/AKS

**Comment by marty2bell** [comment]
OK, Thanks
