### ISSUE TITLE
Consider supporting base image rebuilds for more registries

### ISSUE THREAD

**Issue by nphmuller** [Azure/acr#133]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature request

We have a couple of images that use quay.io as their image repositories. But some even use their own public registry. For example Elasticsearch, which uses docker.elastic.co.

It would be great if registries like these could be supported for the auto base image rebuilds.

Some ways this could be implemented:
- Support custom web hooks for image rebuilds. (although this would require the registry the support webhooks).
- Periodically check (pull) for base image updates.

**Comment by SteveLasker** [comment]
Thanks nick. This is possible and we have left the design open for additional registries and we’re just waiting for feedback like this.  The best way to make feature requests is to post to user voice. https://aka.ms/ACR/uservoice. This way we can stack rank based on customer votes, adding the complexity of course. Global replication is complex and not highly voted, just as an example.

**Comment by nphmuller** [comment]
Thanks. I've left my feedback here: https://feedback.azure.com/forums/903958-azure-container-registry/suggestions/31243153-auto-build-with-os-framework-patching
