### ISSUE TITLE
ACR native repo security scanning capability. 

### ISSUE THREAD

**Issue by garethmorris78** [Azure/acr#139]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

**What happened?**:
No "inbuilt" scanning of docker images within ACR.  Currently 3rd party software can be purchased that integrates to ACR and provides image scanning function.  

**What did you expect to happen?**:
ACR to have a native scanning capability of docker images for security vulnerabilities and best practices. Whilst there are open source and commercial tools available a native scanning capability ( even is offered on a paid SKU) would be preferable. 

**How do you reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**: Now ACR has a helm chart repo additional scanning capability would provide functionality on par with CNCF Sandbox project  https://landscape.cncf.io/selected=harbor

**Environment (if applicable to the issue)**:
Using ACR to host docker images deployed on an AKS Cluster.

**Comment by tomkerkhove** [comment]
I certainly agree, this would be major!

**Comment by SteveLasker** [comment]
Hi folks,
As noted, we do have 3rd party support. Our goal has always been to have a pluggable model, consistent with standard [OCI Distribution](https://github.com/opencontainers/distribution-spec/) and [proposed designs of consistency](https://stevelasker.blog/2019/08/25/oci-artifacts-and-a-view-of-the-future/) for 3rd and 1st party. Just as windows comes with Defender, by default, customers can swap out Defender for other vulnerability scanners. In this case, we've led with 3rd parties. 
In the next months, Azure Security Center will be providing container registry vulnerability scanning, later expanding it's security support to container runtimes. 
We don't yet have any official dates, but it's only fair to state the obvious, that we recognize registry scanning is table stakes

**Comment by sajayantony** [comment]
This is now in preview - [Security Scanning Integration with ACR](https://docs.microsoft.com/en-us/azure/security-center/azure-container-registry-integration?toc=/azure/container-registry/toc.json&bc=/azure/container-registry/breadcrumb/toc.json)
