### ISSUE TITLE
az acr helm repo push fails with --force, if the chart doesn't already exist

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr#142]
**BUG REPORT**:
When standardizing an automated deployment, a standard script would be created. We rightly support the `--force` command to explicitly require someone to opt-in to overriding an existing image/version.
However, the current behavior will fail if the chart-version doesn't already exist.
This would require someone to first verify the chart-version exists before calling `--force`.

**What happened?**:

**What did you expect to happen?**:
`--force` to override if the chart-version exists, and simply push if it doesn't exist. Essentially, I should be able to use `--force` and it always work.

**How do you reproduce it (as minimally and precisely as possible)?**:
`ac acr helm push ` a chart that doesn't yet exist. 

**Anything else we need to know?**:

**Environment (if applicable to the issue)**:
Prod

**Comment by ferantivero** [comment]
@SteveLasker just to mention that I wasn't aware of this issue in here and open this as feature request under Azure/azure-cli#7778

**Comment by djyou** [comment]
Fixed from version `2.1.12`.
