### ISSUE TITLE
Whitelist ACR webhook request by IP/Hostname?

### ISSUE THREAD

**Issue by TheMacStack** [Azure/acr#145]
Hi, I'm looking to lock down traffic to a endpoint that exists only to receive the POST from an ACR Webhook but cant work out what is the source IP/Domain name for the webhook request (Why i cannot get it from my logging is another discussion).

Anyone have any ideas what might be the domain/hostname that the webhook POST's originate from?

ACR is in West Europe in this case.

Thanks

**Comment by TheMacStack** [comment]
i did this with basic auth instead  using the custom header field of the webhook

**Comment by rburgstaller** [comment]
@TheMacStack can you explain a bit more?
