### ISSUE TITLE
az acr repository show-tags --repository helloworld --order-by to support alpha

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr#148]
**BUG REPORT**:

**What happened?**:
For tooling scenarios, users may script out a choice of a user. To support defaults, implicitly set in code, we should support all sorting options on --order-by.

**What did you expect to happen?**:
All sorting options available on --order-by
time_asc, time_desc, alpha_asc, alpha_desc, created_time_asc, created_time_desc

**How do you reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment (if applicable to the issue)**:

**Comment by sajayantony** [comment]
Order by supported 
```
   --orderby               : Order the items in the results. Default to alphabetical order of
                              names.  Allowed values: time_asc, time_desc.
```
