### ISSUE TITLE
az acr task list -o table should be more condensed

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr#150]
**BUG REPORT**:

**What happened?**:
When running:
`az acr task list -o table` we get a fairly wide listing, that wraps.
The intention of -o table is simple, human readable form. To have wide columns included by default makes the default not very human readable
```
Name                         PLATFORM    STATUS    COMMIT TRIGGER    SOURCE REPOSITORY                             BRANCH    BASE IMAGE TRIGGER    IMAGE       NAMES                                                      PUSH ENABLED
---------------------------  ----------  --------  ----------------  --------------------------------------------  --------  --------------------  -----      ----------------------------------------------------------  --------------
sql-server                   Linux       Enabled   Enabled           https://github.com/stevelasker/foo master    Runtime               ['mss      ql/server:{{.Build.ID}}', 'mssql/server:2017-CU12-ubuntu']  True
```
**What did you expect to happen?**:
Shorter Column List to include:
```
Name                         PLATFORM    STATUS    COMMIT TRIGGER    BASE IMAGE TRIGGER  
```
Users that want more detail can use the `-o json --query` to cherry pick columns

**How do you reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment (if applicable to the issue)**:

**Comment by sajayantony** [comment]
@ehotinger can we close this?
