### ISSUE TITLE
ACR Build - Base image windows server core 2019/1809

### ISSUE THREAD

**Issue by TBurda** [Azure/acr#157]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG
**What happened?**:
Cannot build images, when base image is windows server core 2019/1809. When will base image be ready in azure ?

Error massage:
1809: Pulling from windows/servercore
a Windows version 10.0.17763-based image is incompatible with a 10.0.17134 host

**How do you reproduce it (as minimally and precisely as possible)?**:
az acr build --registry logeto --image windowsservercore:1809 --os windows --build-arg WINDOWS_VERSION=1809 .

Dockerfile:
ARG WINDOWS_VERSION
FROM mcr.microsoft.com/windows/servercore:${$WINDOWS_VERSION}

**Comment by SteveLas** [comment]
Hi Tomas,
Normally, we’d have a windows update out in days. This one is pretty big so it will take us a bit to roll out. With the holiday blackout, we’re seeing how fast we can support 1809.

On Nov 17, 2018, at 12:26 AM, Tomáš Burda <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this a BUG REPORT or FEATURE REQUEST?:
BUG
What happened?:
Cannot build images, when base image is windows server core 2019/1809. When will base image be ready in azure ?

Error massage:
1809: Pulling from windows/servercore
a Windows version 10.0.17763-based image is incompatible with a 10.0.17134 host

How do you reproduce it (as minimally and precisely as possible)?:
az acr build --registry logeto --image windowsservercore:1809 --os windows --build-arg WINDOWS_VERSION=1809 .

Dockerfile:
ARG WINDOWS_VERSION
FROM mcr.microsoft.com/windows/servercore:$<http://mcr.microsoft.com/windows/servercore:$>{$WINDOWS_VERSION}

**Comment by northtyphoon** [comment]
@TBurda thanks for your patience. We have enabled WS2019 in all regions. Please give a try. Let us know if you have any questions.
