### ISSUE TITLE
Cannot config build context path in rest api.

### ISSUE THREAD

**Issue by adashen** [Azure/acr#159]
**FEATURE REQUEST**

**What happened?**:
I am send an scheduleRun rest request to build the image in git repo. My dockerfile is not under root, I could specify the dockerfile path in the ""dockerFilePath" property. However I could not specify the build context path. And the build failed because of cannot find the correct file to be copied.

**What did you expect to happen?**:
Have a property to specify the context path

**Comment by northtyphoon** [comment]
@adashen, to specify build context based on git repo, you can use the source url like the following

`https://github.com/Azure/acr.git#master:samples/java/task`

`master` is the branch name.
`sample/java/task` is the build context folder.

In the above case, the dockerfile needs to be relative to the context folder. Eg, if the dockerfile file is `sample/java/task/Dockerfile`, you need to set `Dockerfile` in `dockerFilePath`.

You can see an example in https://github.com/Azure/acr/blob/master/samples/java/task/src/main/java/com/microsoft/azure/management/containerregistry/samples/ManageTask.java#L69

For other build context cases, you can take a look at docker build spec
https://docs.docker.com/engine/reference/commandline/build/#git-repositories

**Comment by adashen** [comment]
@northtyphoon , Thanks for information, it works. So sourceLocation in DockerBuildRequest is contextPath, and dockerFilePath should be relative to sourceLocation path. Better to have more detail info in docs.

**Comment by sajayantony** [comment]
@northtyphoon  is this our rest API documentation?

**Comment by northtyphoon** [comment]
@adashen, thanks for all the feedbacks. I believe you are unblocked so close the issue. Let us know if you have other questons.
