### ISSUE TITLE
Task run error for context path with # in Azure DevOps repos

### ISSUE THREAD

**Issue by mgrabarz** [Azure/acr#161]
Noticed an inconsistent behaviour and potentially bug in ACR tasks when using az cli.

**When I define a build task in ACR for github context, everything seems to be working flawlessly**
_az acr task create -r <my_acr> --name <task_name> --image my-node:10-alpine --context https://github.com/<account_name>/<project_name>#:10/alpine --file Dockerfile --branch master --git-access-token <mytoken>
result: success
az acr task run -r <my_acr> --name <task_name>
result: success_

**For Azure DevOps it fails:**
_az acr task create -r <my_acr> --name <task_name2> --image my-node:10-alpine --context https://dev.azure.com/<account_name>/<project_name>/_git/docker_node#:10/alpine --file Dockerfile --branch master --git-access-token <mytoken>
result: success
az acr task run -r <my_acr>--name <task_name2>
result: Queued a run with ID: cf3
Waiting for an agent...
2018/11/06 11:50:31 Using acb_vol_eff6c9f0-32af-41bd-a5fe-b8b456ca7242 as the home volume
2018/11/06 11:50:31 Setting up Docker configuration...
2018/11/06 11:50:32 Successfully set up Docker configuration
2018/11/06 11:50:32 Logging in to registry: <my_acr>.azurecr.io
2018/11/06 11:50:33 Successfully logged in
2018/11/06 11:50:33 Executing step ID: build. Working directory: '', Network: ''
2018/11/06 11:50:33 Obtaining source code and scanning for dependencies...
2018/11/06 11:50:36 Successfully obtained source code and scanned for dependencies
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /workspace/build/Dockerfile: no such file or directory
Error: failed to run step ID: build: exit status 1
Run ID: cf3 failed after 9s_

**Then when I try to move part of the path to file name, it works again:**
_az acr task create -r <my_acr> --name <task_name3> --image my-node:10-alpine --context https://dev.azure.com/<account_name>/<project_name>/_git/docker_node --file 10/alpine/Dockerfile --branch master --git-access-token <mytoken>
result: success
az acr task run -r <my_acr>--name <task_name3>
result: success_

**Comment by northtyphoon** [comment]
Looks the builder parser just needs to support new DevOps git url

https://github.com/Azure/acr-builder/blob/master/builder/parse.go#L60

/cc: @rosanch @ehotinger

**Comment by ehotinger** [comment]
Closing this. It can be tracked at https://github.com/Azure/acr-builder/issues/353 - PR is out to support the new devops urls.
