### ISSUE TITLE
Dark theme on the portal is unreadable

### ISSUE THREAD

**Issue by sajayantony** [Azure/acr#163]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG

**What happened?**:
Black theme is unreadable. 

**Environment (if applicable to the issue)**:
 - Portal Black theme 
https://twitter.com/andyfisher100/status/1069975952803942400
![image](https://user-images.githubusercontent.com/1821104/49462131-28741f80-f7aa-11e8-962b-9bf4e4ab2daa.png)

**Comment by sajayantony** [comment]
Update: Fix is being rolled out.

**Comment by ankurkhemani** [comment]
Fix is now rolled out to all regions.
