### ISSUE TITLE
Documentation on Helm repo webhooks not present

### ISSUE THREAD

**Issue by tillig** [Azure/acr#165]
Feature request: There is documentation [on how to use the Azure Container Registry webhooks](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-webhook-reference) and the schema shows what container-related webhooks look like. However, there's no docs about whether webhooks exist for Helm repo events and, if they do, what one of those webhooks might look like.

**Comment by sajayantony** [comment]
This is currently only in PR - Azure/azure-cli#8076
We will follow up with Docs /cc @dlepow

**Comment by tillig** [comment]
Excellent. Definitely need to include schema info and an example. I look forward to it. Thanks!

**Comment by jaysterp** [comment]
@tillig Due to deployment blackouts around the holidays you can expect these new Helm webhook events (along with detailed docs) in early January :) We look forward to hearing your feedback on this feature!

**Comment by dlepow** [comment]
@iainfoulds FYI. Doc work item added to backlog. Thanks!

**Comment by dlepow** [comment]
@tillig - Just to let you know that we have published information about Helm repo webhooks in these articles:

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-webhook
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-webhook-reference
https://docs.microsoft.com/en-us/azure/event-grid/event-schema-container-registry

@sajayantony - I think we can close this issue now. Thanks!

**Comment by sajayantony** [comment]
Thanks @dlepow . @tillig 
Closing this issue since this has now been merged into the MicrosoftDocs repo.
