### ISSUE TITLE
Is it possible to limit the role required for running az acr build to something less than Contributor

### ISSUE THREAD

**Issue by jonaspetersorensen** [Azure/acr#174]
**FEATURE REQUEST**:

We have a k8s cicd solution which use a SP to pull and push images to ACR, and we can limit required permissions for this use case to the role "AcrPush".
Now we are looking into using ACR for automated builds as well, but to be able to use acr build we see no other way to get this to work than to grant the SP the role "Contributor".

We would like to use a less powerful role than Contributor to be able to build images in acr, say a "AcrBuild" role that would also grant "AcrPush" as in most build use cases you would pull, build and push images to the same registry.

**Environment (if applicable to the issue)**:
 - Azure CLI

**Comment by sajayantony** [comment]
@mnltejaswini @northtyphoon - since you folks are working on the auth story for task runners. 
@jonaspetersorensen - Build tasks can be created only by writes of the registry, Do you want to scope who can kick of the builds or configure what the build can do?

**Comment by mnltejaswini** [comment]
@jonaspetersorensen  There is no built-in role for restricting build/run operations. But ACR exposes several operations that can be used in custom role to provider granular RBAC to the resources. For example in your case, you can create a role "MyAcrBuilder" with the following actions 

**Microsoft.ContainerRegistry/registries/scheduleRun/action**  -- that can only schedule builds/runs

And give the SP the roles AcrPush, MyAcrBuilder. The SP will only be able to pull,push and queue builds. 

For more operations that are exposed by ACR please refer to
 https://docs.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations#microsoftcontainerregistry

**Comment by jonaspetersorensen** [comment]
@sajayantony In our case we would use predefined pipelines, so that means that we want the SP to start the builds and push the result to the registry. The suggestion from @mnltejaswini seems to be what we are looking for (though it would be nice with a built-in role as well, hehe ;) )

**Comment by sajayantony** [comment]
Yes we discussed the possibility of having a built-in role like 
ACRTaskRunner which will have an ability to do `az acr build` since there are a couple of permissions required. 
so basically your assignment might reduce to 
```
az role assingment create --role ACRPush
az role assignment create --role ACRTaskRunner
```

If we did introduce this role.

**Comment by sajayantony** [comment]
Including @SteveLasker to ensure we capture this.

**Comment by msyihchen** [comment]
@sajayantony @SteveLasker Any updates?

**Comment by sajayantony** [comment]
@jonaspetersorensen we are not currently working on creating custom roles for this scenario. Feel free to open the feature request in https://aka.ms/acr/uservoice and we will prioritize. /cc @SteveLasker

**Comment by buzztaiki** [comment]
I have tried it and `az acr build` can be executed with the following permissions.

```json
  "permissions": [
    {
      "actions": [
        "Microsoft.ContainerRegistry/registries/read",
        "Microsoft.ContainerRegistry/registries/scheduleRun/action",
        "Microsoft.ContainerRegistry/registries/listBuildSourceUploadUrl/action",
        "Microsoft.ContainerRegistry/registries/runs/listLogSasUrl/action"
      ],
      "dataActions": [],
      "notActions": [],
      "notDataActions": []
    }
  ]
```

**Comment by Costo** [comment]
Here's the feature request: https://feedback.azure.com/d365community/idea/16c03193-0d25-ec11-b6e6-000d3a4f0858
