### ISSUE TITLE
Please add Log Analytics integration to ACR

### ISSUE THREAD

**Issue by Penberthy** [Azure/acr#178]
All my my other services output to log analytics so i can define actions to for all my none Happy Path workflows, errors and general diagnostic needs.

My preference would be to add Log Analytics via the standard  "az monitor diagnostic-settings create" and the portal of course.

Thanks

**Comment by msyihchen** [comment]
We are working on it.

**Comment by sajayantony** [comment]
This is now in preview - https://aka.ms/acr/audit-logs
