### ISSUE TITLE
Storage account not found error

### ISSUE THREAD

**Issue by afengli** [Azure/acr#18]
when we try to create ACR using a given storage account, the operation fails with "BadRequest":

"message": "Storage account xxxx was not found in subscription xxxx."

However the storage account is there already, both ACR and storage account are created under ARM.

Is this a known issue?

**Comment by sivagms** [comment]
could you please check if the storage account is a classic storage account ?

**Comment by djyou** [comment]
Are you using CLI or Portal? Can you also verify if the storage account exists in the same subscription?

**Comment by afengli** [comment]
hi, using portal, it exists in the same subscription. it is not classic storage account.

**Comment by SajayAntony** [comment]
This is issue is currently being fixed and we expect it to roll out this week.

**Comment by SajayAntony** [comment]
This fix has now been deployed to all regions.
