### ISSUE TITLE
az acr import authentication

### ISSUE THREAD

**Issue by jzoran05** [Azure/acr#181]
**BUG REPORT (User Confused probably) 

**What happened?**:
I am trying to use ACR Task to import image from docker hub into my ACR by using  "az acr import" command.
I did:
- az login (OK)
- az acr login (OK)

 and then tried to run import with this command:

 az acr import -n <my azure registry name> --source docker.io/mcr.microsoft.com/windows/servercore:ltsc2016 --username "<my docker hub user>" --password "<my docker hub password>"-t servercore:ltsc2016

...and I got error:

Deployment failed. Correlation ID: 947b1204-953c-4edd-bcfc-fc925eba4f3f. Operation registries-cf1e87e6-20aa-11e9-a5c3-f06e0bc28714 failed. Resource /subscriptions/3aba1271-ca5f-49e8-9229-2214ec0ac30c/resourceGroups/demos-acr/providers/Microsoft.ContainerRegistry/registries/aksdemoreg Invalid message Unauthorized Unauthorized {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"mcr.microsoft.com/windows/servercore","Action":"pull"}]}]}

It is clear that some authentication has failed (according to the error message) but I am not clear why. user/pwd for docker hub were provided in the parameters, az acr login was successful and done prior invoking the command. Am I doing something wrong or there is some issue (bug) with the az acr import? Can you advise please?

**What did you expect to happen?**:
I expected image from docker hub to be imported to my ACR

**How do you reproduce it (as minimally and precisely as possible)?**:
 az acr import -n <my azure registry name> --source docker.io/mcr.microsoft.com/windows/servercore:ltsc2016 --username "<my docker hub user>" --password "<my docker hub password>"-t servercore:ltsc2016

**Environment (if applicable to the issue)**:
 - Azure CLI/Powershell/SDK version: Azure CLI 2.0.055
 - OS version: Windows 10
 - Datetime (UTC) when the issue occured

   
   If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send email to acrsup@microsoft.com.

**Comment by jzoran05** [comment]
I tried first without user/pwd... it was the same error...

**Comment by NatalieYuGong** [comment]
which version of cli are all of you running?

**Comment by sajayantony** [comment]
@jzoran05 I spoke too soon. 
You import command needs to be 
`az acr import  --source mcr.microsoft.com/windows/servercore:ltsc2016 -t import-test/servercore:ltsc2016`

Please remove the **docker.io** prefix.

**Comment by sajayantony** [comment]
Please reopen if you face an issue during import.

**Comment by kumarunkulawardene** [comment]
> Please reopen if you face an issue during import.

I tried the sample you gave and it works;
az acr import --name xxxxxxx.azurecr.io --source mcr.microsoft.com/windows/servercore:ltsc2016 -t import-test/servercore:ltsc2016

But I'm getting error when I try to copy image from one of my other acr repos which allows anonymous access. I can pull from the source ACR and push to target ACR without no issues. But using the same account when I try to import the image from source acr I get the following error;

Deployment failed. Correlation ID: 6aa4c693-3a51-4560-bbb4-e8191cdfe64a. Operation registries-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX failed. Resource /subscriptions/XXXXX-XXXX-XXXX-XXXX-XXXXXXXX/resourceGroups/xxx-rg/providers/Microsoft.ContainerRegistry/registries/XXXcoe Invalid message Unauthorized Unauthorized {"errors":[{"code":"UNAUTHORIZED","message":"authentication required, visit https://aka.ms/acr/authorization for more information."}]}

![image](https://user-images.githubusercontent.com/60240127/126085999-4cd021b4-f006-4b42-84ac-a4c3466e8e0b.png)
