### ISSUE TITLE
Prevent "AcrPush" role to overwrite existing image

### ISSUE THREAD

**Issue by TqrHsn** [Azure/acr#184]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST
**What happened?**:
AcrPush role can accidentally overwrite an existing image in registry
**What did you expect to happen?**:
An error should be returned if same image is being pushed with different hash
**How do you reproduce it (as minimally and precisely as possible)?**:
docker push an image. Tag another image to same label and docker push.
**Anything else we need to know?**:

**Environment (if applicable to the issue)**:
 - Azure CLI/Powershell/SDK version
 - Docker version
 - OS version
 - Datetime (UTC) when the issue occured
 - Registry and image names
   
   If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send email to acrsup@microsoft.com.

**Comment by sajayantony** [comment]
To avoid accidental overwrites could you use https://docs.microsoft.com/en-us/azure/container-registry/container-registry-image-lock

**Comment by SteveLasker** [comment]
thanks for the issue. We hope the tag locking feature meets your needs.
