### ISSUE TITLE
The token stored by az acr login -n <registry name> is expired quickly(one hour) 

### ISSUE THREAD

**Issue by andxu** [Azure/acr#191]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature Request
**What happened?**:
The token stored by az acr login -n <registry name> is expired quickly(one hour)
**What did you expect to happen?**:
I'd like to extend the expiration time to at least one day.
**How do you reproduce it (as minimally and precisely as possible)?**:
az acr login -n andyreg && echo andyreg.azurecr.io | docker-credential-acr-windows get
expand the token to https://jwt.io/
**Anything else we need to know?**:
no

   
   If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send email to acrsup@microsoft.com.

**Comment by sajayantony** [comment]
Currently we honor the AAD token. We did investigate https://github.com/Azure/acr-docker-credential-helper but did not continue work on this.

**Comment by sajayantony** [comment]
@yuwaMSFT2 - once we have rolled out he longer access token fix, could you please close this thread?

**Comment by msyihchen** [comment]
@andxu We've extended it to 3 hours. Can you take a try? //cc @yuwaMSFT2 @sajayantony
