### ISSUE TITLE
.git in repo URL causes automatic build to not happen

### ISSUE THREAD

**Issue by bradygaster** [Azure/acr#193]
**Is this a BUG REPORT or FEATURE REQUEST?**:
This is a bug (but a little one I was able to work through). 

**What happened?**:
The documentation section on [Creating a build task](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-build-task#create-a-build-task) demonstrates that the `.git` suffix needs to be at the end of the repo URL. I followed these instructions and the build worked when I ran it manually. Then, I did a `git commit, push` to update my repository. 

**What did you expect to happen?**:
I expected that the build would automatically happen. The build did not happen. So I deleted the task and re-created it using the content from the doc, but this time I omitted the `.git` suffix on the git repo URL. The next time I did a `git commit, push` it worked as I expected it to work. 

**How do you reproduce it (as minimally and precisely as possible)?**:
The above commentary is pretty much everything. 

**Anything else we need to know?**:
I loved the experience. It made life super-easy and I didn't have to worry about having Docker installed locally or having to have a physical Windows machine on which to do my work. This is a game-changer, to be able to build my images in the cloud rather than on my machine. 

**Environment (if applicable to the issue)**:
 - Azure CLI/Powershell/SDK version
Azure CLI v.2.0.55

 - Docker version
N/A

 - OS version
Mac Mojave

 - Datetime (UTC) when the issue occured
8 AM PST 2019-02-28

 - Registry and image names
dotnetcoretests, webapplication
   
   If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send email to acrsup@microsoft.com.

**Comment by jaysterp** [comment]
@bradygaster Thank you for reaching out. We are looking into this now. Are you using a GitHub or Azure DevOps repo as your context?

**Comment by bradygaster** [comment]
@jaysterp i was using a GitHub account.

**Comment by sajayantony** [comment]
@bradygaster - closing this for now and we can reopen this when we see this again with details.

**Comment by bradygaster** [comment]
apologies for not having closed it already. The next time I have an opportunity to iterate on this i'll repeat it, then do the same thing for Azure DevOps repos and provide a comparison.
