### ISSUE TITLE
Unable to copy from public dockerhub

### ISSUE THREAD

**Issue by Xorima** [Azure/acr#196]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug

**What happened?**:

`Deployment failed. Correlation ID: d5246d22-93ba-4eb8-a837-375bb9b9f446. Operation registries-01aa08d2-418e-11e9-8412-1860248cc8bd failed. Resource /subscriptions/<id>/resourceGroups/<rg>/providers/Microsoft.ContainerRegistry/registries/<registry> Invalid message Unauthorized Unauthorized {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"python","Action":"pull"}]}]}`

**What did you expect to happen?**:

The public image will be imported into my registry

**How do you reproduce it (as minimally and precisely as possible)?**:
az login
`az acr import --name myrepo --source docker.io/python:2.7-alpine3.8 -t import-test/python:2.7-alpine3.8`

**Anything else we need to know?**:

using `az acr import --name myrepo --source mcr.microsoft.com/windows/servercore:ltsc2016 -t import-test/servercore:ltsc2111` works

**Environment (if applicable to the issue)**:
 - Azure CLI/Powershell/SDK version
```
azure-cli (2.0.57)

acr (2.1.13)
acs (2.3.16)
advisor (2.0.0)
ams (0.4.0)
appservice (0.2.12)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.7)
billing (0.2.0)
botservice (0.1.5)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.20)
consumption (0.4.2)
container (0.3.13)
core (2.0.57)
cosmosdb (0.2.7)
dla (0.2.3)
dls (0.1.7)
dms (0.1.2)
eventgrid (0.2.1)
eventhubs (0.3.3)
extension (0.2.3)
feedback (2.1.4)
find (0.2.13)
hdinsight (0.3.0)
interactive (0.4.1)
iot (0.3.5)
iotcentral (0.1.5)
keyvault (2.2.10)
kusto (0.1.0)
lab (0.1.5)
maps (0.3.3)
monitor (0.2.9)
network (2.3.1)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.3)
rdbms (0.3.6)
redis (0.3.2)
relay (0.1.3)
reservations (0.4.1)
resource (2.1.9)
role (2.3.1)
search (0.1.1)
security (0.1.0)
servicebus (0.3.3)
servicefabric (0.1.12)
signalr (1.0.0)
sql (2.1.8)
sqlvirtualmachine (0.1.0)
storage (2.3.1)
telemetry (1.0.1)
vm (2.2.14)```
 - Docker version
```
docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false
```
 - OS version
Windows 10 18.09
 - Datetime (UTC) when the issue occured
08-03-2019 10:40
 - Registry and image names

   If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send email to acrsup@microsoft.com.

**Comment by mpmatti** [comment]
So what was the conclusion of this problem?

**Comment by ohadschn** [comment]
@mpmatti the source was malformed, should be `docker.io/library/python:2.7-alpine3.8` (and NOT `docker.io/python:2.7-alpine3.8` without the `library` component).
