### ISSUE TITLE
ACR build failed due to 'failed to scan dependencies'

### ISSUE THREAD

**Issue by Shuanglu** [Azure/acr#199]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
**What happened?**:
ACR build windows image failed due to 'failed to scan dependencies'
**What did you expect to happen?**:
build successfully or more clear error
**How do you reproduce it (as minimally and precisely as possible)?**:
az acr build --registry xxx -t xx . --os windows
The docker file is https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2017
And it failed due to below

2019/03/14 13:13:54 Output from dependency scanning: open c:\workspace\build\:wq: The filename, directory name, or volume label syntax is incorrect.
failed to run step ID: build: failed to scan dependencies: exit status 1

**Anything else we need to know?**:

**Environment (if applicable to the issue)**:
 - Azure CLI/Powershell/SDK version
 - Docker version
 - OS version
 - Datetime (UTC) when the issue occured
 - Registry and image names
  
acr 2.2.2 in CLI

   If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send email to acrsup@microsoft.com.

**Comment by ehotinger** [comment]
@Shuanglu can you try moving your Dockerfile to a subdirectory (i.e. `foo`) and then `cd foo && az acr build .` from there so that all the context isn't uploaded from your current working directory? It looks like you're uploading your entire Linux file system into a Windows host and there's some issues decompressing it. We can try to improve the error message for this.

**Comment by Shuanglu** [comment]
> @Shuanglu can you try moving your Dockerfile to a subdirectory (i.e. `foo`) and then `cd foo && az acr build .` from there so that all the context isn't uploaded from your current working directory? It looks like you're uploading your entire Linux file system into a Windows host and there's some issues decompressing it. We can try to improve the error message for this.

This works. thanks!

**Comment by sajayantony** [comment]
So can we close this?

**Comment by Shuanglu** [comment]
> So can we close this?

sure
