### ISSUE TITLE
How to use Docker HTTP V2 API?

### ISSUE THREAD

**Issue by xenalite** [Azure/acr#207]
Question:
How can I use the ACR Docker HTTP V2 API?
The FAQ says to use this endpoint: https://instance.azurecr.io/v2/
This gives me a 401 response with a `WWW-Authenticate` header.
```
Www-Authenticate: Bearer realm="https://ixsamldem20cr01dev.azurecr.io/oauth2/token",service="ixsamldem20cr01dev.azurecr.io"
```

How should I use this token endpoint to obtain a token?
I would like to obtain a token from admin U / P.
Once I have the token, how do I include it with API requests?

My use case:
I want use U / P authentication to connect to the registry API endpoint and validate that a specific image tag exists. This would be using purely HTTP calls without need for Docker client or Azure CLI.

**Comment by SteveLasker** [comment]
Hi Xenalite
https://github.com/Azure/acr/blob/master/docs/AAD-OAuth.md#azure-container-registry-refresh-tokens-and-access-tokens

should provide what you’re looking for.

**Comment by sajayantony** [comment]
Closing since we have updated the docs and added sample scripts. Please reopen if required.
