### ISSUE TITLE
Support SemVer 2.0 metadata tags (+) in the name of Helm Charts

### ISSUE THREAD

**Issue by leyshon** [Azure/acr#209]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature request
**What happened?**:
Create a helm chart with a version that includes metadata tags (+1234) and try to upload it to ACR. It returns "Error: You have requested filename that is not supported"
**What did you expect to happen?**:
As per the Helm documentation, metadata tags are supported so ACR should support filenames that include them
**How do you reproduce it (as minimally and precisely as possible)?**:
```
Create a chart with a version number that includes +something
helm package <chartname>
az acr helm push <chartname>

**Comment by sajayantony** [comment]
Unfortunately ACR doesn't support this at this point for helm preview. The current direction for helm-3 is unification of registry images and charts and so the name will have to be in line with a tag ref scheme which will allow any OCI registry to push and pull helm charts. 
/cc @shizhMSFT and @djyou  to comment here.

**Comment by streakcu** [comment]
Are there other parts of SemVer 2.0 that ACR doesn't comply with?

**Comment by shizhMSFT** [comment]
The regex for tag ref is `[\w][\w.-]{0,127}` and the regex for SemVer 2 is
```regex
v?([0-9]+)(\.[0-9]+)?(\.[0-9]+)?(-([0-9A-Za-z\-]+(\.[0-9A-Za-z\-]+)*))?(\+([0-9A-Za-z\-]+(\.[0-9A-Za-z\-]+)*))?
```

In other words, besides the plus `+` symbol, we have a size limit of 127.

**Comment by sajayantony** [comment]
Closing now since there is no action at this time since  ACR is unifying on helm3 which will be registry based.
