### ISSUE TITLE
[Question] How to quickly tag manifests?

### ISSUE THREAD

**Issue by xenalite** [Azure/acr#213]
We run ACR builds to create our images. 
`az acr build --registry registry --file file --image image --os os dir`

They are versioned with Semver with build metadata like such:
`1.2.3-alpha.456+789`

The image tag we put is in the format since Docker tags do not support `+`:
`1.2.3-alpha.456_789`

We would also like to tag the resulting manifest like so:
`1.2.3-alpha.456`
`1.2.3-alpha`
`1.2.3`
`1.2`
`1`
`alpha`
`latest`

I can generate these tag myself with PowerShell, but how to I tag an existing manifest?
I could `docker pull`, `docker tag`, `docker push`, but it's neither quick and now I have to authenticate and have docker installed. I'd rather just use Azure CLI.

So I tried the import instead:
`az acr import -n target --source source/image:tag -t image:newtag`
But the import is not quick, even if source and target are the same registry and both tags already exist. It takes 15 seconds per command, so 105s per image to assign new tags, where it takes 25s to build the image in the first place. And then we have 8 images to build per commit.

**Comment by sajayantony** [comment]
Multiple tags are already supported for build. 
I believe we should add this to the cli docs that —image is a multi option argument. 
@northtyphoon ?

**Comment by xenalite** [comment]
@sajayantony Thank you.
I can confirm this functionality works in Azure CLI `2.0.63`.

```
PS C:\temp\acr-tagging> az acr build -r registry -t acr-tagging/sample:latest -t acr-tagging/sample:latest2 -f .\Dockerfile .
```

![image](https://user-images.githubusercontent.com/4509839/56756379-9042fb00-6789-11e9-9159-e9bf0a85a470.png)
