### ISSUE TITLE
HTTP V2 API /blobs/ endpoint "Authentication information is not given in the correct format."

### ISSUE THREAD

**Issue by leongold** [Azure/acr#217]
This seems broken to me, however I realise it works via Docker's CLI, so I'm probably doing something wrong.

I'm trying to use the `/blobs` endpoint to fetch image config, and am hitting `Authentication information is not given in the correct format.`

My flow is first to challenge, extract `service`, `realm`, and `scope`, and get a token. This works. My next step is to call the `/blobs` endpoint... which fails. I'm using --

`Authorization: Bearer <token here>` as part of my header.

Note: the exact same flow succeeds with Docker Hub.

Any hints are greatly appreciated!

**Comment by leongold** [comment]
hey guys, any hints? i've reviewed https://docs.docker.com/registry/storage-drivers/azure/, how relevant is this?

**Comment by sajayantony** [comment]
Have you reviewed https://github.com/Azure/acr/blob/master/docs/AAD-OAuth.md ?

**Comment by leongold** [comment]
Hey @sajayantony, I have, but I might be missing something... I'm successful in using basic/bearer tokens up until the point I need to call the `/blobs/*` endpoint.

I'll be happy to re-review and retrace my steps, however I have a feeling there's something missing regarding the `/blobs` endpoint, where I understand Azure's storage service is also involved.

I'd very much like and would VERY appreciate a confirmation (or otherwise) that `/blobs` is accessible using the steps mention in the documentation you've provided (https://github.com/Azure/acr/blob/master/docs/AAD-OAuth.md)

**Comment by sajayantony** [comment]
Did you follow the location header returned by the blobs url? That URL is a SASURL and you should not forward the bearer token on the follow.

**Comment by leongold** [comment]
I have not! I will try and report back. Thanks!

**Comment by leongold** [comment]
These are the headers I'm getting:
```
> { server: 'nginx',
  date: 'Wed, 08 May 2019 06:31:34 GMT',
  'content-type': 'application/json; charset=utf-8',
  'content-length': '151',
  connection: 'close',
  'access-control-expose-headers':
   'Docker-Content-Digest, WWW-Authenticate, Link, X-Ms-Correlation-Request-Id',
  'docker-distribution-api-version': 'registry/2.0',
  'strict-transport-security':
   'max-age=31536000; includeSubDomains, max-age=31536000; includeSubDomains',
  'www-authenticate':
   'Bearer realm="https://*****.azurecr.io/oauth2/token",service="snykgoof.azurecr.io",scope="repository:*****:pull"',
  'x-content-type-options': 'nosniff',
  'x-ms-correlation-request-id': 'c6cc16cc-ac06-41e7-a475-d1d77e09b006' }
```

Looks like standard V2 response (I'm calling `/blobs/<sha digest>`). Is this ok? what should I do next? doesn't appear like SASURL?

**Comment by yuwaMSFT2** [comment]
It tells you that you need to get an access token in order to access this resource.
You can follow this to get an access token:
https://github.com/Azure/acr/blob/master/docs/Token-BasicAuth.md#get-a-pull-access-token-for-the-user

and then send the request to with bearer token received, similar to this:
https://github.com/Azure/acr/blob/master/docs/Token-BasicAuth.md#calling-an-azure-container-registry-api

For /v2/{repo}/blobs/sha256:xxxxx request, you should get a 307 response with a location header of blob SAS url. Just follow the url to get the real blob conent (without the Authorization header as suggested by Sajay)

**Comment by leongold** [comment]
Thanks so much for your help and bearing with me.

@yuwaMSFT2, these are the exact steps I've followed originally, however I'm receiving 401 instead of 307 as you see in my OP.

Just to once again retrace my steps:
1) I'm calling `/v2/{repo}/blobs/sha256:xxxxx` to get challenge parameters. So far so good.
2) I'm sending a request the bearer realm with scope and service as parameters. This works and I get an access_token. So far so good.
3) I'm using the access token (Bearer: <token>) as the value of the Authorization header, and am calling the endpoint  `/v2/{repo}/blobs/sha256:xxxxx` once again -- I receive the error in the OP.

**Comment by leongold** [comment]
BTW, for what it's worth, I'm using an Admin account.

**Comment by sajayantony** [comment]
Here is an example of using the bearer token 
```bash
$ curl -s -D -  -H "Authorization: Bearer $ACR_ACCESS_TOKEN" https://$REGISTRY/v2/hello-world/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 | grep Location
Location: https://wus2managed121.blob.core.windows.net/f0dbaeeb0e9d444484539e3cb9a03832-vztz6g30q1//docker/registry/v2/blobs/sha256/a3/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4/data?se=2019-05-08T07%3A57%3A20Z&sig=
```
You need to follow the location header. 
You can create the access token using AAD or using the admin creds. Either works as long as you create the correct scopes as described in the script here - 
https://github.com/Azure/acr/blob/master/docs/AAD-OAuth.md#docker-login-with-acr-access-token---single-repository-scope

**Comment by yuwaMSFT2** [comment]
@leongold which tool are you using to send request? Some tool may send the same Authorization header when follow the redirect URL. It will get you authorization error since the redirect URL doesn't expect it.
A workaround would be to send the request to /v2/blobs/xxxx WITHOUT following the link; once you get the 307 response, get the URL in the Location header in the response, and send another request to the redirect URL directly without any authorization header.

**Comment by leongold** [comment]
@yuwaMSFT2 I'm using nodejs `express` which may very well automatically redirect! I will check this and report back.

Thanks a lot!

**Comment by leongold** [comment]
Confirmed! by disabling automatic redirects, I've followed the location header without the authorization header and managed to access the blob.

Thanks guys! my only suggestion is perhaps to add a little relevant warning in the documentation.

Cheers!

**Comment by sajayantony** [comment]
Please feel free to close the issue if you are unblocked.

**Comment by yuwaMSFT2** [comment]
Thanks @leongold for the feedback. We will update our FAQ to include this issue.

**Comment by shizhMSFT** [comment]
@leongold We have updated our FAQ at https://github.com/Azure/acr/blob/master/docs/FAQ.md#authentication-information-is-not-given-in-the-correct-format-on-direct-rest-api-calls

**Comment by leongold** [comment]
Of course, sorry for the delay and thanks again!
