### ISSUE TITLE
ACR GitHub Actions for Container Uploading

### ISSUE THREAD

**Issue by runewake2** [Azure/acr#224]
** Feature Request **

I would like to be able to upload existing containers built in a GitHub Action to my Azure Container Registry.

Currently the user experience for uploading containers to the Azure Container Registry is convoluted and requires entering your own custom commands to make this work. I have been able to slightly work around this using the existing Azure CLI command, but this workflow is not ideal. [An example of what this looks like](https://raw.githubusercontent.com/WorldOfZero/dotcom/master/.github/main.workflow).

In the example a custom command written in the Azure CLI container runs `az acr build` to build and push my images to ACR. The result of this is a second image being built that will be different (it should be fairly close though since they're built from the same source)
 from the original images built and tested. Instead I would like to be able to upload the container I have already built to my ACR instance using `docker push` or some similar functionality. Ideally in the form of a custom GitHub Action providing this functionality.

I have attempted to use `az acr login` to authenticate with ACR but that process seemed to have requirements that none of the existing containers fulfilled (it would throw errors regarding lack of a Docker install). If this process could be simplified down and made more clear that would be fantastic!

**Environment (if applicable to the issue)**:
 - GitHub Actions

**Comment by northtyphoon** [comment]
@runewake2 you can use`docker/login` to login in to ACR.  The following is an example.

I created a registry `binduregistry` and service principal. I also grant the service principal `acrpush` role for the registry.

`Docker_REGISTRY_URL` is `binduregistry.azurecr.io`
`DOCKER_USERNAME` is `AZURE_SERVICE_APP_ID`
`DOCKER_PASSWORD` is `AZURE_SERVICE_PASSWORD`

```
workflow "New workflow" {
  on = "push"
  resolves = ["Docker Push"]
}

action "Docker Login" {
  uses = "actions/docker/login@8cdf801b322af5f369e00d85e9cf3a7122f49108"
  secrets = ["DOCKER_REGISTRY_URL", "DOCKER_USERNAME", "DOCKER_PASSWORD"]
}

action "Docker Build" {
  uses = "actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108"
  needs = ["Docker Login"]
  args = ["build", "-t", "binduregistry.azurecr.io/hello-world", "."]
}

action "Docker Push" {
  uses = "actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108"
  needs = ["Docker Build"]
  args = ["push", "binduregistry.azurecr.io/hello-world"]
}
```

**Comment by sajayantony** [comment]
@runewake2 - Were you unblocked? @northtyphoon can you also point your DOC/Sample PR here?

**Comment by SteveLasker** [comment]
If you wind up using the new github registry, you can also use az acr import. Https://aka.ms/acr/import

**Comment by runewake2** [comment]
Hi, I was able to get this working. The pipeline I'm using looks like this: https://github.com/WorldOfZero/dotcom/blob/master/.github/main.workflow

The problem is it's using the ACR commands so I'm getting a newly built image uploaded to ACR which is different than the one I am building to use locally. I tried the Docker Login/Push variety like is posted above. This fails for me when pushing with an auth error.

It seems like this could be solved with improved documentation around best practices for this solution but idk if anything around this exists yet. The use of `docker login` and `docker push` in place of `az acr login` and `az acr build` might be a place to start.

**Comment by sajayantony** [comment]
Might be good to see if you can get helm from GitHub Actions team. The Auth model using Service principal is a supported scenario since that’s used by multiple types of build systems.

**Comment by northtyphoon** [comment]
@runewake2:

>  I tried the Docker Login/Push variety like is posted above. This fails for me when pushing with an auth error.

We checked the server side log. It's because the service principal you are using only has image pull permission. Can you assign AcrPush role to the service principal?

https://docs.microsoft.com/bs-latn-ba/azure/container-registry/container-registry-roles

**Comment by runewake2** [comment]
Thanks, that makes sense. I'll give it another shot, if this is the case I'll try to set up a PR to update the docs for others.

**Comment by SteveLasker** [comment]
Thanks Sam,
One question is whether you really need to build with Actions and Tasks? 
There are benefits of each, but not sure you really wanted to both build. 
- Actions has a great integrated experience with github. 
- Tasks can track the base image updates, and automatically trigger new builds when the base images or source changes. 

If you build with Actions, you can use the [ACR Import](https://aka.ms/acr/import)  api. 
Here's an article I wrote a while back on [Choosing a Docker Container Registry](https://stevelasker.blog/2018/11/14/choosing-a-docker-container-registry/)

**Comment by SteveLasker** [comment]
@dlepow , what do you think about documenting github actions, pushing to ACR with Import? With a reference to using Tasks as well?

**Comment by sajayantony** [comment]
Why do we need import if the action can directly push to ACR. Import makes sense if they want to push to the GitHub registry and ACR. But this also means they need the AZ ClI image pulled each time.

—sajay
________________________________

**Comment by northtyphoon** [comment]
@runewake2 , I also added a doc and sample https://github.com/Azure/acr/blob/master/docs/integration/github-actions/github-actions.md
Let me know if you have any questions.

**Comment by clarkezone** [comment]
@northtyphoon how do you get the password for the service principal to use your example above?
