### ISSUE TITLE
Unable to deploy ACR ARM template with firewall enabled

### ISSUE THREAD

**Issue by gabrielvcunha** [Azure/acr#232]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug Report

**What happened?**:
ARM Template deploy fails when using firewall rules, defined by networkRuleSet property, as shown in [ACR ARM template reference](https://docs.microsoft.com/en-us/azure/templates/microsoft.containerregistry/2017-10-01/registries#NetworkRuleSet).
Error returns as below:
_The request content was invalid and could not be deserialized: 'Could not find member 'networkRuleSet' on object of type 'TemplateResource'. Path 'properties.template.resources[0].networkRuleSet'_

**What did you expect to happen?**:
The ARM template should be successfully deployed and a container registry should be created, with firewall enabled and a virtual network rule set up

**How do you reproduce it (as minimally and precisely as possible)?**:
Create an ACR ARM template and define a virtual network access rule using firewall, defined by networkRuleSet parameter. Use Test-AzureRmDeploymet or az deployment create, to test or create a azure deployment using the created template.

**Environment (if applicable to the issue)**:
 - Azure CLI/Powershell/ version: Azure CLI 2.0.65 / AzureRM 6.13.1
 - Datetime (UTC) when the issue occured: 02:28 UTC Wednesday, 29 May 2019

**Comment by sajayantony** [comment]
Could you please share the template that failed?

**Comment by gabrielvcunha** [comment]
Sure! Changed my parameters value.
[vidaregistry.parameters.zip](https://github.com/Azure/acr/files/3232188/vidaregistry.parameters.zip)

**Comment by gabrielvcunha** [comment]
Sure! Changed my template parameters.
[acr.zip](https://github.com/Azure/acr/files/3232443/acr.zip)

**Comment by msyihchen** [comment]
@gabrielvcunha Thanks for your sharing your ARM template. Can you put your networkRuleSet within properties? 
![image](https://user-images.githubusercontent.com/33437803/58575639-584f2d80-81f7-11e9-8ef8-2e10e1a96127.png)
//cc @sajayantony

**Comment by gabrielvcunha** [comment]
Thank you guys! My mistake...
