### ISSUE TITLE
nginx proxy container of custom domain frontend VM doesn't restart automatically

### ISSUE THREAD

**Issue by pihai** [Azure/acr#240]
**nginx proxy container of custom domain frontend VM doesn't restart automatically**

Hi

I followed [this article](https://github.com/Azure/acr/tree/master/docs/custom-domain) to deploy a registry with a custom domain. That worked for the first time, but after a reboot of the frontend VM it stopped working.

I think the problem is that the docker compose file (docs/custom-domain/docker-vm-deploy/docker-compose.yml.template) lacks some kind of restart policy. The container should start automatically after a reboot of the VM.

**To Reproduce**
1. Follow the instructions to create a registry with a custom domain
2. Verify that it works
3. Reboot the frontend VM
4. Try to `docker login` with the custom domain

**Expected behavior**
The container in the frontend VM automatically restarts after a VM reboot.

**Comment by msyihchen** [comment]
@pihai You need to run a startup script on machine reboot. Can you put docker-compose up commands in $startupscript and registry in crontab?
sudo crontab <<EOF
@reboot $startupscript &
EOF

**Comment by pihai** [comment]
Thanks for the answer. Sure, I could do that but in my opinion this should work by default.

I find a docker restart policy more appropriate and easier for that job.

**Comment by msyihchen** [comment]
@pihai Thanks for your feedback.
This stackoverflow thread may help. Let me know what you think.
https://stackoverflow.com/questions/43671482/how-to-run-docker-compose-up-d-at-system-start-up/46529084
![image](https://user-images.githubusercontent.com/33437803/59940222-fe651080-940e-11e9-9d9e-4db6b4abd347.png)

**Comment by pihai** [comment]
Thanks for the link. I was not aware that people seem to have problems with docker restart policies. So far I haven't faced any.

Maybe I'm a little bit too pedantic here but I'm not a huge fan of arbitrary sleeps. They introduce non-deterministic behavior and unnecessary latency.

**Comment by msyihchen** [comment]
I guess the sleep is just to make sure docker is up and running. We can probably add docker service status check instead of sleeping here.
