### ISSUE TITLE
helm dependency update unauthorized

### ISSUE THREAD

**Issue by AdamClarkRock** [Azure/acr#241]
**Describe the bug**
After az login and adding my acr helm repo I can run the follow commands with no error:
1) helm repo update
2) helm search mpdcontainerprod1/ingester
3) helm fetch mpdcontainerprod1/ingester (fetches with no error)

However when I try to run helm dependency update against a requirements.yaml I get an unauthorized error message:

```
Downloading ingester from repo https://mpdcontainerprod1.azurecr.io/helm/v1/repo
Save error occurred:  could not download https://mpdcontainerprod1.azurecr.io/helm/v1/repo/_blobs/ingester-1.0.1.tgz: Failed to fetch https://mpdcontainerprod1.azurecr.io/helm/v1/repo/_blobs/ingester-1.0.1.tgz : 401 Unauthorized
```
The same set of commands work when using a service principal, but not with my credentials despite being an owner on the acr registry.

**To Reproduce**
1. az login
2. az configure --defaults acr=mpdcontainerprod1
3. az acr helm repo add
4. helm repo update
5. helm dependency update where requirements.yaml is:
```
dependencies:
  - name: ingester
    version: 1.0.1
    repository: https://mpdcontainerprod1.azurecr.io/helm/v1/repo
```

**Expected behavior**
I expect the charts specified in the requirements.yaml to be downloaded

**Any relevant environment information**
 - OS: ubuntu
 - Azure CLI: 2.0.66 
 - Registry and image names

**Comment by shizhMSFT** [comment]
@AdamClarkRock It seems that you are using an old version of Helm (2.9.1).

It is a known Helm client issue https://github.com/helm/helm/issues/4299, https://github.com/helm/helm/issues/4445, and was fixed by https://github.com/helm/helm/pull/4662.

Please upgrade your helm client to the latest version or at least version 2.11.0.

**Comment by AdamClarkRock** [comment]
Hi @shizhMSFT - the upgrade has resolved this issue. Many thanks for your help.

Adam

**Comment by sajayantony** [comment]
@ni-reis would check-health have helped her ?

**Comment by ni-reis** [comment]
> @ni-reis would check-health have helped her ?

We are not indicating yet which are the recommended versions, but it would have outputted the version being used.

**Comment by sajayantony** [comment]
@shizhMSFT could you please open a check-health issue. We will triage it appropriately.

**Comment by shizhMSFT** [comment]
Linking #243
