### ISSUE TITLE
Parse helm version and compare with recommended version

### ISSUE THREAD

**Issue by ni-reis** [Azure/acr#243]
It's very common for users to face problems while using helm due to obsolete versions.
Considering that `az acr check-health` command is already outputting the helm version, an upgrade for it would be parsing the helm version and comparing with the current recommended version, printing a warning (or even throwing an error) if the context version is older than the current one.

Also, as errors can happen while parsing the version, it's a good idea to just do that if possible. When not possible it would be nice to print something like "recommended version: 2.11.0".

Thanks!

**Comment by sajayantony** [comment]
This is now merged into the CLI.
