### ISSUE TITLE
acr task create ignores --branch option

### ISSUE THREAD

**Issue by luigibk** [Azure/acr#245]
**Describe the bug**

The `--branch` option is ignored when `az acr task create` is used. The branch used is always master (default branch)

**To Reproduce**
1. Create a branch of repo with Dockerfile in new subdir of root dir
2. Use the new branch and Dockerfile path in `az acr task create`  
3.  Run `az acr task run` from cli and master branch is used. The build fails as it cannot find the new Dockerfile

**Expected behavior**
New branch should be used instead of master branch

**Screenshots**

**Any relevant environment information**
 - OS: macOS 10.14.5
 - Azure CLI/PowerShell/SDK version: 2.0.64
 - Docker version: 18.09.2
 - Datetime (UTC) when the issue occurred: 
 - Registry and image names

**Additional context**

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by northtyphoon** [comment]
@luigibk thanks for reporting the issue. We will investigate and reply back. Meanwhile, can you update the task context and add the branch info in the git url directly? 

eg, `az acr task update -c https://github.com/Azure/acr.git#<branch>`

**Comment by shahzzzam** [comment]
@luigibk Thanks for reporting this issue. The `--branch` option is meant to be used only for any source control triggers on the said branch. It can be different from the Context branch i.e. the branch you want to build. 

As @northtyphoon mentioned, we support building custom branches in the same way as docker:
https://docs.docker.com/engine/reference/commandline/build/#git-repositories

The document on our side maybe confusing and we will work on updating it to add more clarity on the `branch` option and begin deprecation of the flag to make it less confusing. Thank you again.

**Comment by luigibk** [comment]
Thanks @shahzzzam and @northtyphoon for clarifying this. I am currently using the docker syntax, but I feel the documentation for acr tasks is not clear enough on this, so updating the manual section about the `--branch` option would be helpful.

**Comment by SteveLasker** [comment]
oops

**Comment by dlepow** [comment]
@shahzzzam - One quick doc fix to consider is to update the CLI Help (and/or Swagger) description of `--branch` to something like: "The branch name **where the source control commit trigger is enabled.**" .

**Comment by jaysterp** [comment]
@dlepow After discussion with the team we have decided to deprecate the `--branch` parameter in the CLI and use whatever branch the user passes in with `--context` with parsing similar to [docker](https://docs.docker.com/engine/reference/commandline/build/#git-repositories). In the interim, I agree that the description should clarified in order to avoid confusion. //cc @sajayantony @northtyphoon

**Comment by northtyphoon** [comment]
In the latest CLI 2.3.1, we have deprecated branch parameters, instead, users need to follow the context pattern (https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-overview#context-locations) to pass the branch information, eg, 

az acr task create -c https://github.com/Azure-Samples/acr-build-helloworld-node.git#master ....

/cc: @rosanch
