### ISSUE TITLE
Error 500 while pulling image from virtual-kubelet

### ISSUE THREAD

**Issue by kalioz** [Azure/acr#250]
**Describe the bug**
We are using kubernetes on AKS and recently added a [virtual node](https://docs.microsoft.com/fr-fr/azure/aks/virtual-nodes-portal). As the page indicates, we are not using a service principal to pull images from our ACR but we are using a [secret](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-by-providing-credentials-on-the-command-line). When pulling images from the ACR, we occasionaly encounter this error : 
(extract from `kubectl describe pod XXX`):
~~~~
Status:              Pending
Reason:             ProviderFailed

Message:            api call to https://management.azure.com/subscriptions/<ID_SUBSCRIPTION>/resourceGroups/MC_<RESOURCE_GROUP>_westeurope/providers/Microsoft.ContainerInstance/containerGroups/<CONTAINER_GROUP>?api-version=2018-10-01: got HTTP response status code 500 error code "InternalServerError": Encountered an internal server error. The tracking activity id is 'bc93a490-b41b-4704-b57f-344fff095320', correlation id is 'ed730261-8cf7-41fd-b46a-64f4f6fc818b'.
~~~~

This error does not appear when pulling other images, and is not dependant on one image (a deployment of 20 pods (so the same image) can have 2 to 10 pods affected by this error)

**To Reproduce**
1. add a virtual node to an existing AKS cluster
2. schedule some (5-10) pods using images from a private ACR with the credentials stored in a secret
3. Some pods will fail independently of their image

**Expected behavior**
The server should not return a 500 error while pulling an image

**Screenshots**

**Any relevant environment information**
 - OS: Linux (aks)
 - (virtual) kubelet version : v1.13.1-vk-v0.9.0-1-g7b92d1ee-dev
 - Datetime (UTC) when the issue occurred : 2019-07-08 -> 2019-07-09
 - Registry and image names : acrvalodev.azurecr.io/valo-front:0.6.4_dev

**Additional context**

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by northtyphoon** [comment]
The failed API is from Azure Container Instance.

https://management.azure.com/subscriptions/<ID_SUBSCRIPTION>/resourceGroups/MC_<RESOURCE_GROUP>_westeurope/providers/Microsoft.ContainerInstance/containerGroups/<CONTAINER_GROUP>?api-version=2018-10-01: got HTTP response status code 500 error code "InternalServerError": Encountered an internal server error. The tracking activity id is 'bc93a490-b41b-4704-b57f-344fff095320', correlation id is 'ed730261-8cf7-41fd-b46a-64f4f6fc818b'

**Comment by kalioz** [comment]
My bad, I saw provider failed and thought it was the ACR.
