### ISSUE TITLE
Pulling images from ACR very slow inside datacenter

### ISSUE THREAD

**Issue by tjcrone** [Azure/acr#252]
My kubernetes nodes use a pre-puller to pull an image for user pods and this pre-puller runs every time the VMSS node pool autoscales up with a new node. It takes new nodes approximately 15 minutes to pull a 2 GB image from within East US. The cluster, all instances, and the registry are all in East US. 15 minutes seems excessively long for an image pull inside the datacenter. Is this normal? Will I see an improvement if I have the container log in with a service principal? How can I troubleshoot this? Thanks!

**Comment by sajayantony** [comment]
What is your VM configuration? Pull latencies increase when you have a slower disk or low CPU count.

**Comment by tjcrone** [comment]
I am using premium SSDs with Standard_D2s_v3 instances, but we have a very burstable application so I am trying to scale the cluster down to 1 VM at times, and then up to perhaps up to 30-40 VMs. And each VM needs to pull this image (only once) when it is created. So the cluster might start off very small. I will try making the minimum node count 3 VMs, and see if this changes things. But it would be great if there was a way to make these pulls faster even when the cluster is small. ~2 MB/s inside the same datacenter is not what I was expecting.

**Comment by tjcrone** [comment]
I should also not that I am only trying to scale up one node when I get these speeds, not 30 nodes at once.

**Comment by tjcrone** [comment]
After scaling the cluster up to 3 VMs, I see no significant improvement. Should I be expecting ~2-3 MB/s on image pulls between my Kubernetes VMSS nodepool and my private ACR within the same datacenter? I have a feeling like I must be doing something wrong. Any thoughts or help on troubleshooting this would be greatly appreciated!

**Comment by sajayantony** [comment]
Can you enable and share your the timing information from your docker logs. We can see how long the pull/vs extraction etc takes.

**Comment by tjcrone** [comment]
Happy to! Can you provide information on how to do this? I am working with [Pangeo](http://pangeo.io/)/Z2JH and I do not normally log in to the containers that manage these pulls, and it might be difficult to modify them, but I can try. What steps should I try? Also just to check, do you get 2-3 MB/s for ACR pulls inside a datacenter? If this is normal, not sure there is any reason to troubleshoot much further. Thanks for your help!

@daxsoule, @agentmorris

**Comment by sajayantony** [comment]
Here are the steps - https://docs.microsoft.com/en-us/azure/container-registry/container-registry-faq#enable-and-get-the-debug-logs-of-the-docker-daemon

**Comment by sajayantony** [comment]
@tjcrone - Did you get a chance to validate with https://azure.microsoft.com/en-us/updates/azure-ephemeral-os-disk-now-generally-available/ 
Feel free to reopen the issue with more details if are still seeing any degraded performance.
