### ISSUE TITLE
`az acr check-health` command fails with unexpected error

### ISSUE THREAD

**Issue by ni-reis** [Azure/acr#256]
It's common for python requests library to fail with an error similar to
`HTTPSConnectionPool(host='myregistry.azurecr.io', port=443): Max retries exceeded with url: /v2/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))`.
This can happen for example if the user is behind a proxy.

This causes the `az acr check-health` command to fail with an unexpected error, displaying all the traceback to the user.

The current behavior is that the command fails to run in this scenario. The expected behavior would be having this scenario covered in the command, being diagnosed, caught, and having a reference in the documentation.

**Comment by sajayantony** [comment]
@ni-reis  should we close this issue?

**Comment by hkuadithya** [comment]
@sajayantony yes, I forgot to close this issue. The PR related to this issue has been merged into Dev.
