### ISSUE TITLE
Cannot push the image to ACR with role "AcrPush" assigned

### ISSUE THREAD

**Issue by houliang428** [Azure/acr#258]
**Describe the bug**
I created a service principal and login with this service principal. Before push image to the Acr, I have successfully assigned a role "AcrPush" to the service principal in the Access control of the Acr. I also tagged the image, but I still cannot push the image to the Acr.

**To Reproduce**
1. I logout all the subscription and all the account.
2. I did not use Acr login, because I am considering a scenario that someone else wants to push an image to my Acr.
3. I used "az login --service-principal --username --password --tenant_id" to login.
4. I assigned a "AcrPush" role to the service principal.   
5. After tagging the image as   "myregistries.azurecr.io/path/nginx", I use docker push to push the image.
**Expected behavior**
I think I should be able to push the image to the ACR

**Screenshots**
Bug Information 
"
The push refers to repository [liangregistries.azurecr.io/houliang/nginx]
fe6a7a3b3f27: Preparing                                                                                                   
d0673244f7d4: Preparing                                                                                                   d8a33133e477: Preparing                                                                                             
unauthorized: authentication required
"

**Any relevant environment information**
 - OS: Windows
 - azure-cli                         2.0.68 *

command-modules-nspkg               2.0.2 *
core                              2.0.68 *
nspkg                              3.0.4
telemetry                          1.0.3

 - Docker version 19.03.1, build 74b1e89

**Comment by djyou** [comment]
@houliang428 You'll have to run `az acr login` to populate the credentials to allow `docker` operations. You may try either of the following:

```
az login --service-principal --username --password --tenant_id
az acr login -n MyRegistry
```
or
```
az acr login -n MyRegistry -u <service principal app id> -p <service principal password>
```

**Comment by djyou** [comment]
Closing this issue, please reactivate if you still have trouble pushing after running `az acr login`.
