### ISSUE TITLE
User Interface via browser

### ISSUE THREAD

**Issue by slawekww** [Azure/acr#260]
**What is the problem you're trying to solve**
Many ACR users do not want or cannot access portal to see repositories/images/manifests.
It is required https service which would serve content of ACR as web pages to browse thru docker images and see manifests content as typical docker registry browsers.
Found problem: https://github.com/Azure/acr-web-manager
but it sounds not updated since 3 years.
Please advise recommended way to access ACR using browser and not using portal.

**Describe the solution you'd like**
Simple helm chart or docker run command to start https service which connects with ACR in backgrouds and serve content of ACR in term of image list/repositories/manifests, not blob layouts. Fast and scalable.

**Comment by SteveLasker** [comment]
Hi Slawek,
Thanks for reaching out. While we haven't updated this project in a while, we've been working on standardizing the interactions. The challenge with the current implementations is every registry (acr, ecr, gcr, quay, docker hub, harbor) must implement custom APIs for general information. The OCI distribution project hadn't solidified a standard for things like repository, tag, searching apis.
We have started such a project here: [Cloud Native Artifact Search Requirements](https://hackmd.io/mF80aTt8TC-GiGHOyPG-dw)
Currently, we're working to standardize [artifacts in a registry](https://stevelasker.blog/2019/01/25/cloud-native-artifact-stores-evolve-from-container-registries/)

The approach we've been taking is to creating a set of standard APIs for the [OCI Distribution](https://github.com/opencontainers/distribution-spec/) project. With standard APIs, the community could develop tooling that would work across all registries, both public vendor hosted, and privately hosted registries. And, it would work across all artifact types, including Container Images, Helm Charts, Singularity, OPA and others. 

These public efforts take time, which is where we've been currently focusing our efforts. 
If you'd like to help revive this browser project, we'd be happy to support you and others until we have some generalized browser UI. 

Steve

**Comment by sajayantony** [comment]
This is being fixed - https://github.com/Azure/acr-web-manager/pull/10

**Comment by tomkerkhove** [comment]
@SteveLasker 	Any plans on providing this as part of ACR itself?

**Comment by SteveLasker** [comment]
We'd likely take an iterative approach. We'll first make sure the code could be hosted in App Service Linux or a customers AKS cluster. It would have auth back to ACR for the user.
If we have that working, and good customer usage, we could consider hosting it directly. Honestly, we haven't had many requests, but are happy to see it up-voted on https://aka.ms/acr/uservoice

**Comment by msyihchen** [comment]
@tomkerkhove Is this issue closable?

**Comment by tomkerkhove** [comment]
I'd keep this open for now

**Comment by SteveLasker** [comment]
Hey @tomkerkhove, 
As this is a feature request, not a bug, can you please move this to https://aka.ms/acr/uservoice?
We track issues, as they apply to supported scenarios here. Keeping this open indicates there's a bug in the product we're not actively fixing.

**Comment by tomkerkhove** [comment]
Looks like it's already there - https://feedback.azure.com/forums/903958-azure-container-registry/suggestions/38315953-acr-user-interface

Ok to close for me, but I didn't open it 😁

**Comment by slawekww** [comment]
Hi @tomkerkhove 
yes, I've opened it at uservoice. Please close this github feature request.
Unfortunatelly I have no work forces to work on ACR improvements even if my organization uses intensively ACR, AZDO and AKS.
