### ISSUE TITLE
Acr build hangs

### ISSUE THREAD

**Issue by TBurda** [Azure/acr#263]
**Describe the bug**
Build container accidentally hangs on one of the steps in dockerfile. I executed a commad `az acr build --registry logeto --image web:7.6.35.1340_1809 --platform windows --build-arg WINDOWS_VERSION=1809 --build-arg VERSION=7.6.35.1340 C:\ContainersBuild\Web --debug`

This happens randomly when I run the build ACR command above. Can you help me? A few months ago everything was fine.

**Debug logs:**
![image](https://user-images.githubusercontent.com/21170562/63257209-8cc40a00-c279-11e9-9035-3efe2c6071c7.png)

**Any relevant environment information**
 - OS: Windows Server 2019 Standard
 - Azure CLI: 2.0.69
 - Docker version: 18.09.4
 - Datetime (UTC) when the issue occurred: 8/17/2019, 11:17 PM GMT+2
 - Registry and image names: logeto.azurecr.io/web:7.6.35.1340_1809

**Comment by northtyphoon** [comment]
@TBurda can you run `az acr task logs -r logeto --run-id cbh8` to get the final build log? It looks one build step timed out. Is it possible to share the project with us to repro it? You can send it to acrsup@microsoft.com.

**Comment by TBurda** [comment]
Yes, I can. I sent email with the files.

**Comment by shahzzzam** [comment]
Hi @TBurda is it possible for you to send the project zip file?
We want to be able to reproduce this and collect some system level logs to see what's going on.

Also - I see that the base image you use here is logeto.azurecr.io/iis:1809.

Do you also happen to have the Dockerfile for that image?

Thanks

**Comment by northtyphoon** [comment]
@TBurda the issue is still under investigation with windows platform team. Unfortunately, I don't have ETA at current moment. If it's intermittent, You may need to retry to workaround it.

**Comment by TBurda** [comment]
Hi @northtyphoon, thank you for answer. This problem occurs every day and blocks our CI / CD. To successfully build a container, I have to run build manually several times.

Could you advise me on, how temporarily workaround this problem?

**Comment by northtyphoon** [comment]
Can you see what build step often failed? For example, if you have the following Dockerfile and the `command2` step often failed, if the steps above `command2` are "static", can you pre-create a base image that ends at 'command2' that other builds can be based on?

```
FROM mcr.microsoft.com/windows/servercore:ltsc2019
RUN powershell -Command 'command1'
RUN powershell -Command 'command2'
COPY ...
...
```

**Comment by xenon425** [comment]
I am encountering the same issue

**Comment by cyril-berber** [comment]
Idem for me. When building an image from mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019 and trying to install VS Build Tools and other tools, the acr build task always hangs, each time at a different step.
Could it be linked to the agent memory?

**Comment by toddysm** [comment]
@xenon425 and @cyril-berber We are trying to collect more details to be able to troubleshoot the issue. The randomness of it makes it hard to reproduce but we are trying our best. Would you mind sharing your build scripts, the details about your ACR Tasks configuration, and the output you see?

**Comment by northtyphoon** [comment]
Windows team has released the fix at 2/9/2021 and updated all supported images listed in https://hub.docker.com/_/microsoft-windows-servercore. If you build against these image directly, you should see the improvement. If you build from your own base image, please make sure you rebuild your base image using the latest windows images.
