### ISSUE TITLE
Build fails when using az acr build --target option with image nginx:stable

### ISSUE THREAD

**Issue by abilous-ti** [Azure/acr#270]
**Describe the bug**
Building with a docker file using image nginx:stable fails the build.

Successfully built 4a72365b55cf
2019/09/04 11:45:56 Successfully executed container: build
2019/09/04 11:45:56 Step ID: build marked as successful (elapsed time in seconds: 30.798192)
2019/09/04 11:45:56 Populating digests for step ID: build...
failed to query digests, msg: Error: No such object: nginx:stable

: exit status 1

Run ID: cr2x9 failed after 38s. Error: failed during run, err: exit status 1
Run failed

**To Reproduce**
1. Dockerfile
FROM node:lts AS build
RUN ls
FROM nginx:stable AS final
RUN ls
2. az acr build -r --no-push --target build .

**Expected behavior**
Successfully built 1f92390d5cd5
Successfully executed container: build
Step ID: build marked as successful
Populating digests for step ID: build...
Successfully populated digests for step ID: build

The following dependencies were found:

    runtime-dependency:
    registry: registry.hub.docker.com
    repository: library/nginx
    tag: stable
    digest: sha256:3c98df50eb7e634d9083e3fb96071eaa32f8dc794275f3e490a96529dc42d1eb
    buildtime-dependency:
        registry: registry.hub.docker.com
        repository: library/node
        tag: lts
        digest: sha256:8eab6272219cb2eef3106a2b2c72ba85627008ebe5f1471dabc76c10e688ad59 git: {}

**Any relevant environment information**
    OS: Windows
    Version 10
    AZ CLI 2.0.72

**Comment by abilous-ti** [comment]
@northtyphoon Are there any updates on this bug, when the fix will be released?

**Comment by northtyphoon** [comment]
@abilous-ti can you try it again? We rollout a fix.

**Comment by abilous-ti** [comment]
@northtyphoon I confirm. Bug is fixed
