### ISSUE TITLE
Preview Purge - unknown flag: --filter

### ISSUE THREAD

**Issue by mkstephenson** [Azure/acr#271]
**Describe the bug**
When attempting to execute the purge command (on demand), it throws an error saying that the required --filter flag is unknown.

**To Reproduce**
1. Open Azure CLI
2. Run az acr run --cmd "mcr.microsoft.com/acr/acr-cli:0.1 --registry {{.Run.Registry}} --filter 'projectname/.*' --ago 7d --dry-run" --registry <myregistry> /dev/null

**Expected behavior**
The purge command should complete successfully

**Any relevant environment information**
 - Azure Cloud Shell

**Comment by nadworny** [comment]
Totally agree

**Comment by Bhaskar1312** [comment]
I am using the following  command/script in a pipeline
`
az acr run \
          -r myregistry \
          --timeout 7200 \
          --cmd "acr purge --dry-run --filter myorg/mycontainer:^((?!release).)*$ --ago 180d --untagged" \
           /dev/null
`
I initially used `^(?:(?!release).)*$` and tried by putting quotes around it to delete images with tags that dont contain `release`. The regex is fine but when ran it gives `Error: unable to correctly parse filter flag`
