### ISSUE TITLE
401 unauthorized when trying to push signed container to ACR

### ISSUE THREAD

**Issue by bdelsaz** [Azure/acr#278]
I am trying to push signed images to an Azure Container Registry. I get the error:
```'failed to sign : you are not authorized to perform this operation: server returned 401```.
This even though I have created all the RBAC roles in Azure AD and I am logged in with the right credentials (AcrImagePush and - AcrImageSigner ).
I am following the instructions in this [Microsoft docs page](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-content-trust)

**Steps to reproduce the behavior**:
1. Tagged my container with the full qualified name <ACR_NAME>/<CONTAINER_NAME>:<TAG>
2. I logged in to Azure using ```az login``` 
3. I logged in into my container registry with ```ac acr login --resource-group <MY_RESOURCE_GROUP> --name <ACR_NAME>```
4. Enabled 'Content trust' in my ACR (now it is a premium ACR)
5. I refreshed my credentials in case the new roles had not been applied in my local CLI.
6.  I try to sign and push an image to ACR using: 
```These are the commands I use to push a signed image to ACR from my windows machine: set DOCKER_CONTENT_TRUST=1```
```docker push <ACR_SERVER>/<IMAGE_NAME>:<TAG>```
7. I write the correct passphrases. 

**These are the resulting logs**
```
The push refers to repository [MY_ACR_NAME.azurecr.io/appname]
4a85926cec01: Layer already exists
349c7f00d08e: Layer already exists
370f72f4d447: Layer already exists
8dc6654a61c6: Layer already exists
8fa655db5360: Layer already exists
latest: digest: sha256:<A_VERY_LONG_SHA> size: 1375
Signing and pushing trust metadata
Enter passphrase for root key with ID 0c6a1f8:
Enter passphrase for new repository key with ID 96c45d3:
Repeat passphrase for new repository key with ID 96c45d3:
Finished initializing "MY_ACR_NAME.azurecr.io/appname"
failed to sign MY_ACR_NAME.azurecr.io/appname: you are not authorized to perform this operation: server returned 401.
```
Below the permissions on my Azure dashboard:
![image](https://user-images.githubusercontent.com/46991222/65992669-f138d280-e48f-11e9-98f2-a6e16c673361.png)

**Expected behavior**
I expect the signed container to be pushed to ACR in a 'signed' state

**Environment information**
 - OS: Windows 10.0.17763
 - Azure CLI version: 2.0.74
 - Docker version: 19.03.0-rc2
 - Using docker linux containers
 - Datetime (UTC) when the issue occurred: September 25th 2019

**Additional context**
I tried enabling enabling admin account on my ACR and using docker login with the admin account credentials. The result was the same.

**Comment by martinpf** [comment]
This is what happens when the AcrPush role assignment is there for the credential the docker client has cached for that registry but  AcrImageSigner is not.  Is there any chance the current credential the docker client is using  for the registry is missing that role assignment?

**Comment by martinpf** [comment]
You could verify there are no docker client issues by doing a docker login using a service principal that has both AcrPush and AcrImageSigner roles assigned to the registry.

**Comment by bdelsaz** [comment]
@martinpf thanks so much for your response. I also suspect it has something to do with the docker client, something in the lines of AZ CLI is not passing the docker client the credentials.

When I do ```docker login``` with the admin account (after admin account is activated) of my ACR, I am able to login. But I cannot push containers, the access to the repository/resource is denied. 

When I do ```docker login``` using my user credentials (username and password), which are the ones linked to the roles acrSignImage, acrPush etc.,  I get the response 'Error response from daemon: Get https://beatrizdelsaz.azurecr.io/v2/: unauthorized: authentication required'

My docker config looks like this:
```
{
	"auths": {
		"MY_ACR_NAME.azurecr.io": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/19.03.0-rc2 (windows)"
	},
	"credsStore": "desktop",
	"stackOrchestrator": "swarm"
}
```
I am sure I am missing something here, still reading the docs

**Comment by bdelsaz** [comment]
So, I think I can boil down my problem to this.
```az acr login``` (which is just a wrapper of  ```docker login```) can successfully log in if I use the 'admin account' username and password.

However, if I try to log in with my AD username (my email), both az acr and docker client will refuse to log me in. 

```
az acr login -n ACR_NAME -u MY_EMAIL@EMAIL.com
Password:
Error response from daemon: Get https://ACR_NAME.azurecr.io/v2/: unauthorized: authentication required
```
So when I do docker push and try touse my acrImageSign credentials, these are not there. since according to [the docs](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-content-trust#grant-image-signing-permissions) 'You can't grant trusted image push permission to the admin account of an Azure container registry.
Does this make more sense?

**Comment by martinpf** [comment]
Instead of
  az acr login -n ACR_NAME -u MY_EMAIL@EMAIL.com
does a sequence of commands like the following work?  (log into your Azure AAD account using az login)
   az login   
   az acr login  -n <registryName> 
   docker push <registryName>.azurecr.io/yourRepo:yourTag

**Comment by shizhMSFT** [comment]
Could you try to create a service principle and assgin `AcrPush` and `AcrImageSigner` roles to that service principle? Then login using the service principle?

**Comment by bdelsaz** [comment]
@martinpf it works, for unsigned images only. If I do ```set DOCKER_CONTENT_TRUST=1``` before pushing it will not sign the image. 

Will try creating a service principal as @shizhMSFT suggests and will post here the results

**Comment by bdelsaz** [comment]
@shizhMSFT this works if I sign in as a user principal, thank you.

Setting credentials and loggin in as a user principal, both from CLI and Azure portal, _does not work_ then (unless I'm missing something).

**Comment by martinpf** [comment]
to sign in as an AAD user you must use az login and then az acr login.  az acr login will apply the token that az login obtains to docker.  az acr login doesn't support the AAD login protocal (2 factor auth, etc...) for AAD user accounts

**Comment by bdelsaz** [comment]
> to sign in as an AAD user you must use az login and then az acr login. az acr login will apply the token that az login obtains to docker. az acr login doesn't support the AAD login protocal (2 factor auth, etc...) for AAD user accounts

Yes, I do this (see my [second post](https://github.com/Azure/acr/issues/278#issuecomment-538646878)). I am unable to login with my AAD credentials even after I login with ```az login``` to be sure.

az login response:
```
....
"user": {
   "name": "<MY_EMAIL>",
   "type": "user"
}.
..
```
Then az acr login (Password shows empty, but I type it)
```
az acr login --resource-group <RG_NAME> --name <ACR_NAME> --username <MY_EMAIL>
Argument 'resource_group_name' has been deprecated and will be removed in a future release.
Password:
Error response from daemon: Get https://<ACR_NAME>.azurecr.io/v2/: unauthorized: authentication required
```

**Comment by bdelsaz** [comment]
I think this might be an azure cli problem.
I've seen [this issue](https://github.com/Azure/azure-cli/issues/5961), [this issue ](https://github.com/Azure/azure-cli/issues/4843)and [this issue](https://github.com/Azure/azure-cli/issues/4715), regarding login failing on non-standard consoles and passing password input to docker client. None of the workarounds worked stated in these issues worked for me and I'm using latest version of azure CLI.

I think I will close this issue for now and open one/keep reserching on the azure-cli repo. Thanks @martinpf and @shizhMSFT !

**Comment by shizhMSFT** [comment]
The root cause is that the permission list is not recognizable by ACR if the current login user has a classic subscription administrator role, such as `Service Administrator` and `Co-Administrator`.

We are sorry that those classic admins roles are currently not supported by ACR, and we plan to resolve this issue.

**Comment by geet-h17** [comment]
@shizhMSFT i am still getting this issue tried "Owner" "Contributor" , AcrPush and AcrImageSigner roles assigned to ACR still nothing worked , getting "you are not authorized to perform this operation: server returned 401." after entering passphase...

**Comment by shizhMSFT** [comment]
@geet-h17 Please create a support ticket in Azure to investigate the actual cause behind the 401. Our customer support will help you resolve your issue.

**Comment by shizhMSFT** [comment]
Just in case. It is worth noting that, after you assign new roles, it is suggested refreshing the local credentials by running `az acr login`.
