### ISSUE TITLE
agressive on reserved names

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr#280]
**Describe the bug**
We seem to be a bit too aggressive on reserved words/names
**To Reproduce**
```sh
az acr task create \
    --cmd "mcr.microsoft.com/azure-cli az login --identity" \
    --name az-login \
    --registry contosobaseimages \
    --context /dev/null \
    --assign-identity
```
generates an error:
`The resource name 'contosobaseimages/az-login' or a part of the name is a trademarked or reserved word.`

Not sure why we concatenate `contosobaseimages/az-login`, but really confused why we block on a name of `az-login`

**Expected behavior**
Names that aren't copyright, on the vulgar terms list should be allowed.

**Comment by northtyphoon** [comment]
I guess the error is from ARM not us. We do allow `-` for the task name.

@jaysterp @huanwu can you confirm it?

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/stable/2019-04-01/containerregistry_build.json#L2540

**Comment by huanwu** [comment]
Yeah, it is not related to us. I can repro it on prod but cannot repro on dogfood. It seems the prod arm has more restrictions.

**Comment by SteveLasker** [comment]
Who do we follow-up with regarding name validation from ARM?

**Comment by northtyphoon** [comment]
@SteveLasker  all Azure resource creations is pre-validated by ARM. 

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-reserved-resource-name

The following words cannot be used as either a whole word or a substring in the name:

LOGIN
MICROSOFT
WINDOWS
XBOX

**Comment by SteveLasker** [comment]
Lets please queue up a link to this doc for name validation. It wasn't clear to me what word, or why.

**Comment by northtyphoon** [comment]
@SteveLasker the request was directly rejected by ARM, it didn't even reach our service. I closed the issue because it's out of our control and we don't get a chance to handle it and unable to do anything for this case.

I suggest your feature request on https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-reserved-resource-name? Does it make sense?

**Comment by sajayantony** [comment]
Can revisit if we are doing something ACR specific.
