### ISSUE TITLE
az acr import to generate output on success

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr#282]
**Describe the bug**
When running az acr import, there's no output for the success or failure of execution.
For context, `acr import` may be run in a larger batch script (or acr tasks). Looking at the logs, there's no info the command ran, or was successful

**To Reproduce**
1. `az acr import --name contosobaseimages --source docker.io/library/node:9-alpine -t staging/node:9-alpine --force -o jsonc`

On successful import, no output is generated.
If an error occurs, we do get output
`Deployment failed. Correlation ID: 30aa9a16-8eb9-4b1c-afe0-3a51b4f7b409. Operation registries-9c3cbdb0-ea24-11e9-ab76-0a580af44e17 failed. Resource /subscriptions/[subID]/resourceGroups/demo42/providers/Microsoft.ContainerRegistry/registries/contosobaseimages Invalid message NotFound Not Found {"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Tag":"9-alpine-error"}}]}`

**Expected behavior**
Output confirming import worked.

|source|registry|target|size|
|:-|:-|:-|:-|
|docker.io/library/node:9-alpine|contosobaseimages|staging/node:9-alpine|68.5MB|

**Comment by yugangw-msft** [comment]
This is really by-design, as CLI picks up: http://www.linfo.org/rule_of_silence.html

**Comment by SteveLasker** [comment]
While I appreciate the "silence game", I also like hearing a confirmation to know a request was confirmed. All our other CLIs provide some positive output. Even update APIs that implement idempotent behaviors for updating something that didn't change return a value confirming it's state.

**Comment by yugangw-msft** [comment]
Actually lots of command don't output anything, e.g. all those `delete` commands. The guideline is that commands output the data returned from the API, so it can be scripted. For success or failure, it is the exit code to be used. I hope ACR commands can be consistent with the rest of world. If we really want to output something, maybe do an image get at the end and output that?

**Comment by Wwwsylvia** [comment]
@SteveLasker Are we good to close this?
