### ISSUE TITLE
Add Run.RegistryName to Task.yaml Run Variables

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr#285]
**What is the problem you're trying to solve**
Some commands require just the registryname (eg: `demo42`) instead of the fully qualified name `demo42.azurecr.io`. Without this `Run.` variable name, we have to resort to either parsing the `Run.Registry`, or passing it in as a `.Values.` value.

**Describe the solution you'd like**
Task Run Variables to support `.Run.RegistryName` which would take `demo42` from the `.Run.Registry` value.

In the below example, `az acr import` requires the registry name. In this case, I'm passing it in as a `--set REGISTRY_CENTRAL=contosobaseimages`, complicating the experience.
While we could add additional help text for how to do [go parsing](https://blog.gopheracademy.com/advent-2017/using-go-templates/), we should make the simple things simple. 

```yaml
version: v1.0.0
steps:
# Build target image
- build: -t {{.Run.Registry}}/staging/node:9-alpine -f import-node-dockerfile .
# Login
- cmd: "mcr.microsoft.com/azure-cli az login --identity"
# Push Import Image
- cmd: "mcr.microsoft.com/azure-cli az acr import --name {{.Values.REGISTRY_CENTRAL}} --source {{.Run.Registry}}/public/node:9-alpine -t staging/node:9-alpine --force"
``

**Comment by northtyphoon** [comment]
Tasks has supported {{.Run.RegistryName}}. Try

`az acr run --cmd "bash echo {{.Run.RegistryName}}" -r demo42 /dev/null`

**Comment by SteveLasker** [comment]
Ok, so it's a doc issue, as there's no reference to it in [ACR Tasks reference: YAML](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-reference-yaml)
@dlepow, can we queue this up for an update?

**Comment by dlepow** [comment]
Yep, this can be addressed as a side point in pending PR https://github.com/MicrosoftDocs/azure-docs-pr/pull/89309 for YAML version update.

**Comment by SteveLasker** [comment]
Closing as RegistryName added to the above pr.
