### ISSUE TITLE
Add log event when image tag is removed

### ISSUE THREAD

**Issue by jpreese** [Azure/acr#286]
**What is the problem you're trying to solve**
This morning a couple of our build pipelines stopped working because the image tags used for the containerized jobs could not be found. No one in the organization appears to have manually deleted it, and the logs don't show any information.

**Describe the solution you'd like**
More events around actions that occur in the Azure Container Registry, specifically, in this case, around the removal of an image tag.

**Additional context**
If I am missing something, please let me know. The primary goal is to figure out how an image and its tag was pushed, confirmed to be pushed and working, stopped working today without a trace. Thanks!

**Comment by jpreese** [comment]
For completeness, @SteveLasker has mentioned there is going to be a diagnostic and logs feature which may cover this. https://twitter.com/SteveLasker/status/1182298896355082245?s=20

**Comment by cegraybl** [comment]
Changes have been deployed to all public regions.
The documentation on how to configure is in the following link (it mentions only Pull and Push events, but we currently also support deletion and untag events)
https://azure.microsoft.com/en-us/blog/azure-container-registry-preview-of-diagnostics-and-audit-logs/
