### ISSUE TITLE
az acr import with port number fails in validation

### ISSUE THREAD

**Issue by jakaruna-MSFT** [Azure/acr#287]
## Describe the bug
I am opening this issue as part this [MSDN thread ](https://social.msdn.microsoft.com/Forums/en-US/b0d50ace-e740-401b-a5da-c6a1b1219239/how-can-i-use-port-in-registryuri-when-i-import-container-images-from-a-nonazure-private-container?forum=AzureContainerServices) opened by panyoung.kim

**Command Name**
`az acr import`

**Errors:**
```
Invalid value docker.io:443 for property parameters.Source.RegistryUri for resource name jakaruna. Kindly refer to docs for expected value: https://docs.microsoft.com/en-us/rest/api/containerregistry/registries/importimage
```

## To Reproduce:

have a port num as part of the source URI

like my-private-repo:5000
- `az acr import -n {} --source {} -t {} --debug`

## Expected Behavior
imports that image.  Docker pull works well with port
Example:   docker pull my-provare-repo:5000/helloworld

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.71 *

Extensions:
aks-preview 0.4.10
dev-spaces 1.0.3
dev-spaces-preview 0.1.6
resource-graph 0.1.11

**Comment by adewaleo** [comment]
I transferred the issue here as it is not a CLI issue and it is being worked on on the service Resource Provider side.

**Comment by adewaleo** [comment]
So although our validation now allows port numbers, it turns out that our import implementation does not handle ports properly....

```
PS C:\Users\oladewal\source\azure-cli\azure-cli> az acr import -n tosinreg2 --source ovatestregistry.azurecr.io:443/hello-world:v1 --force
Deployment failed. Correlation ID: 9e2482f3-5095-400f-ab58-408c9366e912. Operation registries-00000 failed. Resource /subscriptions/00000/resourceGroups/ova-test/providers/Microsoft.ContainerRegistry/registries/tosinreg2...
... Invalid message Unauthorized Unauthorized
```

This is because for a push to work to a specific port, the client / requester must be authenticated to that port.

case in point 

```
docker pull ovatestregistry.azurecr.io:443/hello-world:v1
```
works only after authenticating to "ovatestregistry.azurecr.io:**443**"

**Comment by adewaleo** [comment]
More work will have to be done in the service to handle these scenarios properly, beyond just improving validation (which was previously done)

**Comment by jakaruna-MSFT** [comment]
@adewaleo Can you go through this [MSDN thread](https://social.msdn.microsoft.com/Forums/en-US/8eda3544-53ed-43fa-ac53-87e721fa09c3/accessing-private-docker-registry-on-nonstandard-port-with-aci?forum=AzureContainerServices) and provide your inputs?

In that thread, customer is trying to pull the image from the private registry with port number 5000 and the image pull fails.

command used is 
`
az container create\
        --name testcontainer\
        --resource-group test-rg
        --image private.example.com:5000/dockerimage:build94\
        --ports 80\
        --ip-address Private\
        --registry-login-server private.example.com\
        --registry-username reguser\
        --registry-password ***
`

error is 
`The image 'private.example.com:5000/dms-api:build94' in container group 'testcontainer' is not accessible. Please check the image and registry credential.
`

**Comment by jakaruna-MSFT** [comment]
@adewaleo If we run the private registry in 443, what will happen

**Comment by adewaleo** [comment]
> @adewaleo If we run the private registry in 443, what will happen

I think az acr import should work fine with 443 if the port isn't explicitly mentioned, however this should be fixed as part of this issue (being able to import with explicit port)

@jakaruna-MSFT Unless I understand you, we don't own azure container instances (ACI) or the container create service / command. Please reach out to them.  

However, I think as you mentioned or hinted, the user should be able to import a registry to ACR and then run container create using the imported image in acr. 

I will be working on making ACR import work with port numbers, but ACI / az container create is outside our team's scope.

Is there a reason they want to run the private registry on 5000? Or are they simply reporting this issue?

**Comment by kawaja** [comment]
I'm the reporter in the [MSDN Thread](https://social.msdn.microsoft.com/Forums/en-US/8eda3544-53ed-43fa-ac53-87e721fa09c3/accessing-private-docker-registry-on-nonstandard-port-with-aci?forum=AzureContainerServices).

I'm relatively new to Azure and I was testing private registry on non-standard port as that's how some of our registries are configured (not always my choice). Using a proxy to re-map to port 443 did allow me to access the registry, thank you.

Copying images in to ACR is likely how the pipeline will eventually be configured, but that won't always be the case for everyone.

Other parts of the container ecosystem work fine with non-standard ports, including docker, kubernetes, etc. and I believe ACI should as well.

**Comment by adewaleo** [comment]
I am happy you got a workaround to work @kawaja. Sorry about the inconvenience.

@jakaruna-MSFT and @kawaja 
**Please note** though that I don't work on **ACI** but **ACR**. We will work on supporting **acr import** with port numbers, however working on az container create with non standard ports is beyond our scope. 

cc: @mmacy, @neilpeterson, @seanmck @dlepow as they are contributors to https://docs.microsoft.com/en-us/azure/container-instances/container-instances-quickstart

How do we get this issue (see [MSDN thread](https://social.msdn.microsoft.com/Forums/en-US/8eda3544-53ed-43fa-ac53-87e721fa09c3/accessing-private-docker-registry-on-nonstandard-port-with-aci?forum=AzureContainerServices)) to the ACS team? @kawaja had issues creating a container instance form a registry on a non-standard port.

**Comment by dlepow** [comment]
@dkkapur @macolso - Can you please comment on the `az container create` issue mentioned above when pulling an image from a private registry on a nonstandard port? Thanks you!

**Comment by yugangw-msft** [comment]
Since ACR repository is for tracking ACR particular issue, to route it effective, I suggest we close this issue and open a new one in Azure CLI and tag it for ACI team to take look.
