### ISSUE TITLE
Custom Domain - nginx proxy container returns "504 Gateway Time-out" after the IP of the ACR has changed

### ISSUE THREAD

**Issue by pihai** [Azure/acr#288]
**nginx proxy container returns "504 Gateway Time-out" after the IP of the ACR has changed**

Hi

I followed [this article](https://github.com/Azure/acr/tree/master/docs/custom-domain) to deploy a registry with a custom domain. Usually this works for a few days and then occasionally stops working.

Trying to curl the registry via the custom domain results in a timeout:

```
 curl https://<my-custom-domain>/v2/_catalog
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.15.12</center>
</body>
</html>
```

By looking at the logs of the proxy container i realized that nginx does the DNS resolution only on startup/config load:

```
104.42.137.111 - - [18/Oct/2019:04:34:25 +0000] "GET / HTTP/1.1" 499 0 "-" "Mozilla/5.0 zgrab/0.x"
2019/10/18 04:42:23 [error] 6#6: *10240 upstream timed out (110: Connection timed out) while connecting to upstream, client: 13.80.252.219, server: <my-custom-domain>, request: "GET /v2/_catalog HTTP/1.1", upstream: "https://52.236.186.83:443/v2/_catalog", host: "<my-custom-domain>"
13.80.252.219 - - [18/Oct/2019:04:42:23 +0000] "GET /v2/_catalog HTTP/1.1" 504 168 "-" "curl/7.47.0"
```

Notice that nginx used the IP address "52.236.186.83", which was resolved on startup, but now has changed to something else.

**To Reproduce**
1. Follow the instructions to create a registry with a custom domain
2. Wait a few days until the IP of the ACR changes (or force it somehow, maybe by recreating it)
3. execute a command like "docker login" or curl the API directly as I did

**Expected behavior**
I know that with a single frontend VM the availability isn't great anyway, but at least it should keep working when the IP of the ACR changes.

**Additional context**
It seems that this is a common problem with nginx. Maybe the following articles can help;
- [How to force nginx to resolve DNS (of a dynamic hostname) everytime when doing proxy_pass?](https://serverfault.com/questions/240476/how-to-force-nginx-to-resolve-dns-of-a-dynamic-hostname-everytime-when-doing-p)
- [Error with IP and Nginx as reverse proxy](https://stackoverflow.com/questions/26956979/error-with-ip-and-nginx-as-reverse-proxy)

**Comment by sajayantony** [comment]
@SteveLasker

**Comment by SteveLasker** [comment]
Hi @pihai,
This is unfortunately an NGINX bug. Each time we do a rollout, our IPs can change. This is why we require a cider range for whitelisting firewall rules, and not a specific IP. Even geo-replication can return multiple valid IP addresses. 

We are adding supported custom dns support with customer provided certs as well always require ssl. Timeframe is likely summer of 2020 before we complete the full experience. 
We are handholding a few large customers with custom domains. Feel free to contact me if your scenario is pretty big and you think we’d support it. 
For non-critical business, vanity domains, this nginx thing was a hope it would work. This makes me realize we should take this article down if nginx isn’t going to fix the refresh issue.

**Comment by pihai** [comment]
Thanks for the answer. Glad to hear that custom dns is coming in nearish future.

However i would not consider this as an nginx bug but rather a bug in the config. I ended up with this solution: https://github.com/pihai/acr/commit/ce4aceca036a69141097e9a983d800daddd7c39c

Working so far.

**Comment by sajayantony** [comment]
Closing this item since this is not an issue that will be fixed and has not had traction. ACR is moving towards a first class custom domain support - https://github.com/Azure/acr/pull/363
