### ISSUE TITLE
Need to understand how the AKS cluster is able to pull images

### ISSUE THREAD

**Issue by revanthalampally** [Azure/acr#290]
Hi All,

I have created an AKS cluster with a service principle.
The same service principle has access to ACR.

Now when I do any deployment, I am able to spin up pods without providing any ImagePullSecret for the ACR, unable to figure out how this is possible.

I tried logging into a AKS cluster and did docker pull of an image in ACR. I am asked to do a docker login first which make sense but I am clueless on how the pods are coming up without imagepullsecret.

**Comment by shizhMSFT** [comment]
@revanthalampally I'd clone this for you, but it would lose your tracking abilities. Please just copy/paste this over to https://github.com/Azure/AKS since it is an AKS key management issue.

**Comment by northtyphoon** [comment]
@revanthalampally AKS stores the service principal credential in /etc/kubernetes/azure.json. The following code uses the credential to login ACR and pull images.

https://github.com/kubernetes/kubernetes/blob/d6035f3e0d79dd05628ef42231beae97806a06ad/pkg/credentialprovider/azure/azure_credentials.go#L199

**Comment by revanthalampally** [comment]
@northtyphoon Thanks a lot. That explains a lot of things.
