### ISSUE TITLE
Suggesting the use of online base64 tool to encode username and password

### ISSUE THREAD

**Issue by grep-ir** [Azure/acr#291]
**Describe the bug**
https://github.com/Azure/acr/blame/master/docs/Token-BasicAuth.md#L44 suggests that readers of this doc use an online tool to base64 encode `username:password`.  This is a great way to hand over your credentials to the operator of that website.  It would be much better to use a bash utility such as `base64` to encode your string.

To encode:
`echo "username:password" | base64`

To decode:
`echo "myb64string" | base64 -D`

**Comment by hkuadithya** [comment]
Merged in this PR: https://github.com/Azure/acr/pull/292
Thanks @grep-ir
