### ISSUE TITLE
Base image update of ubuntu:18.04 on Docker Hub did not trigger my ACR task

### ISSUE THREAD

**Issue by BenjaminHerbert** [Azure/acr#295]
**Describe the bug**

I have setup an ACR task, which builds an image from a Dockerfile that relies on `ubuntu 18.04`.

I have followed the setup described in [Automate OS and framework patching](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-overview#automate-os-and-framework-patching) and have build the task once to let "ACR Tasks discover(...) the base image dependencies".

This setup was running fine a few weeks ago: a change on Docker Hub to `ubuntu:18.04` triggedd my task correctly, resulting in a acr task run and new image.

I have now discovered that six days ago, there was an update on Docker Hub for [`ubuntu:18.04`](https://hub.docker.com/_/ubuntu/?tab=tags&name=18.04&page=1) and the corresponding task was **not** triggered

The documentation tells: 

> For image builds from a Dockerfile, an ACR task detects dependencies on base images in the following locations:
> 
> * The same Azure container registry where the task runs
> * Another Azure container registry in the same region
> * A public repo in Docker Hub
> * A public repo in Microsoft Container Registry
> 
> If the base image specified in the FROM statement resides in one of these locations, the ACR task adds a hook to ensure the image is rebuilt any time its base is updated.

* Where is this _hook_ added? 
* How can I investigate if this hook is correctly added? 
* Can you detail what the ACR task does in the background or if applicable which other services is involved here?
* How can I **reliably** tell/check that the base-image update trigger works for my ACR tasks?

(Please note, if I run my task manually, the triggering of tasks that depend on image as a base image works fine, though.)

**To Reproduce**

I am not able to reproduce the error, as I have no control over the ubuntu Docker Hub.

**Expected behavior**

An update of the base image ubuntu:18.04 on Docker Hub should reliably trigger my ACR task.

Thanks for you help
Benjamin

**Comment by jaysterp** [comment]
@BenjaminHerbert thanks for reaching out. Can you please provide the registry and task name so we can investigate?

**Comment by BenjaminHerbert** [comment]
@jayterp I have just sent out an email to 'acrsup@microsoft.com' providing the information.

**Comment by jaysterp** [comment]
@BenjaminHerbert we indeed see that no build was triggered for your task on the ubuntu base image update a week ago. We have found a potential issue that may have caused this and are making a fix to address it now. Thank you for reporting!

**Comment by northtyphoon** [comment]
@BenjaminHerbert  we have deployed the fix.

**Comment by BenjaminHerbert** [comment]
I am looking forward for improvements here.

My main question is still:

> How can I reliably tell/check that the base-image update trigger works for my ACR tasks?

It's not helpful if I still have to track changes of Base-Images on Docker-Hub and see if the tasks were triggered correctly.

**Comment by northtyphoon** [comment]
@BenjaminHerbert If you go to portal and open tasks blade, you currently can list runs and see the associated task and trigger type, eg, base image update. We are also planning some improvements to allow you open specific task and quickly get the information about triggers, runs, image dependency etc. If you have specific idea in mind, please also let us know /cc: @SteveLas @sajayantony @ElianaLiberman

**Comment by BenjaminHerbert** [comment]
Hi @northtyphoon, I am not sure if I understand the meaning of the icons of the UI correctly. Does this mean the base-image-trigger is disabled? For me it looks like only the source trigger is set but the base-image-trigger is not. 

![grafik](https://user-images.githubusercontent.com/2254565/69708907-b86a5200-10fc-11ea-9d7f-181cb8dec0f4.png)

When I lookup the information with ` az acr task show -n ubuntu -r dvagcr -o json | jq '.trigger'`
it states that a baseImageTrigger with "name:defaultBaseimageTriggerName" has "status:Enabled":
it looks like there is a base-image-trigger?

```
{
  "agentConfiguration": {
    "cpu": 2
  },
  "creationDate": "2019-08-28T11:22:09.798633+00:00",
  "credentials": null,
  "id": "/subscriptions/xxxx/resourceGroups/xxx/providers/Microsoft.ContainerRegistry/registries/xxx/tasks/ubuntu",
  "identity": {
    "principalId": null,
    "tenantId": null,
    "type": "UserAssigned",
    "userAssignedIdentities": {
      "/subscriptions/xxx/resourcegroups/xxx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/bpAcrTasksIdentity": {
        "clientId": "xxx",
        "principalId": ""
      }
    }
  },
  "location": "westeurope",
  "name": "ubuntu",
  "platform": {
    "architecture": "amd64",
    "os": "linux",
    "variant": null
  },
  "provisioningState": "Succeeded",
  "resourceGroup": "xxx",
  "status": "Enabled",
  "step": {
    "baseImageDependencies": [
      {
        "digest": "sha256:6e9f67fa63b0323e9a1e587fd71c561ba48a034504fb804fd26fd8800039835d",
        "registry": "registry.hub.docker.com",
        "repository": "library/ubuntu",
        "tag": "18.04",
        "type": "Runtime"
      }
    ],
    "contextAccessToken": null,
    "contextPath": "https://xxx.visualstudio.com/xxxContainer/_git/ubuntu",
    "taskFilePath": "task.yaml",
    "type": "FileTask",
    "values": [],
    "valuesFilePath": null
  },
  "tags": null,
  "timeout": 3600,
  "trigger": {
    "baseImageTrigger": {
      "baseImageTriggerType": "Runtime",
      "name": "defaultBaseimageTriggerName",
      "status": "Enabled",
      "updateTriggerEndpoint": null,
      "updateTriggerPayloadType": "Default"
    },
    "sourceTriggers": [
      {
        "name": "defaultSourceTriggerName",
        "sourceRepository": {
          "branch": "master",
          "repositoryUrl": "https://xxx.visualstudio.com/xxxContainer/_git/ubuntu",
          "sourceControlAuthProperties": null,
          "sourceControlType": "VisualStudioTeamService"
        },
        "sourceTriggerEvents": [
          "commit"
        ],
        "status": "Enabled"
      }
    ],
    "timerTriggers": null
  },
  "type": "Microsoft.ContainerRegistry/registries/tasks"
}
```

So, how to interpret these values? I am still unsure how to reliably tell, that a base-image trigger is configured and working...!

**Comment by northtyphoon** [comment]
@BenjaminHerbert we will investigate the icon issue you reported. 
To track if the base image is triggered, for now you can see triggered runs from `Runs` tab. For example, I have a task depending on `mcr.microsoft.com/dotnet/core/runtime:2.2-stretch-slim` which was updated three times between 11/19 - 11/22.

![image](https://user-images.githubusercontent.com/2686301/69753843-56641980-1109-11ea-83c1-90079726f201.png)

![image](https://user-images.githubusercontent.com/2686301/69754041-ca9ebd00-1109-11ea-973b-1c349148f03a.png)

**Comment by BenjaminHerbert** [comment]
@northtyphoon I know that I _can_ check if a task is triggered by looking at the runs. By using ACR task, I want to **automate building** of images whenever a base-image update on Docker Hub happens. :

If I have to track *myself* whether base-image updates on Docker Hub are triggering my ACR tasks, then using this mechanism is kind of pointless :disappointed:

I need to know how to check if base-image triggers are setup correctly proactively - not by checking manually if it works after an image update is performed.

**Comment by sajayantony** [comment]
Is there some experience you had in mind. For e.g. could the portal lookup the current tag on dockerhub and show a warning that the image is behind the latest? 
Ideally this should be a short duration if we didn't have the bug that caused the builds to not trigger. 

I see that validating this is not quite straightforward.  But this is the check for the digest is as follows. 
Here you can see that the target manifest sha and the dependencies are the same for my build using the `step.baseImageDependencies[0].digest`. 

> I used cloud shell for this and task shows me that I have a runtime dependency on alipine:latest

```sh
# Get the token and the manifest digest for the base image
$ export token=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/alpine:pull" | jq -r .token)
$ curl -s -H "Accept: application/vnd.docker.distribution.manifest.list.v2+json" -H "Authorization: Bearer $token" "https://registry-1.docker.io/v2/library/alpine/manifests/latest" | sha256sum | cut -d " " -f1
7c92a2c6bbcb6b6beff92d0a940779769c2477b807c202954c537e2e0deb9bed

# Check the digest in your current build
$ az acr task show -n my-task --query "step.baseImageDependencies[0].digest" -o tsv | cut -d ":" -f2
7c92a2c6bbcb6b6beff92d0a940779769c2477b807c202954c537e2e0deb9bed
```

**Comment by BenjaminHerbert** [comment]
I am not sure I understand your question correctly. 😕 

My ideal experience would be:
- if I configure a base image update, it works and triggers my build.

A warning that the task is "behind" despite a base image update was discovered would not be my desired experience. If Azure discovers this fact, it could just trigger the task so that the image _is up to date_. This would require no further user interaction.

**Comment by sajayantony** [comment]
@BenjaminHerbert - During the last few months there have been a set of improvements that have been made on the tracking side. If this is still an issue please feel free to reopen the issue and the team will try to help as needed.

**Comment by MateuszGalasinski** [comment]
Hi, I encountered similar issue with not triggering build:
1) My task in ACR: 
![image](https://user-images.githubusercontent.com/39420679/92441600-ce8a6000-f1ae-11ea-8609-4e14cdefdc95.png)
2) Manual successful runs (no automatic run ever happened)
![image](https://user-images.githubusercontent.com/39420679/92441657-e2ce5d00-f1ae-11ea-94ca-2bf9f685f237.png)
3) Builds logs from last run, showing runtime-dependency on testproject/agent from dockerhub
![image](https://user-images.githubusercontent.com/39420679/92442699-9f74ee00-f1b0-11ea-8a42-e93618cf4ccc.png)
4) Dockerhub stating base image was updated on 04.09 
![image](https://user-images.githubusercontent.com/39420679/92442878-eebb1e80-f1b0-11ea-8937-a417bfe9a152.png)

Querying task info from cli results in similar info as in BenjaminHerbert's case:
`az acr task show -n testagentbase -r ldzimages -o json | jq '.trigger' `
``` json
{
  "baseImageTrigger": {
    "baseImageTriggerType": "Runtime",
    "name": "defaultBaseimageTriggerName",
    "status": "Enabled",
    "updateTriggerEndpoint": null,
    "updateTriggerPayloadType": "Default"
  },
  "sourceTriggers": null,
  "timerTriggers": null
}
```

I assume my acr task should ran on 04.09 with Trigger: Image Update, but as you can see last run was manual on 02.09.
@sajayantony, You've written there were improvements on the tracking side. Could you share any insight what else can I check to find out why it's not being triggered?

**Comment by BenjaminHerbert** [comment]
@sajayantony I had doubts that this is working reliably in the past weeks as well, but could not investigate further. Could you please check and reopen the issue?

**Comment by northtyphoon** [comment]
@MateuszGalasinski the screenshot you shared shows all your run were quick runs. Can you run the following command to populate the dependencies for the task? After that, 

```
az acr task run -n testagentbase -r ldzimages
```

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-base-image-update#build-the-application-container

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-base-images#base-image-notifications

**Comment by MateuszGalasinski** [comment]
@northtyphoon, sorry I had to wait for another update on Dockerhub, but it worked this time ! Thanks a lot for your help 👍 
Although it wasn't totally obvious since I couldn't find a way to see what's misconfigured, when it comes to me, we can close the issue.

**Comment by sajayantony** [comment]
Please re-open if this is still an issue.

**Comment by samuelraudabaugh** [comment]
I emailed this to acrsupport@microsoft.com with registry and task name information, but posting here in case anyone else has suggestions.

My task has the base image trigger enabled icon lit up, and a new version of my base image, drupal:10, was published to Docker Hub yesterday, but the history on the “Runs” tab only shows Manual triggers. I tried the task run command suggested by @northtyphoon, but I got the following error:

Adding the context and file flags didn't help either.

```
❯ az acr task run -n $TASKNAME -r $REGNAME -c https://github.com/myorg/myproject.git -f Dockerfile
Sending context to registry: []...
Queued a run with ID: ch4
Waiting for an agent...
2023/03/17 17:18:11 Downloading source code...
Run ID: ch4 failed after 2s. Error: failed to download context. Please check if the URL is incorrect. If it has credentials, please check if they are expired
Run failed
```

Any suggestions?
