### ISSUE TITLE
Base image update of centos:7 on Docker Hub triggered my ACR task **twice**

### ISSUE THREAD

**Issue by BenjaminHerbert** [Azure/acr#300]
**Describe the bug**
I have setup an ACR task _centos_, which builds an image from a Dockerfile that relies on `centos:7`.

I have followed the setup described in [Automate OS and framework patching](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-overview#automate-os-and-framework-patching) and have build the task once to let "ACR Tasks discover(...) the base image dependencies".

Yesterday there was an update to [centos:7 on Docker Hub](https://hub.docker.com/_/centos/?tab=tags&page=1&name=7), this caused my _centos_ ACR task to be triggered **twice**. 

Both runs have the same start date:

> **2019-11-12T00:54:45Z**
> **2019-11-12T00:54:45Z** 

**To Reproduce**
I am not able to reproduce the error, as I have no control over the ubuntu Docker Hub.

**Expected behavior**
I expect that an update to the centos:7 image on Docker Hub triggers my build **exactly once**.

**Screenshots**
Screenshot of the triggered runs (`az acr task list-runs -n centos -r "myregistry"`)
![grafik](https://user-images.githubusercontent.com/2254565/68655037-933be800-052f-11ea-87aa-e898a113f91d.png)

**See also**
With an _ubuntu_ ACR task I had the issue that [**no** run was triggered after an image update](https://github.com/Azure/acr/issues/295).

**Comment by northtyphoon** [comment]
@BenjaminHerbert we are aware of the two issues you reported recently and will release a fix soon.

**Comment by northtyphoon** [comment]
@BenjaminHerbert we have deployed the fix

**Comment by northtyphoon** [comment]
Verified the duplicated trigger issue has been fixed. If you hit it again, please reopen it.
