### ISSUE TITLE
Pull and push on ACR fails with private agents 

### ISSUE THREAD

**Issue by Jyoti492** [Azure/acr#305]
Hi Team,

I am able to connect the ACR via Service Connection only on hosted agents and on our private agents it fails with the error as below although the ACR is open for all networks. Can you please let us know if we have to do any specific settings on the agent.
The push refers to repository [mcpsharedreg.azurecr.io/coesd/aab-base-deploy-helm]
Get ***v2/: read tcp 10.232.61.203:43262->52.236.186.80:443: read: connection reset by peer
##[debug]Exit code 1 received from tool '/bin/docker'
##[debug]STDIO streams have closed for tool '/bin/docker'
##[error]Get ***v2/: read tcp 10.232.61.203:43262->52.236.186.80:443: read: connection reset by peer

**Comment by sajayantony** [comment]
@northtyphoon - can you please have this routed to someone on the DevOps team?

**Comment by SteveLasker** [comment]
I'm looking for a DevOps contact and repo to transfer these to.

**Comment by SteveLasker** [comment]
Assigning to @azooinmyluggage for DevOps

**Comment by sajayantony** [comment]
Closing this issue since it hasn't had any traction for more than 2 months. @Jyoti492   Please feel free to open a support ticket against Azure DevOps if this is still an issue through Azure Support.
