### ISSUE TITLE
ACR ARM Template when exported has unsupported scope map configs characters

### ISSUE THREAD

**Issue by ardhar** [Azure/acr#312]
**Describe the bug**
When ACR ARM template is exported, it gets scope maps configuration with unsupported characters such as "_" and this prevents the ARM template from importing. 

Template export contains unsupported characters and this prevents importing the template.  

**To Reproduce**
1. Create Resource Group
2. Create ACR 
3.  Goto Export Template and export the ACR Template. 
4. Delete the ACR 
5. Try importing the template and create the ACR 

**Expected behavior**
Import operation should work seamlessly 

**Screenshots/Logs**
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "BadRequest",
      "message": "{\r\n  \"error\": {\r\n    \"code\": \"ResourceNameWithHyphenInvalid\",\r\n    \"message\": \"Invalid resource name: '_repositories_admin'. Resource names must contain only alphanumeric characters optionally separated by '-'. The total length of the name including hyphens should be at least 5 and less than 50 characters. Also, '_' is reserved for system defined resources. For more information on repository permissions, please visit https://aka.ms/acr/repo-permissions\"\r\n  },\r\n  \"status\": \"Failed\"\r\n}"
    },
    {
      "code": "BadRequest",
      "message": "{\r\n  \"error\": {\r\n    \"code\": \"ResourceNameWithHyphenInvalid\",\r\n    \"message\": \"Invalid resource name: '_repositories_pull'. Resource names must contain only alphanumeric characters optionally separated by '-'. The total length of the name including hyphens should be at least 5 and less than 50 characters. Also, '_' is reserved for system defined resources. For more information on repository permissions, please visit https://aka.ms/acr/repo-permissions\"\r\n  },\r\n  \"status\": \"Failed\"\r\n}"
    },
    {
      "code": "BadRequest",
      "message": "{\r\n  \"error\": {\r\n    \"code\": \"ResourceNameWithHyphenInvalid\",\r\n    \"message\": \"Invalid resource name: '_repositories_push'. Resource names must contain only alphanumeric characters optionally separated by '-'. The total length of the name including hyphens should be at least 5 and less than 50 characters. Also, '_' is reserved for system defined resources. For more information on repository permissions, please visit https://aka.ms/acr/repo-permissions\"\r\n  },\r\n  \"status\": \"Failed\"\r\n}"
    }
  ]
}

**Any relevant environment information**
 - OS: [e.g. Ubuntu, Windows] : NA
 - Azure CLI/PowerShell/SDK version : NA
 - Docker version : NA
 - Datetime (UTC) when the issue occurred: Everytime it occurs and reproducible 
 - Registry and image names : NA

**Additional context**

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by susanshi** [comment]
this has been fixed and deployed last week.   Please verify.
I have verified the following scenarios:
Create a premium registry, export template,   delete registry and create a registry from the template,
Create a basic registry, export template,   delete registry and create a registry from the template.

Note: if exporting an existing registry with TBAC tokens, users will need remove the credentials of tokens before deploying the arm template.
