### ISSUE TITLE
Unable to update existing encodedtask using "az acr task update -f" command

### ISSUE THREAD

**Issue by northtyphoon** [Azure/acr#313]
**To Reproduce**
1. az acr task create -r myregistry -n mytask -f acb.yaml -c /dev/null
2. az acr task update -r myregistgry -n mytask -f acb.yaml

`acr task update` failed as the following error message:

Cannot determine the build context for the step of the task 'createcontainer2'. Either the context should be a well formed absolute URI or there should be only one source trigger for the task.

**Expected behavior**
The task is updated.

az --version
azure-cli                         2.0.77

**Comment by terencet-dev** [comment]
This has been fixed
