### ISSUE TITLE
Unable to create ACR tasks with more than 2 CPUs

### ISSUE THREAD

**Issue by yubhat** [Azure/acr#321]
az acr task create -n hello-world -r reshatest --cmd MyImage -c /dev/null --cpu 4
See the error : Some of the properties of 'taskCreateParameters' are invalid.. InnerErrors: AgentProperties:Invalid value for CPU).The supported values are (2)
From the error ACR tasks currently only supports 2 CPUs and by design limit for ACR and cannot be exceeded. 

Creating Github feature request to create more than 2 CPUs for ACR Tasks. 

Are there any memory limitations for the tasks and is there a way to increase or modify the memory allocation for the ACR tasks?

**Comment by blackbaud-alanacable** [comment]
I am having a similar issue when I try to create a task with only one cpu.  The error message I get is `InvalidInputValue - Some of the properties of 'taskCreateParameters' are invalid.. InnerErrors: AgentProperties:Invalid value for CPU core count. The supported values are (2)`. Why is creating a ACR task limited to only 2 CPU's?

**Comment by terencet-dev** [comment]
Closing as this has been inactive for over three months. Please open a [support ticket](https://azure.microsoft.com/support/create-ticket/) with our team for assistance.
