### ISSUE TITLE
[Reliability] Ensure registry reliability for high load regions

### ISSUE THREAD

**Issue by sajayantony** [Azure/acr#322]
The engineering team has been working on improving scale and reliability for high load regions over the past few months. These regions rapidly grew over the last year and even though infrastructure was being allocated proportionately, there were architectural limits we hit. This lead us to re-prioritize work and resulted in re-architecting our infrastructure and update our provisioning model to support higher load. Going forward will also enable the service to reduce the negative impact when rolling out changes and provide us a way to grow at the rate we are currently observing.

The first set of these changes are planned for rollout completion by Jan 31st 2020.

**Comment by yugangw-msft** [comment]
Rolled out
