### ISSUE TITLE
acr task to support registry regex for --filter and use only --untagged

### ISSUE THREAD

**Issue by slawekww** [Azure/acr#323]
**What is the problem you're trying to solve**
Write acr task to purge all untagged images for all repositories.
As example:
acr purge --filter 'repository:.*' --ago 0d --untagged

For now it is not possible to define regex for repository and untagged option is optional:
task would untag all images which matches regex and it would clean by repository!

**Describe the solution you'd like**
Allow to define acr task like:
acr purge --filter '.*:.*' --ago 0d --untagged

It should go thru all repositories and clean all untagged images, similar to command:
az acr repository show-manifests --name $REGISTRY --repository $REPOSITORY  --query "[?tags[0]==null].digest" -o tsv \
    | xargs -I% az acr repository delete --name $REGISTRY --image $REPOSITORY@% --yes

Cleanup only untagged images within repositories - it means that regex for repository would be taken into account only.

**Comment by northtyphoon** [comment]
@SteveLasker  can you review the suggestion?

**Comment by slawekww** [comment]
I do not expect this feature anymore.
