### ISSUE TITLE
az acr check-health : Error image operating system "linux" cannot be used on this platform

### ISSUE THREAD

**Issue by Pankaj-Thakur** [Azure/acr#328]
**Describe the bug**
The issue is with the az acr check-health command. It is this command that, as part of its diagnostics, pulls a hello world image. Problem seems that, az acr check-health is pulling a linux image whereas my docker host is configured for windows.
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-check-health

I do not have issue pulling images from my registry. Docker is configured for windows. 

**To Reproduce**
1. Download and configure Docker for windows.
2. Run 'az acr check-health --name <NameofACR>--ignore-errors --yes' 

**Expected behavior**
1. No errors or real errors.
2. Bugs in the 'az acr check-health' command not expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/20115956/71853192-80f1ac80-308f-11ea-9022-dd6667cd0f9f.png)

**Any relevant environment information**
 - OS: [ Windows]
 - Azure CLI
 - Docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:36:50 2019
  OS/Arch:          windows/amd64
  Experimental:     false
 - Datetime (UTC) 1/6/2020 1900 UTC
 - Registry name: D365DevALMInternal

**Additional context**

**Comment by hkuadithya** [comment]
I suppose the best way to handle this would be to generate a `multi-arch` hello-world docker image supporting Windows and Linux platform and then, push the updated image to Microsoft container registry.

We could explore [manifest tool](https://github.com/estesp/manifest-tool) for generating this. @shizhMSFT any thoughts? 

@yugangw-msft please feel free to assign this issue to one of the engineers.

**Comment by shizhMSFT** [comment]
From the output below:
```
$ docker manifest inspect mcr.microsoft.com/mcr/hello-world
{
        "schemaVersion": 2,
        "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
        "config": {
                "mediaType": "application/vnd.docker.container.image.v1+json",
                "size": 1510,
                "digest": "sha256:fce289e99eb9bca977dae136fbe2a82b6b7d4c372474c9235adc1741675f587e"
        },
        "layers": [
                {
                        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
                        "size": 977,
                        "digest": "sha256:1b930d010525941c1d56ec53b97bd057a67ae1865eebf042686d2a2d18271ced"
                }
        ]
}
```
MCR only provides single platform images. MCR needs to onboard `hello-world` images for multiple platforms with a manifest list. 

@hkuadithya Try `docker manifest` to `inspect` or `create` a manifest list.

**Comment by nathana1** [comment]
Can we import the main docker hello-world (docker manifest inspect docker.io/library/hello-world) into mcr?

**Comment by northtyphoon** [comment]
windows has 5+ versions and the number is still increasing. AFAIK, there is no `official` multi-arch image covering all versions. If we want to support all of them, we will likely need to create our own. We also need to maintain it to catch up the monthly update.

Another thought, if the main purpose of the validation is to test the network connection, we can think about a different approach such as download the layer and manifest blob directly.

**Comment by sajayantony** [comment]
Ideally the check-health tool doesn't have to fail in this case. The basic requirement is that it is able to communicate to the docker daemon and should be able to pull the manifest. Which in this case is done. So if check-health can just warn and move on it might be good enough.

**Comment by yugangw-msft** [comment]
@Wwwsylvia, please pick up this issue after done with CLI ones. Let me know if you have any questions
/CC: @shizhMSFT

**Comment by sajayantony** [comment]
@Wwwsylvia - were you able to make progress on this?

**Comment by Wwwsylvia** [comment]
> @Wwwsylvia - were you able to make progress on this?

Oh sorry I can't believe I missed this one out... 
Will check this now

**Comment by Wwwsylvia** [comment]
PR merged
