### ISSUE TITLE
Retention Policy not having any effect

### ISSUE THREAD

**Issue by ball-hayden** [Azure/acr#342]
**Describe the bug**

I have applied a retention policy to a container registry. I have registries with a large number of manifests that are no longer referred to by tags, but they are not removed after the retention period has expired.

**To Reproduce**
1. Create a container registry
2. Push a number of images
3. Remove tags from some images
4. Enable retention policies with a short period (<n> days)
5. Wait until the retention period expires
6. Observe that the manifest count and used storage does not change

**Expected behavior**
After <n> days the manifest count and used storage reduces, as manifests no longer referenced by tags are removed.

**Comment by ankurkhemani** [comment]
@ball-hayden As per [docs here](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-retention-policy#preview-limitations), the retention policy currently applies only to manifests that are untagged after the policy is enabled. Existing untagged manifests in the registry aren't subject to the policy. To delete existing untagged manifests, see examples in [Delete container images in Azure Container Registry](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-delete).

**Comment by ball-hayden** [comment]
Ah. I understand.
So if I keep waiting, at some stage (when this limitation is lifted) they should go away?

**Comment by ankurkhemani** [comment]
@ball-hayden We are not yet sure on how the experience will look in future. So, I would recommend using [Delete container images in Azure Container Registry](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-delete) if you want to purge the manifests that were left untagged before enabling retention policy.
