### ISSUE TITLE
Acr build vague error when using symbolic links

### ISSUE THREAD

**Issue by rosanch** [Azure/acr#344]
**Describe the bug**
When having a symbolic link in the working directory that file, build fails to untar the symbolic link file but outputs failed to download source instead.

**To Reproduce**
1. create a symbolic link pointing to a resource outside your workspace.
2. run build from that workspace.

**Expected behavior**
Should output invalid symlink \"/workspace/etc -> /something

**Comment by terencet-dev** [comment]
Closing as this has been inactive for over three months. Please open a [support ticket](https://azure.microsoft.com/support/create-ticket/) with our team for assistance.
