### ISSUE TITLE
"az acr run --cmd" should keep the image workdir by default

### ISSUE THREAD

**Issue by northtyphoon** [Azure/acr#346]
**What is the problem you're trying to solve**
az acr run -r myregistry --cmd mcr.microsoft.com/dotnet/core/samples:dotnetapp /dev/null

The `dotnetapp` image sets the workdir to `/app` folder. Its entrypoint and cmd settings assume the current working directory is `/app` folder. However ACR Tasks by default launches the container using  `/workspace` as the workdir so the above cli command will fail. 

**Describe the solution you'd like**

Since the main usage of `--cmd`  is to launch the container image as it is, it's better to minimize the override behavior, especially avoid overriding the workdir folder.

So when generating the task step in the request, the cli command should pass `disableWorkingDirectoryOverride: true`

**Comment by sajayantony** [comment]
This makes sense. +1

**Comment by northtyphoon** [comment]
update cli
https://github.com/Azure/azure-cli/commit/4ac58c0a49fa27c91eb380c7f4ccc5f76d886fb9
