### ISSUE TITLE
ACR does not support Docker Content Trust

### ISSUE THREAD

**Issue by EmJayBee83** [Azure/acr#35]
Docker Content Trust allows signing of images in a manner transparent to users.

Docco: https://docs.docker.com/engine/security/trust/content_trust/

**Comment by syedyali** [comment]
+1

**Comment by sajayantony** [comment]
https://github.com/Azure/acr/blob/master/docs/FAQ.md#does-azure-container-registry-support-content-trust

**Comment by SteveLasker** [comment]
Great to get the content trust docs added. 
I understand why contributor is required for push, but why owner?  Owner shouldn’t be required for this flow.
