### ISSUE TITLE
ACR login/docker login fails with internal server error for small percentage of customers.

### ISSUE THREAD

**Issue by susanshi** [Azure/acr#352]
**Describe the bug**
When AAD Jwt token contains `objectId` with `null` values, endpoints `/oauth2/exchange` and  `/oauth2/token`  throws 500 internal server error

**To Reproduce**
1.  az acr login -n repo name
2.  command fails with internal server error

**Expected behavior**
Login should succeed.
 
**Any relevant environment information**
 User can run into this issues from both az cli and azure portal. Logging in using admin account is not impacted.

**Additional context**
We have prepared a fix which will be deployed in the coming week.

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by ankurkhemani** [comment]
The fix has been deployed to all public prod regions.
