### ISSUE TITLE
Private Link

### ISSUE THREAD

**Issue by Mr-iX** [Azure/acr#360]
Hi all,

thank you very much for implementing private endpoints in the container registry. It's such a nice feature!

I have noticed the following issue. When I try to login using the private DNS name, I get an invalid certificate error message:
```bash
[root@registry user]# docker login acr.privatelink.azurecr.io
Username: acr
Password:
Error response from daemon: Get https://acr.privatelink.azurecr.io/v2/: x509: certificate is valid for *.azurecr.io, not acr.privatelink.azurecr.io
```

Also you stated in the documentation, that you can use private endpoints through a VPN tunnel from your on premises site. But the DNS Name `acr.azurecr.io` resolves to a public ip, so that the docker client uses the public connection and not the VPN tunnel. When trying to access the ACR through it's ip adress, I get the following error message:
```bash
[root@onprem user]# docker login 192.168.1.10
Username: acr
Password:
Error response from daemon: Get https://192.168.1.10/v2/: x509: cannot validate certificate for 192.168.1.10 because it doesn't contain any IP SANs
```
So what is the correct way to connect to the ACR from on premises?

**Comment by jomeier** [comment]
Is it not possible to add a self signed certificate to the ACR or a private custom hostname?

**Comment by northtyphoon** [comment]
@Mr-iX  You should continue to login in as `docker login acr.azurecr.io` on promise. On your VNet, if you run `nslookup azr.azurecr.io`, you are supposed to be see it is resolved to a local ip from the subnet.

For preview release, you can still resolve `acr.azurecr.io` domain from public internet. However you can block the access from public internet by running the following command.

`az acr update --default-action Deny`

/cc @yugangw-msft @djyou

**Comment by Mr-iX** [comment]
@northtyphoon Yes, when I resolve the DNS name from my VNET, it shows the private up, but only when I checked the box to create the private DNS zone. 
I already blocked all internet traffic, but now I cannot access the ACR from on premises, because it doesn’t use the private endpoint over the VPN tunnel. 
It would be great when I can set a custom C-name for the ACR and upload a self-signed certificate for this C-name.

**Comment by northtyphoon** [comment]
@yugangw-msft @sajayantony @avtakkar can you help clarify the custom domain support?

**Comment by sajayantony** [comment]
@Mr-iX - As @northtyphoon pointed out, custom domain with customer provided certificates  is something we are evaluating. For private link the expectation is that the same CNAME as the public DNS should be used even in the internal network as you will be using Azure Private DNS in this environment. Please vote on the user-voice item here. 
https://feedback.azure.com/forums/903958-azure-container-registry/suggestions/35141614-add-ssl-properties-like-in-app-service

@SteveLas - there are 2 items on uservoice that point to custom domain capabilities - might be worth unifying them. 
https://feedback.azure.com/forums/903958-azure-container-registry?query=domain

**Comment by Mr-iX** [comment]
@sajayantony So means that I have to modify the /etc/hosts file on all my onpremises systems? This would be very difficult, because a lot of developers in our company use the ACR.
Also could you clarify why I need to create a private DNS zone, so that the public hostname resolves to the private ip? Normally for accessing a service privately I just have to add a service endpoint to my vnet

**Comment by yugangw-msft** [comment]
@Mr-iX, on VNET isolation through private endpoint, you will need to set up VPN gateway or  ExpressRoute private peering. Let me know whether or not you have set that up or need more information.

Creating a DNS zone's purpose is to have the dns resolution to resolve "myreg.azurecr.io" to a a particular private ip allocated to the registry endpoint, and  based on the internal mapping (invisible to users), the push/pull will be evetually routed to ACR infrastructure through Azure dedicated network

**Comment by Mr-iX** [comment]
@yugangw-msft Thanks for your reply!
Actually we have setup a VPN gateway with BGP enabled. So when a on premises devices wants to access a private Azure IP, the traffic is routed through this VPN tunnel.

I tried to integrate the private IP in our DNS infrastructure, but there are two problems:
- with a custom DNS name, the certificate of the ACR is not valid anymore. But a client from on premises must resolve my custom DNS name, because otherwise it resolves the public DNS name (rusacrbdpd.azurecr.io) and the traffic is not routed through the VPN tunnel
- When I try to resolve the DNS name "rusacrbdpd.azurecr.io" in Azure it still resolves to the public ip and not the the private IP, even when I created an A-record in my private DNS zone

Some debug information:
- private DNS zone entry (Zone name: mgmt.1eu1.apps-d.rsext.net)
![image](https://user-images.githubusercontent.com/25360303/78106243-47f97780-73f3-11ea-9dd8-26cd23cacfaa.png)

- private endpoint of ACR
![image](https://user-images.githubusercontent.com/25360303/78106276-5c3d7480-73f3-11ea-9ff0-86b411391cba.png)

- The private endpoint is in a separate VNET which is peered to the VNET where our VPN tunnel terminates and the VM "dns2" is in

- query Azure DNS server for public ACR name
```bash
[root@dns2 user]# dig @168.63.129.16 rusacrbdpd.azurecr.io

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.el7 <<>> @168.63.129.16 rusacrbdpd.azurecr.io
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7382
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
; OPT=65436: 0b a7 c6 1a 22 1e c8 4f a3 62 b2 cd 90 40 ed 01 ("...."..O.b...@..")
;; QUESTION SECTION:
;rusacrbdpd.azurecr.io.         IN      A

;; ANSWER SECTION:
rusacrbdpd.azurecr.io.  1800    IN      CNAME   rusacrbdpd.privatelink.azurecr.io.
rusacrbdpd.privatelink.azurecr.io. 1800 IN CNAME weu-2.fe.azcr.io.
weu-2.fe.azcr.io.       409     IN      CNAME   weu-2-acr-reg.trafficmanager.net.
weu-2-acr-reg.trafficmanager.net. 71 IN CNAME   r0311weu-2.westeurope.cloudapp.azure.com.
r0311weu-2.westeurope.cloudapp.azure.com. 10 IN A 52.236.186.80

;; Query time: 65 msec
;; SERVER: 168.63.129.16#53(168.63.129.16)
;; WHEN: Wed Apr 01 06:28:22 UTC 2020
;; MSG SIZE  rcvd: 251
```
- query Azure DNS server for private DNS name
```
[root@dns2 user]# dig @168.63.129.16 rusacrbdpd.mgmt.1eu1.apps-d.rsext.net

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.el7 <<>> @168.63.129.16 rusacrbdpd.mgmt.1eu1.apps-d.rsext.net
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1467
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
; OPT=65436: 0b a7 c6 1a 22 1e c8 4f a3 62 b2 cd 90 40 ed 01 ("...."..O.b...@..")
;; QUESTION SECTION:
;rusacrbdpd.mgmt.1eu1.apps-d.rsext.net. IN A

;; ANSWER SECTION:
rusacrbdpd.mgmt.1eu1.apps-d.rsext.net. 1800 IN A 100.124.1.5

;; Query time: 4 msec
;; SERVER: 168.63.129.16#53(168.63.129.16)
;; WHEN: Wed Apr 01 06:29:56 UTC 2020
;; MSG SIZE  rcvd: 102
```

**Comment by yugangw-msft** [comment]
@SteveLas, we should route this support to network team, because private link fails at the basic step below, which has to work.  I will start a mail thread. @Mr-iX you can feel free to reach to me at yugangw at microsoft dot com  
```
When I try to resolve the DNS name "rusacrbdpd.azurecr.io" in Azure it still resolves to the public ip and not the the private IP, even when I created an A-record in my private DNS zone
```

**Comment by yugangw-msft** [comment]
@Mr-iX:
Some document here hope they help. The one hosted at github has a pretty good section for on-premise integration, do give it read.

Official public documentation:
https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances#name-resolution-that-uses-your-own-dns-server
https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-overview#dns-configuration

A good write up from field:
https://github.com/dmauser/PrivateLink/tree/master/DNS-Integration-Scenarios

**Comment by yugangw-msft** [comment]
@Mr-iX, per our offline communication, it is clear you need custom private DNS name for the private endpints, which are not available right now. 
Since this is a network ask, I am closing this issue. 
Feel free to reactivate if you have any other questions we can help

**Comment by jomeier** [comment]
What do you recommend to us whom we can contact? Closing this issue without further contact details does not really help 😉

**Comment by sajayantony** [comment]
@jomeier and @Mr-iX  Please create an support ticket through the Azure portal. We help route it through to the right team. You want a general advisory since Custom Domains using private link as a DNS override is an unsupported scenario at this point.

**Comment by mhtonysantaferra** [comment]
My company just ran into this specific issue.  The Private Endpoints which setup a specific IP address that should be what the DNS that gets setup inside an AKS cluster should resolve to the cluster IP. 

The fact that it doesn't allow this to work is a failure since we cannot authenticate against the ACR with this causes us to force public access to the ACR and force our AKS to have to connect to it over the public internet.

Ideally the DNS override should be the case from within private resources when the link/endpoint are generated.

**Comment by VGerris** [comment]
And 4 years later this still doesn't work. If I have a vpn up towards the 10.x network amd working dns resolution, the az acr login command still fails and suggesting my public IP should be added. Why doesn't it resolve to the public IP? Looks a like like the bug reported that is still open for over 3 years. Please fix this instead of requiring unnecessary complicated additional network configuration and make sure it works on all OSes. Thank you
