### ISSUE TITLE
ACR login failed with error unauthorized: Application not registered with AAD

### ISSUE THREAD

**Issue by jmaitrehenry** [Azure/acr#366]
**Describe the bug**
When we try to connect to ACR using a SP failed with error: `unauthorized: Application not registered with AAD`

**To Reproduce**
1. Create new ACR using Azure cli `az acr create -n myacr -g myrg --sku basic` or with the web UI
2. Add new assignment using AKS `az aks update -n myaks -g myrg --attach-acr myacr`
3. Deploy a new app in AKS using a private image hostedin our ACR

Event from AKS:
```
  Normal   Pulling    14s (x2 over 27s)  kubelet, aks-std2cpu8g-xxx-vmss000001  Pulling image "myacr.azurecr.io/app-web:120"
  Warning  Failed     14s (x2 over 27s)  kubelet, aks-std2cpu8g-xxx-vmss000001  Failed to pull image "myacr.azurecr.io/myimage:latest": [rpc error: code = Unknown desc = Error response from daemon: Get https://myacr.azurecr.io/v2/myimage/manifests/latest: unauthorized: Application not registered with AAD., rpc error: code = Unknown desc = Error response from daemon: Get https://myacr.azurecr.io/v2/app-web/manifests/120: unauthorized: authentication required]
  Warning  Failed     14s (x2 over 27s)  kubelet, aks-std2cpu8g-xxx-vmss000001  Error: ErrImagePull
  Normal   BackOff    0s (x2 over 26s)   kubelet, aks-std2cpu8g-xxx-vmss000001  Back-off pulling image "myacr.azurecr.io/myimage:latest"
  Warning  Failed     0s (x2 over 26s)   kubelet, aks-std2cpu8g-xxx-vmss000001  Error: ImagePullBackOff
```

**Expected behavior**
- AKS can pull images from ACR

**Any relevant environment information**
Azure CLI:
```
❯ az version
This command is in preview. It may be changed/removed in a future release.
{
  "azure-cli": "2.3.1",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.3.1",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}
}
```
AKS: 0.16.7

**Comment by jmaitrehenry** [comment]
I will close my issue, AKS was configured with the SP name and not the client id.

**Comment by marcosflobo** [comment]
@jmaitrehenry could you please elaborate more on your answer. I'm facing this issue and I did not experience it in the past.

I have the same issue. In my case, **there some images**, which are in the ACR for a long time but new tags, that **can be pulled**. There are others, which are recently new and added into the ACR, that I face the same error

```
rpc error: code = Unknown desc = Error response from daemon: Get https://myregistry.azurecr.io/v2/mynewimage/1.0.0/manifests/1.0.0: unauthorized: Application not registered with AAD., rpc error: code = Unknown desc = Error response from daemon: Get https://myregistry.azurecr.io/v2/mynewimage/1.0.0/manifests/1.0.0: unauthorized: authentication required
```

I think in my case the problem are not the credentials, since some of the images can be pulled.

**Comment by jmaitrehenry** [comment]
In my case, it's when I created my AKS cluster, I didn't use the client_id of my Service Principal but it's name (https://mysp). By reconfiguring the SP of AKS the problem was solve.

In your case, if you can pull some image but not other image it's weird. Is it possible that your cluster doesn't pull older tag because they are already present in the nodes?

You can check the SP inside the Azure Active Directory, you can get is ID by running the first command in the reset documentation:
https://docs.microsoft.com/en-us/azure/aks/update-credentials

If the SP exist and have some role assigned on your ACR, maybe try to do an acr login and pull manually:
```
az acr login --name myacr -u sp_client_id -p sp_secret
docker pull myacr.azurecr.io/myimage:mytag
```

If it works, it's maybe a problem with the credentials inside your AKS cluster that need to be reset. Else, maybe open a new issue as this one is close and may not be related to your problem.

**Comment by marcosflobo** [comment]
At the I solved out. In my deployment.yaml I was missing the `imagePullSecrets` parameter. Details [here](https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry).

So, yes at some point it was related to permissions.

**Comment by rocketraman** [comment]
@jmaitrehenry Thank you for posting your solution, I made the same mistake of providing the service principal name instead of the application id at cluster creation time, and the link you posted provides the mechanism to update the credentials.

@marcosflobo FYI, you shouldn't need to specify imagePullSecrets in the deployemnt if you have properly attached the registry to the cluster.

**Comment by rocketraman** [comment]
Its not surprising people are making this mistake: the documentation is totally useless:

![image](https://user-images.githubusercontent.com/53049/98304482-0c78ea00-1f8e-11eb-8a50-520d26ce89fe.png)

Gee, thanks.
