### ISSUE TITLE
Unable to get AAD authorization tokens with .devcontainer

### ISSUE THREAD

**Issue by RickC37** [Azure/acr#367]
**Describe the bug**
Since some weeks I use now .devcontainer, which is a pretty cool new technology from Microsoft.

However, it seems that the Azure ACR CLI is not working as expected. 

```
sudo az acr login --name containerregistryname
Unable to get AAD authorization tokens with message: Please run 'az login' to setup account.
Unable to get admin user credentials with message: Please run 'az login' to setup account.
Username:
```

**To Reproduce**
1. Create/build a  .devcontainer with Debian 9, Azure CLI and Docker CE CLI 
2. Mount the containers Docker CLI to the hosts Docker Deamon (in my case Mac OS X) 
3. run `sudo az acr login --name containerregistryname`

**Comment by yugangw-msft** [comment]
@RickC37, can you follow the error and run the "az login", or do you expect .devcontainer pre-authenticate you?

**Comment by RickC37** [comment]
Hi @yugangw-msft,
thx for the quick reply.

I forgot to mention, that I did the `az login` beforehand.
If I use other `az` cli command it works straight away.
But `az acr` do not work somehow.

Any idea?

**Comment by yugangw-msft** [comment]
@RickC37, do you also run `az login` with `sudo`?

**Comment by yugangw-msft** [comment]
Please feel free to activate it with the details to reproduce

**Comment by KalanaDananjaya** [comment]
I faced the same issue. @yugangw-msft's answer resolved the issue https://github.com/Azure/acr/issues/367#issuecomment-614232197

**Comment by DietmarReply** [comment]
I have the same issue and adding sudo does not solve the issue for me. 

Any other solutions?

**Comment by seongkyu-lim** [comment]
I have the same issue and does not solve the issue by adding sudo..!
I used well with azure cli but situation has happend suddenly.
