### ISSUE TITLE
ACRTask do not trigger properly when I delete the digest of images and publish again

### ISSUE THREAD

**Issue by kuwe1990** [Azure/acr#373]
I try to test my ACR Task in our dev env. There are some issue which I can not trigger the acrTask properly.
Below are the command I run.
docker pull onepubacrprod.azurecr.io/public/windows/nanoserver:1903
# Create a ACR task hook to base image onepubtestacrdev.azurecr.io/public/windows/servercore:1903
# Trigger acr task once.
docker push origin onepubtestacrdev.azurecr.io/public/windows/servercore:1903

Then the acrTask triggered properly and then.

I remove the base images by
az acr repository delete --name OnePubTestAcrDev --image public/windows/servercore:1903

Then I push the same image to acr again 
docker push origin onepubtestacrdev.azurecr.io/public/windows/servercore:1903.

Then the acr can not trigger properly.

My question is as my understanding, I already remove the tag from the acr and republish. Why the hook did not trigger. How the hook really works? The only way I can trigger acrTask is update the base images?

**Comment by northtyphoon** [comment]
@kuwe1990 in your second push, was `onepubtestacrdev.azurecr.io/public/windows/servercore:1903`  changed from first push? if not, it wouldn't trigger a new run. Base image trigger monitor the manifest change of the tag and trigger the run if it detects a change. /cc: @jaysterp @djyou

**Comment by kuwe1990** [comment]
Hi Bin, The image do not change actually. I know ACR task will trigger when the manifest digest get update. But before I push the same images, I already remove the original images from ACR by az acr repository delete --name OnePubTestAcrDev --repository public/windows/servercore:1903 And after that, I actually check manifest exist under repo public/windows/servercore by az acr repository show-manifests --name OnePubTestAcrDev --repository public/windows/servercore. It return me null. Then I rerun docker push with the same images. The acr task still not trigger. I am curious where the webhook add in the layers and how can I trigger acrTask by push same images? There is no way? Another question is if the acrTask trigger by manifest update. If I retag the images and push to diff repo in same registry. The acrTask hook the new tag layer will or not updated? I think not right? Since the manifest actually not change. BestKui   Sent from Mail for Windows 10 From: Bin DuSent: Tuesday, April 14, 2020 6:47 PMTo: Azure/acrCc: Kui Wen; MentionSubject: Re: [Azure/acr] ACRTask do not trigger properly when I delete the digest of images and publish again (#373) @kuwe1990 in your second push, was onepubtestacrdev.azurecr.io/public/windows/servercore:1903 changed from first push? if not, it wouldn't trigger a new run. Base image trigger monitor the manifest change of the tag and trigger the run if it detects a change. /cc: @jaysterp @djyou—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by northtyphoon** [comment]
@kuwe1990 If you re-push the same image, it won't trigger the task. What is your ultimate purpose? Is it to test something? If you just want to rerun the task, you can do `az acr task run -r myregistry -n mytask`.
Tasks tracks the manifest change of the tag used in your Dockerfile.

**Comment by kuwe1990** [comment]
Yeah, it just test purpose. I know it can trigger by az acr task run. The main purpose is I want to understand how the hook added and why after I remove the manifest. It still not trigger properly. BestKui Sent from Mail for Windows 10 From: Bin DuSent: Tuesday, April 14, 2020 11:06 PMTo: Azure/acrCc: Kui Wen; MentionSubject: Re: [Azure/acr] ACRTask do not trigger properly when I delete the digest of images and publish again (#373) @kuwe1990 If you re-push the same image, it won't trigger the task. What is your ultimate purpose? Is it to test something? If you just want to rerun the task, you can do az acr task run -r myregistry -n mytask.Tasks tracks the manifest change of the tag used in your Dockerfile.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kuwe1990** [comment]
Yeah, it just test purpose. I know it can trigger by az acr task run. The main purpose is I want to understand how the hook added and why after I remove the manifest. It still not trigger properly

**Comment by northtyphoon** [comment]
Discussed with @kuwu1990, Tasks base image update trigger doesn't support "delete and re-push the same image".
