### ISSUE TITLE
Private link for Azure Container Registry

### ISSUE THREAD

**Issue by mangalorereshmi** [Azure/acr#376]
Configure Azure Private Link for an Azure container registry. See documentation here: https://aka.ms/acr/privatelink

**Comment by SteveLasker** [comment]
Closed as we've moved to GA. I've retitled to reflect GA state on the board.

**Comment by mxrss2** [comment]
Does ACR private link support acr build? I can not seem to get it to work when i set the acr registry to private.

**Comment by SteveLasker** [comment]
http://aka.ms/acr/tasks/agentpool supports private link. Is an early preview, so your feedback is appreciated
