### ISSUE TITLE
Remove the unnecessary `export` in the example shell scripts

### ISSUE THREAD

**Issue by Wwwsylvia** [Azure/acr#392]
**What is the problem you're trying to solve**
There are some unnecessary `export` in the example shell scripts in [AAD-OAuth.md](https://github.com/Azure/acr/blob/master/docs/AAD-OAuth.md)

**Describe the solution you'd like**
Remove the unnecessary `export` 

**Additional context**
The script is like below:
```bash
export registry="contosoregistry.azurecr.io"
export acr_username="00000000-0000-0000-0000-000000000000"
export acr_refresh_token="eyJ...L7a"
docker login -u "$acr_username" -p "$acr_refresh_token" $registry
```

**Comment by djyou** [comment]
@Wwwsylvia Can this issue be closed?

**Comment by shizhMSFT** [comment]
@djyou This is a new issue. #389 does not fix this issue but introduced this issue.
