### ISSUE TITLE
LibGit2Sharp update dockerfile and acrTask trigger twice

### ISSUE THREAD

**Issue by kuwe1990** [Azure/acr#398]
Hi
There is another issue I found recently. I am not sure it is a bug in my side or it because there is some issue in acrTask side.

I recently use libgit2Sharp library to trigger dockerfile update in github automatically. The acrTask trigger successfully. But it trigger twice even the automation update just submit one commit. If I update dockerfile manually. The acrTask will just trigger once which is correct. 

The registry I am testing is OnePubTestAcrPPE.

There are 3 test acrTask.
You can see the acrTask history:
RunId ccf, cce, ccd/ccc ccb cca has been triggered by automatically dockerfile update. It trigger twice.

For runid cc9 cc8 cc7, it trigger by me manually. It just trigger once successfully.

I am not sure where I can find the log in acr portal. Can you help me check why the acrTask do not trigger properly?

**Comment by mnltejaswini** [comment]
@kuwe1990  We received two separate push events from GitHub corresponding to the update
ccf, cce, ccd are the runs that are scheduled for the 3 tasks Test1, 2, 3 with empty commit Id on the repository https://github.com/upscontent/TestRepository 
ccc ccb cca are the runs that are scheduled for the 3 tasks Test1, 2, 3 for the commit Id 3759366600ee08c9afe654786aa4be648174c510 
Can you please provide some information on how did you make the update? Was a new branch pushed to the repository and as per https://github.com/gogs/gogs/pull/5508 there will be a push event .

**Comment by mnltejaswini** [comment]
Upon looking at the webhook payloads for the two commits, one seems to be redundant as it has distinct flag as false and the commits array is empty. Still looking to cases as to why this can happen, but from Task side, we can ignore the webhooks that that has empty commit array and distinct flag as false.

**Comment by northtyphoon** [comment]
The fix has been rolled out.
