### ISSUE TITLE
az acr task run: Unable to find image 'acr:latest' locally error

### ISSUE THREAD

**Issue by GersonDias** [Azure/acr#400]
**Describe the bug**
I'm trying to follow the guide https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auto-purge but when running the task, I'm receiving `Unable to find image 'acr:latest' locally` message.

**To Reproduce**
```
az acr task create --name purgeTask --cmd $purge_cmd --schedule "0 0 * * *" --registry <registry> --context /dev/null
$purge_cmd = "acr purge --filter '<repo>:.*' --filter '<repo>:.*' --filter '<repo>:.*' --filter '<repo>:.*' --filter '<repo>:.*' --ago 28d --dry-run"
az acr task create --name purgeTask --cmd $purge_cmd --schedule "0 0 * * *" --registry <registry> --context /dev/null
az acr task run --name purgeTask --registry <registry> 
```

**Expected behavior**
Should purge the repo's content.

**Any relevant environment information**
 - OS: Win10 (v2004)
 - Azure CLI: 2.0.69
 - Datetime (UTC): 2020/05/05 13:23:43 
 - registry: rhodium24uat.azurecr.io

**Additional context**

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by Quim78** [comment]
Hi,

I got same error. I'm following the same guide (https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auto-purge#run-in-a-scheduled-task).

**Comment by northtyphoon** [comment]
CLI 2.0.69 is an old version. Can you upgrade CLI to the latest and then update or recreate the task?

**Comment by northtyphoon** [comment]
@GersonDias @Quim78 did you get a chance to try the latest CLI?

**Comment by androuser123** [comment]
issue still exists

**Comment by northtyphoon** [comment]
@androuser123  thanks for the confirm.
