### ISSUE TITLE
Container Registry Port

### ISSUE THREAD

**Issue by nidiculageorge** [Azure/acr#402]
Hi Team,

Is there any port in which the Azure Container Registry needs to be accessed ,as when we have to specify in Nsg.Which Port do we have to mention

**Comment by SteveLas** [comment]
Please see https://aka.ms/acr/dedicated-data-endpoints

**Comment by nidiculageorge** [comment]
I have gone through the link, is there any particular port

**Comment by SteveLasker** [comment]
Good point. I overlooked this detail. Port 443 is the only port required to deliver REST manifest delivery over the registry endpoint, as well as content delivery over the data endpoints.
@dlepow to add this clarification to our docs.
