### ISSUE TITLE
Cannot login to Azure Container Registry using username and password from Azure portal

### ISSUE THREAD

**Issue by gro1m** [Azure/acr#404]
**Describe the bug**
Cannot login to Azure Container Registry providing username and password given in Azure portal.

**To Reproduce**
1. Defined proxy variables in PowerShell: 
```powershell
$Env:HTTP_PROXY="http://<username>:<password>@<company_domain>:80"
$Env:HTTPS_PROXY="http://<username>:<password>@<company_domain>:80"
$Env:REQUESTS_CA_BUNDLE=<path_to_companies_certifacte>
```
2. 
```powershell
az acr check-health -n myregistry --yes
```
Output seems to be o.k.:
```powershell
Docker daemon status: available
Docker version: Docker version 18.09.2, build 6247962
Docker pull of 'mcr.microsoft.com/mcr/hello-world:latest' : OK
Azure CLI version: 2.3.1
DNS lookup to myregistry.azurecr.io at IP <blanked> : OK
Challenge endpoint https://myregistry.azurecr.io/v2/ : OK
Fetch refresh token for registry 'myregistry.azurecr.io' : OK
Fetch access token for registry 'myregistry.azurecr.io' : OK
Helm version: 3.2.1
Notary version: 0.6.0
```
3. 
```powershell
az acr login -n myregistry --username myregistry --password <password copied from Azure portal> --debug
```
Snippet from output:
```powershell
urllib3.connectionpool : Starting new HTTPS connection (1): myregistry.azurecr.io:443
urllib3.connectionpool : https://myregistry.azurecr.io:443 "GET /v2/ HTTP/1.1" 401 149
Error response from daemon: Get https://myregistry.azurecr.io/v2/: authenticationrequired
cli.azure.cli.core.util : Login failed.
Login failed.
az_command_data_logger : exit code: 1
telemetry.save : Save telemetry record of length 2494 in cache
```

**Expected behavior**
Login Succeeded after last command.

**Screenshots**
Not applicable

**Any relevant environment information**
 - OS:
OsName : Microsoft Windows 10 Enterprise
OsType : WINNT
OsOperatingSystemSKU  : EnterpriseEdition
OsVersion  : 10.0.18363
 - Azure CLI/PowerShell/SDK version:
```powershell
PS az version
This command is in preview. It may be changed/removed in a future release.
{
  "azure-cli": "2.3.1",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.3.1",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}
}
```
 - Docker version:
`powershell Docker version 18.09.2, build 6247962`
 - Datetime (UTC) when the issue occurred:
today couple of times
 - Registry and image names

**Comment by yugangw-msft** [comment]
@gro1m, assume you are using admin account, can you please cross check whether the docker command works or not?
`docker login myregistry.azurecr.io -u myregistry -p <password copied from Azure portal>`

**Comment by gro1m** [comment]
@yugangw-msft 
Thank you very much for your informative reply. I could solve the problem with the command you posted: The docker login gave the error addressed here: https://github.com/docker/for-win/issues/1534.
Using the solution by @sumitdubey022229:
```
Following Configure Docker Proxy in following format
http://username:password@proxy-server:proxy-port for http proxy
replace http by https for https proxy..
```
solved the issue.

**Comment by gro1m** [comment]
Problem solved by adding username and password to the docker proxy settings
