### ISSUE TITLE
The provided location 'francecentral' is not available for resource type

### ISSUE THREAD

**Issue by eliassal** [Azure/acr#406]
**Describe the bug**
I am following instructions at 
https://docs.microsoft.com/en-gb/azure/container-registry/container-registry-tutorial-quick-task
 When I issue the following command on a resource group in France Central Region

`az container create ............`

I get

> The provided location 'francecentral' is not available for resource type 'Microsoft.ContainerInstance/containerGroups'. List of available regions for the resource type is 
> 'westcentralus,westus,eastus,westeurope,westus2,northeurope,southeastasia,eastus2,centralus,australiaeast,uksouth,southcentralus,centralindia,brazilsouth,southindia,northcentralus,eastasia,canadacentral,japaneast,koreacentral'.

**Screenshots**
![Release_009](https://user-images.githubusercontent.com/8447864/82831393-9b9ab580-9eb8-11ea-8323-ac0f180b9193.jpg)

Is it normal?

**Any relevant environment information**
 - Azure Shell/ Bash
 - 5/25/2020, 6:26 PM GMT+2
 - Registry = sierac.azurecr.io
 image names = helloacrtasks:v1

**Additional context**

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by adewaleo** [comment]
@eliassal thanks for reaching out. This is an issue with azure container instances, not azure container registry. Could you raise a support ticket / request with azure container instances?

I will also move your issue to the azure cli repo. All azure teams contribute to the CLI through that repo, so it can be a good way to give visibility to this issue.

**Comment by adewaleo** [comment]
Hmm for some reason I can't transfer this issue. Could you please open an issue at https://github.com/Azure/azure-cli

**Comment by yugangw-msft** [comment]
Not ACR issue
