### ISSUE TITLE
Getting a refresh/access token from an AAD service principal

### ISSUE THREAD

**Issue by AdallomRoy** [Azure/acr#408]
Is it possible? Currently the documentation only states how to get an ACR refresh token from a AAD refresh/access token which do not exist when authenticating with a service principal. So how do you exchange service principal credentials to an ACR refresh token? Either it's undocumented, or it's a feature request. Thanks!

**Comment by AdallomRoy** [comment]
Thanks - I was able to make this work using the "access_token" grant_type instead of the "access_token_refresh_token" one! Anyhow, I think it could have been simpler if it was documented better :-) Thanks

**Comment by sajayantony** [comment]
+ @dlepow

**Comment by sajayantony** [comment]
Closing this item since there is no action item at this point.
