### ISSUE TITLE
Allow public pull for images in Azure container registry

### ISSUE THREAD

**Issue by karrtikr** [Azure/acr#409]
**What is the problem you're trying to solve**
Allow users to configure images inside ACR, so they can be pulled publicly with `docker pull` without any authentication. Basically allow read-only anonymous access to images in ACR.

**Additional context**
We would like to run test job in our CI pipelines inside containers from ACR, particular in Github actions. But it only supports to run jobs inside public images, which do not require any authentication.

To continue using ACR, I need to configure those images so they're available for public docker pull, so that I can just use it as if they're hosted on docker hub instead.

I am willing to switch tiers if this is a preview feature and that's necessary. Please advise.

**Comment by Wwwsylvia** [comment]
@yugangw-msft Do we have any thoughts on this?

**Comment by sajayantony** [comment]
I think we need a public doc on how to sign up for this.

**Comment by karrtikr** [comment]
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-faq#how-do-i-enable-anonymous-pull-access

I think this is the public doc you maybe referring to. I was successfully able to open up a support ticket and get this resolved.

**Comment by tomkerkhove** [comment]
I have been using this for almost a year now as well

**Comment by yugangw-msft** [comment]
closing as we have doc on this already

**Comment by microsoft-sampsa** [comment]
will do this as well, since its the only way to use custom docker container registries with cluster runs (i.e. authentication is impossible)
