### ISSUE TITLE
Allows Access Control to enable access to ACR

### ISSUE THREAD

**Issue by ramondeklein** [Azure/acr#41]
We currently use the admin user to be able to push/pull images from ACR. We would rather authorize with the AAD, so you could do something like this:

    docker login myacs.azurecr.io -u john.doe@example.com -p /o=w0SV+tL+f0GiiF=xd+UPQDINYeNPX

Via IAM this user is assigned contributor access, so it can push/pull images from the repository.

**Comment by SajayAntony** [comment]
Current solution only enables IAM users which are [service principals](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication). 
For AAD, #32 is what is currently being worked on and login will be supported through the CLI

**Comment by erichexter** [comment]
I am not sure what the value of #32 is.  The ability to use AAD credentials to pull images from a registry seems like a entry level requirement. Without this, the overhead of creating service principals for every user that needs individual access controls is crazy.  At DockerCon, I was told this feature was being worked on.

**Comment by SajayAntony** [comment]
@erichexter - #32 will enable to use IAM with AAD users on a registry users. Currently ACR is based on Basic auth. With the AAD implementation, we will integrate the device login scenario which should enable AAD users to be assigned to the registry resource and perform pull/push depending on the IAM permissions for that user on the registry. 
Service Principals are managed with AAD and do not require 2FA and hence can be used in a non-interactive flow and is clearly targeting a headless scenario where as user login as you pointed out should be AAD. With AAD and 2FA the token flow is different and as per Dockers recommendation we will have to make this an oauth model and hence a change to ACR on the service side + client side is required.

**Comment by SajayAntony** [comment]
Managed registries are now in preview. We should be able to open issues under that for AAD. 
Registries with your own storage account will be provided an option to migrate up before Managed registries goes GA.
