### ISSUE TITLE
Increase the limit for Webhooks in ACR 

### ISSUE THREAD

**Issue by epomatti** [Azure/acr#410]
The limits for webhooks, for both Basic and Standard service tiers, seem to be very low and do not scale well with the increase in price.

Why would the _amount_ of webhooks, and not storage or the actual hook calls, influence the costs? 

Current prices:

- Basic $5 = 2 Webhooks
- Standard $20 = 10 Webhooks
- Premium $50 = 500 Webhooks

[ACR Service Limits](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-skus#service-tier-features-and-limits)

I would suggest at minimum that it should scale based on the Premium, 5, 20 and 500 webhooks. But that's still seems low.

Here is a model proposal: If we can create hundreds of images in ACR with the Basic SKU, then it would be fair to create hundreds of webhooks as well. The computational costs of the webhooks, which are negligible, could be added in some other way to the price or quotas.

Can we have a discussion about why the Basic and Standard limits for Webhooks are so low? I would like to understand why the amount of webhooks, and not the actual calls/processing, have influence in the price.

I have opened a [user voice](https://feedback.azure.com/forums/903958-azure-container-registry/suggestions/40569829-increase-the-limit-for-webhooks-in-acr) but I assume this is a better channel for the community.

**Comment by Wwwsylvia** [comment]
@yugangw-msft

**Comment by yugangw-msft** [comment]
@SteveLas, please comment

**Comment by SteveLasker** [comment]
Hi @epomatti, thanks for the feedback, and uservoice is actually the best place for new or expanded capabilities for existing features. We try to use this issues list for bugs/issues in current features. But, I do see your point "_the current limit is an issue_". Thank you for the uservoice entry so we can comment there. 
@mangalorereshmi is working on a new consumption tier that this would align with.

**Comment by epomatti** [comment]
Thanks @SteveLasker and @mangalorereshmi for the response.

I closed this issue and will be waiting for the response back on User Voice [40569829](https://feedback.azure.com/forums/903958-azure-container-registry/suggestions/40569829-increase-the-limit-for-webhooks-in-acr).
