### ISSUE TITLE
PowerShell commandlets for ACR

### ISSUE THREAD

**Issue by ramondeklein** [Azure/acr#42]
It seems that ACR can only be managed via AZ CLI 2.0, but almost all other services also have Powershell cmdlets. We have completely standardized on PowerShell, but we need to install AZ CLI 2.0 to deal with ACR.

**Comment by SajayAntony** [comment]
These are already available - Azure/azure-powershell#3782

Please update your Powershell commands as described [here](https://docs.microsoft.com/en-us/powershell/azure/install-azurerm-ps?view=azurermps-4.0.0).

![image](https://cloud.githubusercontent.com/assets/1821104/26267011/d404b244-3c9c-11e7-83c2-e001f93505b8.png)
