### ISSUE TITLE
ACR Docker Images Delete API

### ISSUE THREAD

**Issue by rajivml** [Azure/acr#421]
HI,

I couldn't find any API to programatically delete an Image from ACR , I do see an API for deleting the entire container registry but it doesn't accept any parameters like imageName and imageTag

https://docs.microsoft.com/en-us/rest/api/containerregistry/registries/delete

Can you please throw some light on this, we are porting an SaaS based application from GCP to Azure and we have dependency on image delete API where GCP does support it based on authentication tokens and we have a service running in production on GCP leveraging this functionality.

**Comment by SteveLasker** [comment]
Hi @rajivml
Welcome to Azure. Here’s some apis that should help

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-delete
and
http://aka.ms/acr/auto-purge
Steve

**Comment by rajivml** [comment]
Thanks @SteveLas , I have just now realized that the image is called as an repository earlier I was looking at a wrong place, found the rest API as well https://docs.microsoft.com/en-us/rest/api/containerregistry/repository/delete 

I will try it out

**Comment by rajivml** [comment]
@SteveLas I tried to delete the repository via curl, but am getting "Unsupported Request" error,

<HTML><HEAD>
<TITLE>Unsupported Request</TITLE>
</HEAD><BODY>
<H1>Unsupported Request</H1>
DELETE to http&#58;&#47;&#47;docs&#46;microsoft&#46;com&#47;en&#45;us&#47;rest&#47;api&#47;containerregistry&#47;repository&#47;xxxxxxx&#46;azurecr&#46;io&#47;acr&#47;v1&#47;host&#37;2Fe0a24b06&#95;1bd4&#95;4ae9&#95;9b11&#95;c804443cdb3c&#37;2Firiswithtrain not supported.<P>
Reference&#32;&#35;8&#46;26d70b17&#46;1593848550&#46;78d3422
</BODY></HTML>

**Comment by rajivml** [comment]
![image](https://user-images.githubusercontent.com/46923567/86517644-1fe14080-be48-11ea-9101-c1642b17fc98.png)

The doc say's it's preview, is this the reason it's not working and also the example that was given was using an test ecr point, so I doubt it works in prod, can you please check and confirm

**Comment by SteveLas** [comment]
Sorry, but most folks that would normally reply here are taking a much needed break. We do have live-site support folks on call. If you'd like a response over the US holiday weekend, please open a ticket here: https://aka.ms/acr/support/create-ticket
As for preview, we support all preview APIs, although, I didn't think this one was in preview, but I'm just looking quickly as I head out for a hike. 
Steve

**Comment by rajivml** [comment]
no issues, you can reply over a weekday, I still have sometime to implement it, happy hiking !!

**Comment by rajivml** [comment]
HI, can you guys give me an sample rest/curl call on how to delete an image based on it's tag

**Comment by SteveLasker** [comment]
@yugangw-msft can you help here?

**Comment by SteveLas** [comment]
@rajivml, the team is really busy, so trying to contact individuals can be a challenge. Do you mind opening a support ticket, so we can make sure you get the timely help you need from one of the on-call folks: https://aka.ms/acr/support/create-ticket

**Comment by rajivml** [comment]
hm, I would have done that but I don't have access to our azure support portal, I need to catch hold of some IT guy to create one on behalf of me. But it's pretty surprising that even contributors are not able to point me to the right documentation for an public API

**Comment by rajivml** [comment]
@sajayantony @shizhMSFT Hey guys , my use case is to delete an image from ACR based on tags, but I couldn't find any examples on how to delete the same programatically i.e via Rest API  and I have been blocked from a couple of weeks on this and I don't have permission to create support tickets via portal.azure so that's why am relying on this medium/channel

Can you please share an sample curl/postman request on how to get an access token which has delete access and an sample curl request on how to delete the image from ACR.  Thanks

https://github.com/Azure/acr/blob/master/docs/Token-BasicAuth.md

**Comment by rajivml** [comment]
```
Delete Based on Manifest:

export scope="repository:host/xxxxx/iriswithtrain:delete"
curl -v -H "Authorization: Basic $acr_credential" "https://$registry/oauth2/token?service=$registry&scope=$scope"

export acr_access_token="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

curl -v -X DELETE -H "Authorization: Bearer $acr_access_token" https://$registry/v2/host/e0a24b06_1bd4_4ae9_9b11_c804443cdb3c/iriswithtrain/manifests/sha256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxx

*  SSL certificate verify ok.
> DELETE /v2/host/xxxxxxxxxxxxxxxxxxxx/iriswithtrain/manifests/sha256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx HTTP/1.1
> Host: xxxxxx.azurecr.io
> User-Agent: curl/7.68.0
> Accept: */*
> Authorization: Bearer xxxxxxx.xxx.xxxxx
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 202 Accepted
< Server: openresty
< Date: Sat, 11 Jul 2020 14:31:06 GMT
< Content-Length: 0
< Connection: keep-alive
< Access-Control-Expose-Headers: Docker-Content-Digest
< Access-Control-Expose-Headers: WWW-Authenticate
< Access-Control-Expose-Headers: Link
< Access-Control-Expose-Headers: X-Ms-Correlation-Request-Id
< Docker-Distribution-Api-Version: registry/2.0
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-Content-Type-Options: nosniff
< X-Ms-Client-Request-Id:
< X-Ms-Correlation-Request-Id: 40640d46-c6a6-4384-986a-d8430051f5b6
< X-Ms-Request-Id: 9e29afde-764d-462a-a184-4dcfd3902ed9
< Strict-Transport-Security: max-age=31536000; includeSubDomains
<
* Connection #0 to host aifabric.azurecr.io left intact
```

I have tried this and the API responds that request has been accepted and it's an hour and the image still exists and I can pull the image as well , any idea on why it didn't get deleted, if the permissions are missing then that would have been verified at the time of token validation itself so I think that's not the reason

**Comment by rajivml** [comment]
looks like I have to pass this digest which is highlighted in yellow as input for the delete call instead of the digest that is returned by the get manifests call i.e the one under config 

{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
    "mediaType": "application/vnd.docker.container.image.v1+json",
    "size": 11850,
    "digest": "**sha256:xxxxxx**"
  },
  "layers": [
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 45344292,
      "digest": "sha256:xxxxxxxxxxxxxxxxxxxxxxx"
    }
  ]
}

![image](https://user-images.githubusercontent.com/46923567/87227952-b0c19a00-c3bb-11ea-90d1-b3b9396801d5.png)

Now 2 more questions,

1) How do I get this sha256 digest which is highlighted in yellow in the screenshot because the get manifest calls doesn't have this info
2) Once the image is deleted, the repository isn't getting deleted, do u guys have an API to delete the empty repository as well

**Comment by SteveLasker** [comment]
apologies for the delay. We’re tracking down someone to assist.

**Comment by rajivml** [comment]
okay got it, we have to make a head request to fetch the docker digest which I have highlighted in yellow earlier , please get all these documented 

rajivchodisetti@DESKTOP-LOUPTI1:/mnt/c/Users/rajiv.chodisetti/Desktop$ curl -I HEAD -H "Accept: application/vnd.docker.distribution.manifest.v2+json" -H "Authorization: Bearer $acr_access_token" "https://$registry/v2/$image/manifests/1"
curl: (6) Could not resolve host: HEAD
HTTP/1.1 200 OK
Server: openresty
Date: Sat, 11 Jul 2020 18:34:25 GMT
Content-Type: application/vnd.docker.distribution.manifest.v2+json
Content-Length: 5348
Connection: keep-alive
Access-Control-Expose-Headers: Docker-Content-Digest
Access-Control-Expose-Headers: WWW-Authenticate
Access-Control-Expose-Headers: Link
Access-Control-Expose-Headers: X-Ms-Correlation-Request-Id
Docker-Content-Digest: sha256:d5c195e299936d3ffefa80a082e36d0592c913f9bd5b85ea9354b6ae2b7d9856
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:d5c195e299936d3ffefa80a082e36d0592c913f9bd5b85ea9354b6ae2b7d9856"
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Client-Request-Id:
X-Ms-Correlation-Request-Id: 85e7de14-8ed6-4f28-9138-8af46b4e6a4e
X-Ms-Request-Id: 8e1b26cd-fede-4675-bf9f-9fb030410310
Strict-Transport-Security: max-age=31536000; includeSubDomains

**Comment by rajivml** [comment]
you can close this issue, I have got my issues resolved, the documentation can be improved a lot, the term image and repository are being interchanged at multiple places and the examples are also not well documented

after going through all these 3 pages & after some trial & error, I was able to figure out it's working, 

https://docs.docker.com/registry/spec/api/#listing-image-tags
https://github.com/Azure/acr/blob/master/docs/AAD-OAuth.md
https://github.com/Azure/acr/blob/master/docs/Token-BasicAuth.md

**Comment by northtyphoon** [comment]
@rajivml First I want to apologize for the delayed response. The team was very busy in the last few weeks.

Before I explain how the delete API works, I want to clarify a little bit about the concepts of registry, repository, tag, manifest and image. For detail explanation, I recommend you read @SteveLasker 's blog post [registry-namespace-repo-names](https://stevelasker.blog/2020/02/17/registry-namespace-repo-names/)

In a registry (eg, myregistry.azurecr.io), you can have **multiple** repositories and the repository name may use '/' to form a hierarchy (eg, foo, foo/bar). In a repository (eg, foo/bar), you can have **multiple** images, each image is uniquely identified by its manifest digest (eg, sha256:046f87b6191999281f0d3c2665714df00c9b7fb596a1e483e0bad58853450fc6). Each manifest can be associated with multiple tags (eg, latest, tag1) or no tag at all. However, each tag can only be associated with one manifest.

- To delete an image and all associated tags, you need to use [Registry V2 API](https://docs.docker.com/registry/spec/api/#detail) (it's fully supported by ACR).

DELETE | /v2/<name>/manifests/<reference> | Manifest | Delete the manifest identified by name and reference. Note that a manifest can only be deleted by digest.
-- | -- | -- | --

For example,

DELETE https://myregistry.azurecr.io/v2/foo/bar/manifests/sha256:046f87b6191999281f0d3c2665714df00c9b7fb596a1e483e0bad58853450fc6

- To delete all images in a repository, ACR provides a single [delete API](https://docs.microsoft.com/en-us/rest/api/containerregistry/repository/delete) 

DELETE {url}/acr/v1/{name}

Name | In | Required | Type | Description
-- | -- | -- | -- | --
name | path | True | string | Name of the image (including the namespace)
url | path | True | string | Registry login URL

For example,

DELETE https://myregistry.azurecr.io/acr/v1/foo/bar

**Comment by northtyphoon** [comment]
If you want to fiddler with the API in the future, I would suggest use Azure CLI `az acr` commands. We provide full support and better samples for `az acr` commands. With `--debug` command, you can inspect the detail http requests, for example, 

```
az acr repository show-manifest -n myregistry --repository foo/bar --debug
az acr repository delete -n myregistry -t foo/bar@sha256:046f87b6191999281f0d3c2665714df00c9b7fb596a1e483e0bad58853450fc6 --debug
```

**Comment by rajivml** [comment]
Thanks @northtyphoon , no worries and I appreciate your detailed response on this topic, I am sorted for now
