### ISSUE TITLE
Unable to find manifest digest when importing from Nexus Docker

### ISSUE THREAD

**Issue by wagnst** [Azure/acr#422]
**Describe the bug**
I am trying to import docker image via `az acr import` from Nexus Docker Repo, but I get `Unable to find manifest digest`:

```bash
Deployment failed. Correlation ID: e8a839fd-d26e-408f-9709-1f4ec06fdb72. Operation registries-00f591ef-c113-11ea-a28f-5b5ddd7f2924 failed. Resource /subscriptions/***/resourceGroups/***/providers/Microsoft.ContainerRegistry/registries/*** Unable to find manifest digest  Repo: someurl.com/lido/sms Tag: 1.0.0 Manifest: 
```
The manifests are there according to nexus interface:
![image](https://user-images.githubusercontent.com/7312523/86917125-e6992100-c124-11ea-85ab-3efbe67d4a27.png)

Pulling the image via docker directly works fiine:

```
docker pull someurl.com/lido/sms:1.0.0
1.0.0: Pulling from lido/sms
75a822cd7888: Downloading [==========>                                        ]  10.32MB/51.36MB
[...]
```

**To Reproduce**
1. Run Nexus and push docker image
2. Create Premium ACR
3. Login to ACR and docker
4. execute:
```bash
az acr import --name *** --source someurl.com/lido/sms:1.0.0 --image sms:1.0.0 --username *** --password ***
```

**Expected behavior**
Image from nexus docker is successfully imported.

**Any relevant environment information**
 - Nexus OSS 3.15.2-01
 - Azure CLI/PowerShell/SDK version 2.8.0
 - Docker version 19.03.6

**Additional context**

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by yugangw-msft** [comment]
@wagnst, sorry for the delay. The error at back-end showed tag of "1.0.0-202001131056" not found, could you double check?

**Comment by yugangw-msft** [comment]
Closing due to no response.
