### ISSUE TITLE
Understand Difference Between Repository & Image

### ISSUE THREAD

**Issue by rajivml** [Azure/acr#423]
HI,

I was going through this doc and I want to understand the difference between Repositority and an Image in the context of ACR, because I don't see any such thing called as Image on ACR UI, afaik repositories are nothing but images in ACR. 

https://github.com/Azure/acr/blob/master/docs/AAD-OAuth.md#calling-post-oauth2token-to-get-an-acr-access-token

By substituting repository name to image variable, I tried to fetch the tags, but am getting unAuthorized error, can someone throw some light on this or help me understand the difference between repository and an image by taking an example.

**Comment by rajivml** [comment]
```
export registry="myrepo.azurecr.io"
image="dave-225414/trainer"  --repository Name
scope="registry:catalog:*"  
curl -v -H "Authorization: Basic $acr_credential" "https://$registry/oauth2/token?service=$registry&scope=$scope"
export acr_access_token="xxxxx"
curl -v -H "Authorization: Bearer $acr_access_token" "https://$registry/v2/$image/tags/list"

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required, visit https://aka.ms/acr/authorization for more information.","detail":[{"Type":"repository","Name":"dave-225414/ai-trainer","Action":"metadata_read"}]}]}
* Connection #0 to host aifabric.azurecr.io left intact
```

This is what I tried,

**Comment by rajivml** [comment]
you can close this, I have figured out that image is nothing but a repository in acr , it's just that you guys were interchanging these words in the documentation leading to confusion

And regarding scope, to list the tags, I tried with this `export scope="repository:$image:*"` and am able to list it now, but anyhow if you can let me know the exact scope needed for listing that would be great, you can close this issue

**Comment by yugangw-msft** [comment]
closing. thanks
