### ISSUE TITLE
How to copy images from one azure container registry to another container registry in different tenant

### ISSUE THREAD

**Issue by nidiculageorge** [Azure/acr#426]
Hi Team,

I have a container registry in one subscription and and another container registry in another subscription. Both are under different tenant ID.

Is it possible to copy images between container registry using az commands. Please let me know the commands

**Comment by hkuadithya** [comment]
@nidiculageorge 
Thanks for reaching out. This feature is already available using [az acr import](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-import-images) command. 

As long as you have the access keys credentials of the source container registry, it doesn't matter what tenant it belongs to.

**Example:**
```
az acr import \
  --name <destinationRegistry> \
  --source <sourceRegistry>.azurecr.io/<Image:Tag> \
  --username <SourceRegUserName> \
  –-password <SourceRegPassword>
```

Please note that with this command, you can:-
* Import from a public registry such as DockerHub
* Import from another ACR, in the same or a different subscription or tenant
* Import from a non-Azure private container registry such as ECR or GCR

**Comment by nidiculageorge** [comment]
@hkuadithya Great thanks for the response,should we specify the password in single quotes '',as we are running from powershell integrated vs code

**Comment by nidiculageorge** [comment]
@hkuadithya 

Getting the below eerror

az: error: unrecognized arguments: –-password xxxxxxxxxxxxxxxxxxxxxxx

**Comment by hkuadithya** [comment]
@nidiculageorge It should be `--password` not `–-password`. Looks like you entered a wrong unicode character (notice how it's bigger than the regular dash).

As for powershell, you can store these parameters in a variable and run.
Use backticks ` for multiline commands on Powershell. Use backslash \ for Bash.

**Example (Powershell):**
```
$source="...";
$destination="...";
$imageTag="library/redis:latest";
$username="...";
$password="...";

az acr login -n $destination

az acr import `
   --name $destination `
   --source "$source.azurecr.io/$imageTag" `
   --username $username `
   --password $password
```

**Comment by nidiculageorge** [comment]
@hkuadithya will try and let know the .Thanks

**Comment by k-byun** [comment]
works for me

**Comment by k-byun** [comment]
@Mohid-A : You need to import one by one.  But you can build a quick script to iterate over all the images as well if you want to automate.

**Comment by Mohid-A** [comment]
Thank you. I am also interested to know if import supports the options "--top" and  "--orderby time_desc" , for instance, to import the recent 10 tags from the repo. This will be useful if migrating a repo with high number of tags.

**Comment by Mohid-A** [comment]
I am currently working on it, i will update here otherwise

**Comment by ankurkhemani** [comment]
Solution to this is documented here: https://docs.microsoft.com/en-us/azure/container-registry/manual-regional-move
