### ISSUE TITLE
intermittent failures pushing build caches

### ISSUE THREAD

**Issue by nathana1** [Azure/acr#428]
First reported here:  https://github.com/moby/buildkit/issues/1550#issuecomment-659073476.  We have identified the issue and are investigating potential fixes.

I've noticed the same problem when pushing caches to Azure Container Registry--it throws a 400 Bad Request error (tested on Buildkit 0.6.2 and 0.7.1 with the option --export-cache type=registry,ref=$(params.image_repo)/$(params.image_name):buildcache with params substituted in by our CI system).

It happens intermittently, but often enough that we've had to switch to an alternate cache export for the time being due to the volume of "failed" builds due exclusively to the cache export. I don't have Azure-side logs to provide more diagnostic information yet, though.

**Comment by terencet-dev** [comment]
Closing as this has been inactive for over three months.
