### ISSUE TITLE
RBAC access to namespaces

### ISSUE THREAD

**Issue by deepakkhetwal** [Azure/acr#436]
**What is the problem you're trying to solve**
We are setting up multi tenant AKS cluster, each namespace owned by different team/tenant and require different privileges at namespcae level, it would be better if we have same namespace level RBAC control with in acr, which will align acr pull images permissions to aks namespace level permissions. Right now, we are looking to create separate acr for each team
**Describe the solution you'd like**
it would be better if we have same namespace level RBAC control with in acr, which will align acr pull images permissions to aks namespace level permissions. 

**Additional context**

**Comment by avtakkar** [comment]
Do repository scoped permissions help? https://docs.microsoft.com/en-us/azure/container-registry/container-registry-repository-scoped-permissions

**Comment by northtyphoon** [comment]
@deepakkhetwal, you may be able to leverage the "tokens and scope maps" feature to manage repository-scoped permissions. 

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-repository-scoped-permissions

Let's say `Team A` run their Pods in `Namespace A`. They need to access a few images in the registry like `registry.azurecr.io/repo1`, `registry.azurecr.io/repo2`. You can create a token with image pull permissions scoped to the two repositories. Using the token you can create a `docker-registry secret` in `Namespace A` and the deployments in `Namespace A` can use the secret as ImagePullSecret.

**Comment by avtakkar** [comment]
Hi @deepakkhetwal , just following up on this - let us know if the above feature works for you.

**Comment by shizhMSFT** [comment]
Closing this issue since it is over 1 month without any customer response.
