### ISSUE TITLE
Provisioning VM for custom domains hangs during script start

### ISSUE THREAD

**Issue by andershermansen** [Azure/acr#44]
I used the scripts and template in the custom-domain to set up a VM in Azure to forward traffic to ACR to have our own customer domain.

The running of the deployment template just seems to hang in this loop in deploy-nginx-docker.sh:
```
## Docker installation extension installs docker in the background
## So we cannot make assumption about its completion time
until docker-compose up
do
    sleep 10
done
```

I verified that by logging in to the VM and looking at running commands.

Everything else seems to be set up correctly.
After killing the stuck task I just ran `docker-compose up -d` and everything seems to run smoothly

**Comment by shhsu** [comment]
Sounds like, for some reason, docker extension somehow never got properly installed while the script was trying to call `docker-compose up` and that command never succeeded.

According to the extension project's help file we might be able to find some logs in these locations
* /var/log/azure-docker-extension-enable.log
* /var/log/waagent.log
* /var/log/azure/Microsoft.Azure.Extensions.DockerExtension/**/docker-extension.log

Could you share these files so we can look at what's wrong?

**Comment by andershermansen** [comment]
Attached is the logs asked for.

BUT. I deleted my original VM and set up a new one to try that. The new one is based on Ubuntu 16.04 instead. I did not investigate much, but the installation the not complete here also. I tried to run the deploy script multiple times, but deployment failed with error.

I ended up updating all packages, reinitialize docker (remove /var/lib/docker) and then using the docker compose and nginx config templates and just start it that way.

It is now working great, so I'm not willing to do any more testing of this issue, so you can close if you like.

[logs.zip](https://github.com/Azure/acr/files/1054060/logs.zip)

**Comment by SajayAntony** [comment]
@andershermansen   Thank you sharing the logs. I will follow up with @shhsu and see if its a VM extension issue or something else. 
I would like to keep the issue open for us to track until we have an understanding.

**Comment by SajayAntony** [comment]
Closing this and we can reopen incase we see this again.
