### ISSUE TITLE
Helm3 charts not listed in Azure portal when uploaded by ACR Transfer 

### ISSUE THREAD

**Issue by jaysterp** [Azure/acr#447]
**Describe the bug**
When using ACR Transfer to move a Helm 3 chart between two registries, the chart is not listed in the portal after being imported to the target registry. When the helm chart is initially pushed as an OCI artifact to the source registry using the Helm 3 client, it is visible in the portal.  However, after exporting the artifact to storage and and importing to the target registry, the helm chart is not listed in the portal under the target registry. `helm chart pull` confirms the artifact exists in the target registry.

**To Reproduce**

1. Create exportPipeline on the source registry.
[Create ExportPipeline](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-transfer-images#create-exportpipeline-with-resource-manager)

2. Push Helm chart using Helm3 client to source registry

`set HELM_EXPERIMENTAL_OCI=1`
[create sample hello-world chart](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos#create-a-sample-chart)
helm chart save . hello-world:v1
helm chart save . mycontainerregistry.azurecr.io/helm/hello-world:v1
helm chart push mycontainerregistry.azurecr.io/helm/hello-world:v1

(this chart shows in the portal under the source registry)

3. Use ACR Transfer to create pipelineRun to export `helm/hello-world:v1` from the source registry to storage.
[Create PipelineRun for export](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-transfer-images#create-pipelinerun-for-export-with-resource-manager)

4. Create importPipeline on the target registry with sourceTrigger enabled and `DeleteSourceBlobOnSuccess` option.
[Create ImportPipeline](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-transfer-images#create-importpipeline-with-resource-manager)

4. Copy blob to target storage container. Let the blob be imported automatically to the target registry (once the blob is deleted you know import happened). 

5. Go to portal to list repositories for the target registry.

6. `helm chart pull` to confirm chart exists in target registry.

**Expected behavior**
Helm3 chart should be listed in the portal under the target registry.

**Any relevant environment information**
Helm version: v3.3.0-rc.2

**Comment by terencet-dev** [comment]
Closing as this has been inactive for over three months.
