### ISSUE TITLE
Import image fails when parameter 'scope' is missing in source registry's auth challenge

### ISSUE THREAD

**Issue by avtakkar** [Azure/acr#449]
**Describe the bug**
Import requires a `scope` for bearer authentication. When the source registry's auth challenge does not include a `scope` parameter, it fails. `scope` should be optional.

**To Reproduce**
```shell
az acr import --name myregistry --source registry.redhat.io/openjdk/openjdk-11-rhel8:1.3   -u '--'  -p  '--' --image openjdk/openjdk-11-rhel8:1.3
```

**Expected behavior**
Successful image import.

**Actual behavior**
```
Invalid message Unauthorized Unauthorized {"errors":[{"code":"UNAUTHORIZED","message":"Access to the requested resource is not authorized"}]}
```

**Comment by terencet-dev** [comment]
Closing as this has been inactive for over three months.
