### ISSUE TITLE
Pulling images is very slow

### ISSUE THREAD

**Issue by adamaiken89** [Azure/acr#450]
**Describe the bug** (Or issue?)
We are using an image from container registry for CI running. And recently puling an image from azure container registry is extremely slow. The speed is around 40KB/s at max. Before that we could usually download the whole image in 1~2 minutes

**Expected behavior**
I have a 1GB image for CI and after 10 mins our CI didn't download the whole image.

**Any relevant environment information**
 - OS: [e.g. Ubuntu, Windows]
 - Azure CLI/PowerShell/SDK version
 - Docker version
 - Datetime (UTC) when the issue occurred
 - Registry and image names

**Additional context**

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by sajayantony** [comment]
@adamaiken89 would you please open a support ticket so that we can security engage since might require the engineer to investigate a particular resource.

**Comment by adamaiken89** [comment]
Noted.
