### ISSUE TITLE
Unable to update count in agent pool

### ISSUE THREAD

**Issue by dlepow** [Azure/acr#452]
After creating an agent pool I am unable to change the count in the pool using the CLI or portal

**To Reproduce**
1. Create an agent pool in supported region westus2 on premium registry:
```
az acr agentpool create     --name myagentpools3     --tier S3 --registry danlep0818
```
  Pool is created successfully.

2. Run `az acr agentpool update`, increasing or decreasing the count. Example:
```
az acr agentpool update     --name myagentpools3  --registry danlep0818 --count 0
```
3. CLI shows error message
```
Deployment failed. Correlation ID: bd30c430-f417-46bf-b306-7884c285b636. The status for Agent Pool myagentpools3 is Error. Error Message: The client 'xxx' with object id 'xxx' has permission to perform action 'Microsoft.Compute/virtualMachineScaleSets/write' on scope '/subscriptions/xxx/resourceGroups/ap-danlep0818-myagentpools3-9e8/providers/Microsoft.Compute/virtualMachineScaleSets/danlep0818-myagentpools3-9e8-0'; however, it does not have permission to perform action 'read' on the linked scope(s) '/subscriptions/xxxa/resourceGroups/task-custom-image-resource-group-prod/providers/Microsoft.Compute/galleries/taskImageGalleryProd/images/taskAgentImage/versions/latest' or the linked scope(s) are invalid.. Registry Resource Id: /subscriptions/xxx/resourceGroups/danlep0818/providers/Microsoft.ContainerRegistry/registries/danlep0818. 
```

**Expected behavior**
Pool count increases or decreases successfully

**Screenshots**
Also unable to update pool count in portal. Moving slider results in "Failed" state
![image](https://user-images.githubusercontent.com/2762013/90574444-c9b52c00-e16d-11ea-9b2d-d7419d273348.png)

**Any relevant environment information**
 - OS: macOS, Cloud Shell
 - Azure CLI 2.10.1
 - Datetime (UTC) when the issue occurred - approx Tue Aug 18 23:12:59 UTC 2020
 - Registry and image names - danlep0818

**Comment by northtyphoon** [comment]
@dlepow can you try it again?

**Comment by dlepow** [comment]
@northtyphoon - Thanks very much, works fine in CLI and portal. I'll go ahead and close issue.
