### ISSUE TITLE
az acr import unauthorized

### ISSUE THREAD

**Issue by hadr10** [Azure/acr#457]
**Describe the bug**
We are moving images from internet to ACR. We have got issue with 2 images which get unauthorized, for other images it works well. The same issue is for image 

az acr import --name xxxacr --source docker.io/nats:2.1.8 -t nats:2.1.8
Deployment failed. Correlation ID: d9eac6a3-d837-4e82-9b85-38e819c9daf5. Operation registries-2b82a968-f3f0-11ea-b928-d43b040c15bf failed. Resource /subscriptions/xxxxxxxxxxxxx/resourceGroups/xxxxxxx-infrastructure-rg/providers/Microsoft.ContainerRegistry/registries/xxxxxxxxxxxacr Invalid message Unauthorized Unauthorized {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"nats","Action":"pull"}]}]}

az acr import --name xxxacr --source docker.io/influxdb:alpine --image influxdb:alpine
Deployment failed. Correlation ID: b9609f01-bef8-4247-b3c8-3cfad3e2d815. Operation registries-901d0dd8-f3f1-11ea-826d-d43b040c15bf failed. Resource /subscriptions/xxxxxxxxxxxx/resourceGroups/xxxxxxx-infrastructure-rg/providers/Microsoft.ContainerRegistry/registries/xxxacr Invalid message Unauthorized Unauthorized {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"influxdb","Action":"pull"}]}]}

**To Reproduce**
1. az acr login -n xxxxxacr
Login Succeeded
2. PS C:\Git> az acr import --name xxxxxacr --source docker.io/nats:2.1.7 --image nats:2.1.7
Deployment failed. Correlation ID: fb3747a8-bf2e-4344-adfc-a59108c209e3. Operation registries-0bf64c02-f3f0-11ea-a56c-d43b040c15bf failed. Resource /subscriptions/xxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxxx-infrastructure-rg/providers/Microsoft.ContainerRegistry/registries/xxxxxxxxxxxacr Invalid message Unauthorized Unauthorized {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"nats","Action":"pull"}]}]}

**Expected behavior**
Successfull import from docker.io to ACR.

**Any relevant environment information**
 - OS: Windows 10
 - Azure CLI/PowerShell/SDK version: 2.9.1
 - Docker version: 19.03.12
 - Datetime (UTC) when the issue occurred: 11.9.2020 7:30
 - Registry and image names
docker.io/nats:2.1.8
docker.io/influxdb:alpine

**Comment by nathana1** [comment]
Docker hub images are in a repository called library so the following sources should work:
--source docker.io/library/nats:2.1.8
--source docker.io/library/influxdb:alpine

**Comment by hadr10** [comment]
it works not, thank you

**Comment by domenichelfenstein** [comment]
Strangely I get the same error when I try to import an image:
`az acr import --name <myRegName> --source docker.io/library/jsreport/jsreport:2.3.0-full`

What am I doing wrong?
(did a `az login` before)

**Comment by marcelcamporelli** [comment]
Note that the `library` folder is only for "official" images. Some images are managed by an organization and have their own subfolder, like `mailhog/mailhog`:

```
# working fine (mailhog managed)
az acr import --name brickwork --source docker.io/mailhog/mailhog --image mailhog/mailhog

# working fine (official docker image)
az acr import --name brickwork --source docker.io/library/postgres:16 --image postgres:16
```
