### ISSUE TITLE
helm chart push fails if tag contains '+'

### ISSUE THREAD

**Issue by Purneau** [Azure/acr#460]
**Describe the bug**
When trying to push a helm chart to ACR that contains a `+` sign in the tag, the push fails with an undescriptive error:

```
$ helm chart push <acr name>.azurecr.io/helm/<chart name>:0.0.1+3167
The push refers to repository [<acr name>.azurecr.io/helm/<chart name>]
ref:     <acr name>.azurecr.io/helm/<chart name>:0.0.1+3167
digest:  b50e4849b365d2d3ff9e2fd762e46f77dc2dccd8e9c0b8a3d27e52fa109b1f33
size:    4.0 KiB
name:    <chart name>
version: 0.0.1+3167
Error: failed commit on ref "manifest-sha256:b50e4849b365d2d3ff9e2fd762e46f77dc2dccd8e9c0b8a3d27e52fa109b1f33": unexpected status: 404 Not Found
```

Executing the same command with a dash instead of a plus sign succeeds:

```
$ helm chart push <acr name>.azurecr.io/helm/<chart name>:0.0.1-3167
The push refers to repository [<acr name>.azurecr.io/helm/<chart name>]
ref:     <acr name>.azurecr.io/helm/<chart name>:0.0.1-3167
digest:  2b94596c43378df0ab127313003f7c70193c42563b8e4a86510d9b8228b811af
size:    4.0 KiB
name:    <chart name>
version: 0.0.1+3167
0.0.1-3167: pushed to remote (1 layer, 4.0 KiB total)
```
**To Reproduce**
Steps to reproduce the behavior: see above

**Expected behavior**
I expect plus signs to be allowed in the tag, as a plus sign is also a default part of [Semantic Versioning 2.0](https://semver.org/).
**Screenshots**
N/A

**Any relevant environment information**
 - OS: Ubuntu, MacOS
 - Azure CLI: 2.10.1
 - Docker version: N/A
 - Datetime (UTC) when the issue occurred: N/A
 - Registry and image names: available upon request through DM

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by benc-uk** [comment]
Any update or workaround?

**Comment by yugangw-msft** [comment]
@shizhMSFT, do we have any workaround before we fix at service end?  I assume `+` is a valid character for version. Please comment

**Comment by shizhMSFT** [comment]
@yugangw-msft It is by design that we don't support `+`, which is for build metadata.
