### ISSUE TITLE
unable to send local context to buildx 

### ISSUE THREAD

**Issue by vishu42** [Azure/acr#478]
**Describe the bug**
While trying to build an image with az acr run and buildx, it always says Dockerfile not found even if Dockerfile is present in path.
Error msg -  error opening dockerfile: Dockerfile, error: open Dockerfile: no such file or directory
**To Reproduce**
1. After following this - https://github.com/Azure/acr/tree/main/docs/tasks/buildx#run-buildx-in-acr-tasks. I pushed a buildx image to azure container reg. 
2. Now running  `az acr run -f build_with_cache2.yaml /dev/null` to build an image with buildx, where build_with_cache2.yaml is
```YAML 
version: v1.1.0
steps:
  - build: -t $Registry/repo-name:$ID .
    cache: enabled
```
as mentioned here https://github.com/Azure/acr/tree/main/docs/tasks/buildx#build-with-cache
While running above command I have a Dockerfile present in the working directory. 

**Expected behavior**
According to the documentation, it should have found the dockerfile and started executing it. As its clearly mentioned in the documentation 
`It is also possible to build local repository using buildx. Run the following task to build using buildx with the context path local-repository-folder-path`

**Comment by shahzzzam** [comment]
Hi @vishu42 , can you try to run the the Task using following command instead?

```
az acr run -f build_with_cache2.yaml .
```

You might need to pass in local context `.`. instead of `/dev/null`. The example uses `/dev/null` because the context is remote.

**Comment by vishu42** [comment]
ah right - its working now @shahzzzam
