### ISSUE TITLE
Helm Failing to search latest charts stored in container registry after migrating to helm v3 from az acr helm

### ISSUE THREAD

**Issue by LaxmanPanguluri** [Azure/acr#491]
**Describe the bug**
Helm3 not able to read charts present in ACR on migration from az acr helm..This was noticed few days back. But when i am trying to pull the specific version of the chart i am able to pull it..But helm dep up and the remaining commands are not able to read the latest chart..Is it an issue with az acr helm migration or something to do with helm itsefl? I have used HELM_EXPERIMENTAL_OCI=1.

**Comment by SteveLasker** [comment]
Hi @LaxmanPanguluri,
When you say helm migration, can I assume you've pulled the charts locally from `az acr helm` and pushed them with `helm registry` ? 
http://aka.ms/acr/helm
Unfortunately, we couldn't make the charts accessible across helm repos and helm registries, so you do need to pull/push them with the `helm registry` feature.
If you're still having trouble, please open a support ticket so we can get all the details on the registry and logs and help: https://aka.ms/acr/support/create-ticket

**Comment by LaxmanPanguluri** [comment]
We haven't done pulling the charts locally from az acr helm for existing charts, but the current charts we are saving them locally and pushing them to registry. When i do helm dep up it is not pulling the latest charts(which are pushed using helm3) instead it is pulling the last charts that we pushed using helm2.

Any suggestions on why it is not pulling the latest charts when i do helm dep up

**Comment by terencet-dev** [comment]
Closing as this has been inactive for over three months. Please open a [support ticket](https://azure.microsoft.com/support/create-ticket/) with our team for assistance.
