### ISSUE TITLE
show-manifests and show does not give the same data for changeableAttributes

### ISSUE THREAD

**Issue by Nordes** [Azure/acr#495]
**Describe the bug**
When I do a `az acr repository show-manifests -n myacr --detail` it does not give the same data as with `az acr repository show -n myacr --image myimagename:1.0.0` within the changeableAttributes JSON Object.

**To Reproduce**
1. Use your subscription, and update an image to have deleteEnabled to false (`az acr repository update -n myacr --image myimagename:1.0.0 --delete-enabled false`)  _**(screenshot 1)**_
2. Verify that your image is truly `deleteEnabled` to false by doing: `az acr repository show -n myacr --image myimagename:1.0.0` _**(screenshot 3)**_
3. Now verify if that same flag is still `deleteEnabled` to false by showing all the manifests: `az acr repository show-manifests -n myacr --repository myimagename --detail` _**(screenshot 3)**_
4. You can see that the deleteEnabled is remaining true in the step 3 instead of being false like in step 2. 

**Expected behavior**
I would expect the changeableAttributes to be the same on the `show` and `show-manifests`.

**Screenshots**
Screenshot 1:
![image](https://user-images.githubusercontent.com/446572/100652904-990c9300-3315-11eb-8124-833704de2c41.png)

Screenshot 2:
![image](https://user-images.githubusercontent.com/446572/100653050-d2dd9980-3315-11eb-95c0-1a6e042cfcf5.png)

Screenshot 3:
![image](https://user-images.githubusercontent.com/446572/100653151-f56fb280-3315-11eb-8f82-a3145eb0dc9c.png)

**Any relevant environment information**
 - OS: WSL2-Ubuntu and Windows
 - Azure CLI/PowerShell/SDK version: See below
 - Datetime (UTC) when the issue occurred: Nov 30th 2020
 - Registry and image names - All registries/images

```
> az --version
azure-cli                         2.14.2 *

core                              2.14.2 *
telemetry                          1.0.6

Extensions:
azure-devops                      0.18.0

Python location '/opt/az/bin/python3'
Extensions directory '/home/nordes/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Nov  9 2020, 06:01:02)
[GCC 9.3.0]
```

**Comment by Nordes** [comment]
I just saw that I should post this into https://github.com/Azure/azure-devops-cli-extension instead. Now re-creating.

**Comment by AntonioVT** [comment]
Hi @Nordes 

The `az acr repository update -n myacr --image myimagename:1.0.0 --delete-enabled false` is targeting the tags entity. 
If you need to update the manifest entity, please use the digest in the --image parameter. For example: 

`az acr repository update -n MyRegistry --image hello-world@sha256:abc123 --write-enabled false`

If you run the `az acr repository show-manifests` again, you should see the expected values. Here's an example of the output:
![image](https://user-images.githubusercontent.com/8893162/100805948-35f22d80-33f5-11eb-952f-d78dc0f72179.png)


cc @yugangw-msft @mnltejaswini

**Comment by northtyphoon** [comment]
@AntonioVT I have a related question. If I disable the deletion on a tag, does it also effectively disable the deletion on the manifest associated with the tag? Can I assume I cannot delete a manifest without deleting the tag reference it first?

**Comment by AntonioVT** [comment]
@northtyphoon Correct, you will not be able to delete a manifest without deleting the tag reference it first. 
Tried that scenario and was unable to delete the manifest.

**Comment by Nordes** [comment]
Btw, thanks all for the answers ;).
