### ISSUE TITLE
acr import: --username and --password ignored

### ISSUE THREAD

**Issue by cfogg6** [Azure/acr#498]
**Describe the bug**
--username and --password entries don't seem to be working for az acr import. I'm trying to follow [this doc](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-import-images#import-from-an-azure-container-registry-in-a-different-ad-tenant) as I plan to import between ACRs in different tenants, but I'm running into an error when using the same subscription for initial testing.

**To Reproduce**
1. Create two ACRs (in this case, they are same tenant+subscription, different resource groups)
2. Create a service principal with acrpull and contributor access to the source ACR
3. Create a user-assigned managed identity with acrpush and contributor access to the target ACR
4. As the managed identity, run this as a powershell script:
```
az login --identity
az acr import `
    -n "[target registry]" `
    --source [source registry].azurecr.io/[source tag]:v0 `
    -t tag:v0 `
    --username=[service principal App Id] `
    --password=[service principal client secret] `
    -r "/subscriptions/[subscription id]/resourceGroups/[source rg]/providers/Microsoft.ContainerRegistry/registries/[source regsitry]"
```

**Expected behavior**
The command should use the username and password to read from the source registry and use the MSI account to write to the target registry

**Actual behavior**
Error:
The client '[object id of MSI account]' with object id '[object id of MSI account]' has permission to perform action 'Microsoft.ContainerRegistry/registries/importImage/action' on scope '/subscriptions/[subscription id]/resourceGroups/[target rg]/providers/Microsoft.ContainerRegistry/registries/[target repository]'; however, it does not have permission to perform action 'read' on the linked scope(s) '/subscriptions/[subscription id]/resourceGroups/[source rg]/providers/Microsoft.ContainerRegistry/registries/[source repository]' or the linked scope(s) are invalid.

If I understand the docs correctly, it shouldn't be using the MSI account to read from the source directory. Per the docs: "you can use service principal credentials (if available) to the source registry. Supply the appID and password of an Active Directory service principal that has ACRPull access to the source registry."

**Other info**
Azure CLI version:  2.10.1
OS: Ubuntu 18.04

I've only tested using MSI and powershell.
I've triple checked that the -r entry is correct, so I don't think the linked scope is invalid.

To verify I'm using the right credentials...
this is where I got the username (client/app id):
![image](https://user-images.githubusercontent.com/12501039/101951272-bf0f1e80-3bc4-11eb-8024-d3caeab42240.png)

and this is where I got the password:
![image](https://user-images.githubusercontent.com/12501039/101951093-6e97c100-3bc4-11eb-914e-978e89c22651.png)

Happy to provide any additional information. Thanks in advance!

**Comment by yugangw-msft** [comment]
Because "-r" is provided, so import accesses source registry through ARM under MI's identity which would fail for permissions; I believe if you can just remote `-r`, the command should work. 
Also to simplify, since `contributor` is already provided, `acrpush` or `acrpull` is no longer needed. https://aka.ms/acr/authorization

**Comment by yugangw-msft** [comment]
Meanwhile, CLI command should be updated to warn when both `--source` and `--registry` are provided

**Comment by yugangw-msft** [comment]
Please re-activate if the advice doesn't work
