### ISSUE TITLE
Unauthorized error when push docker image even though acr login was successful

### ISSUE THREAD

**Issue by corrupt-code** [Azure/acr#506]
**Describe the bug**
I am trying to push a docker image from my local system to ACR. I was able to login to ARC with following command

az acr login -n <repo name>

Now when I try to push an image to ACR, I get unauthorized error. I checked my permissions on Azure portal and I am an owner of the resource group.

I receive below error
unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.

One thing I noticed that if I have "Admin" account enabled in my container registry, and use that with "docker login", it does work.

**Expected behavior**
The image should be uploaded

**Any relevant environment information**
 - OS: Windows
 - Azure CLI: 2.0.31
 - Docker version:  19.03.13

**Comment by avtakkar** [comment]
Hi @corrupt-code, would you please create a support ticket for further assistance? 
https://azure.microsoft.com/en-us/support/create-ticket/

**Comment by zzhan08** [comment]
I have the same, any solution?

**Comment by terencet-dev** [comment]
Closing as this has been inactive for over three months. Please open a [support ticket](https://azure.microsoft.com/support/create-ticket/) with our team for assistance.
