### ISSUE TITLE
Default build image missing some important stuff

### ISSUE THREAD

**Issue by snobu** [Azure/acr#521]
I'd like to build a container image from a Python project. This Python project needs to build a wheel for its grpc dependency. That needs GCC. It's missing in the ACR worker.

```
~/func-onnx-model $ az acr build -t func-onnx-model -r shipyard .
Packing source code into tar to upload...
...
Waiting for an agent...
2021/03/05 18:12:51 Downloading source code...
2021/03/05 18:12:53 Finished downloading source code
2021/03/05 18:12:54 Using zzzzzzzzzzz as the home volume
....
2021/03/05 18:12:56 Executing step ID: build. Timeout(sec): 28800, Working directory: '', Network: ''
2021/03/05 18:12:56 Scanning for dependencies...
2021/03/05 18:12:57 Successfully scanned dependencies
2021/03/05 18:12:57 Launching container with name: build
Sending build context to Docker daemon  15.25MB
Step 1/5 : FROM mcr.microsoft.com/azure-functions/python:3.0-python3.9
3.0-python3.9: Pulling from azure-functions/python
6ec7b7d162b2: Pulling fs layer
a28a49c1de56: Pulling fs layer
....
  error: command 'gcc' failed: No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for grpcio-tools
```

For Ubuntu the missing package would be `build-essential`.

Can i still use ACR Build Tasks in this case?

**Comment by northtyphoon** [comment]
@snobu the error indicated gcc was not available in your docker image. You need to make sure the base image used in your Dockerfile has included the "build-essential". If not, your Dockerfile should include corresponding step to install the missing tool.

**Comment by snobu** [comment]
I had some very flawed assertions on how all this works. I feel pretty silly now. Sure, changing the base image works and i have now successfully built my image with `az acr build`. Thanks for jumping in so quickly.
