### ISSUE TITLE
Quarantine Preview - Pull based on digest

### ISSUE THREAD

**Issue by alexandru-bostan** [Azure/acr#522]
**Describe the bug**
It is possible to pull a quarantined image by its digest even if the entity performing the pull doesn't have AcrQuarantineReader/AcrQuarantineWriter permissions

**To Reproduce**
1. Enable Quarantine policy on a Container Registry (done via ARM template)
2. Create a Service Principal and grant it "AcrPush" role on ACR
3. Docker login to ACR as the Service Principal
4. Execute the following script
```
# declare variables
$acrName = "quarantinedemo"
$image = "nginx"
$dockerTag = "1.18.0"
$acrTag = "base-1.18.0"

docker login "${acrName}.azurecr.io"

# push any image to acr
docker pull "docker.io/library/${image}:${dockerTag}"  | Out-Null
docker tag "docker.io/library/${image}:${dockerTag}" "${acrName}.azurecr.io/${image}:${acrTag}"
$output = docker push "${acrName}.azurecr.io/${image}:${acrTag}"
Write-Host ""

# pull back image from acr using tag
docker pull "${acrName}.azurecr.io/${image}:${acrTag}"
Write-Host ""

# pull back image from acr using digest
$acrDigest = ($output[-1].Split(" "))[2]
docker pull "${acrName}.azurecr.io/${image}@${acrDigest}"
```
**Expected behavior**
According to the [readme](https://github.com/Azure/acr/tree/main/docs/preview/quarantine#attempt-to-pull-the-image-by-its-digest), pulling an image by its digest will result in an error if the identity pulling the image doesn't have AcrQuarantineReader/AcrQuarantineWriter permissions.

Instead it is possible to pull the image by its digest with AcrPull/AcrPush if the same docker host is used to push the initial image to ACR then pull it back:
- if the local digest of the image (that has been created when retagging the docker hub image)  is not deleted: the pull is not blocked
- if the local digest is first deleted (manually) and then the digest is pulled from ACR: the expected error is returned `Error response from daemon: unknown: The image is quarantined.`

**Any relevant environment information**
 - OS: Windows
 - Azure CLI version 2.20.0
 - PowerShell Integrated Console v2021.2.2 (VS Code)
 - Docker version 20.10.5

**Comment by avtakkar** [comment]
Hi @alexandru-bostan , when you push the image and then try to pull it without deleting, the docker client will not pull anything from the registry but use the locally cached image. When you delete your local image, the pull is blocked by the ACR server because the operation is unauthorized.

**Comment by alexandru-bostan** [comment]
Hi @avtakkar,

Thanks for clarifying things, I now understand what happened!
