### ISSUE TITLE
az acr login error after password change

### ISSUE THREAD

**Issue by francois-gsk** [Azure/acr#525]
After every Azure password modification, `az login` is fine, but `az acr login` fails.

When I run `az acr check-health -n xxxxxx --yes`, it's the same error:

```
An error occurred: CONNECTIVITY_CHALLENGE_ERROR
Registry 'xxxxxx.azurecr.io' did not issue a challenge.
Please refer to https://aka.ms/acr/errors#connectivity_challenge_error for more information.
```

Usually I have to wait up to 2 days before I can login to my `acr`

**Comment by estebanreyl** [comment]
Hi @francois-gsk , could you please create a support ticket for further assistance and better tracking?  
https://azure.microsoft.com/en-us/support/create-ticket/

As a tip in the meanwhile consider trying this using the Azure cloud shell, we've seen this sort of error on network configuration issues before and its worth trying to see if there is a difference when accessing from there.

**Comment by francois-gsk** [comment]
@estebanreyl Done!

**Comment by terencet-dev** [comment]
Closing as this has been inactive for over three months. Please open a [support ticket](https://azure.microsoft.com/support/create-ticket/) with our team for assistance.
