### ISSUE TITLE
Calling acr import from acr task

### ISSUE THREAD

**Issue by infbase** [Azure/acr#526]
I would like to know if/how an image import can be called in an acr task.

A use case for this is:
- 2 acr instances
- acr A (non-production acr) has an image based on mcr.microsoft.com/dotnet/runtime:3.1 and a task with baseImageTrigger enabled
- acr import is used to promote this image from acr A to acr B (production acr)
- the image in acr B should be kept up-to-date but using a predefined schedule for updating, so that time for validation in acr A exists

I believe this could be achieved using a task on acr B with a timerTrigger if that task can somehow trigger the acr import process.

**Comment by northtyphoon** [comment]
if you use [multi-step](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-multi-step) yaml file to define you task, you can create a [user or system assigned managed identity on the task](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-authentication-managed-identity) and assign the identity to access acr B, after that, you can run "az acr import" command in task.

```
version: v1.1.0
steps:
 - cmd: az login --identity
 - cmd: az acr import ...
```
