### ISSUE TITLE
Connected Registry

### ISSUE THREAD

**Issue by jabbera** [Azure/acr#531]
Care to share whatever black magic this is:-) https://docs.microsoft.com/en-us/cli/azure/acr/connected-registry?view=azure-cli-latest

Is this a solution to the auth issue wrt owning repositories?

**Comment by avtakkar** [comment]
A description of connected-registry is here: https://github.com/Azure/acr/blob/main/docs/preview/connected-registry/intro-connected-registry.md

**Comment by jabbera** [comment]
Thanks!
