### ISSUE TITLE
Add support for building on Windows versions AFTER 2004

### ISSUE THREAD

**Issue by TravisEz13** [Azure/acr#532]
**What is the problem you're trying to solve**

I want to be able to build docker images for 20H2.

**Describe the solution you'd like**

I want to be able use ACR build/tasks to build 20H2 docker images

**Additional context**

https://github.com/PowerShell/PowerShell-Docker/pull/523

Currently it fails with:

```
Step 1/14 : ARG WindowsServerCoreRepo=mcr.microsoft.com/windows/servercore
      Step 2/14 : FROM ${WindowsServerCoreRepo}:20H2 AS installer-env
      20H2: Pulling from windows/servercore
      no matching manifest for windows/amd64 10.0.19041 in the manifest list entries
      2021/03/31 17:08:05 Container failed during run: build. No retries remaining.
      failed to run step ID: build: exit status 1
      Run ID: cc62 failed after 1m41s. Error: failed during run, err: exit status 1
      ERROR: Run failed

```

**Comment by GrumpyMeow** [comment]
+1 
Same here! 
Building a custom image FROM "windows/servercore:20H2" gives this error:
`no matching manifest for windows/amd64 10.0.19041 in the manifest list entries`

**Comment by GrumpyMeow** [comment]
Still no news? :-(

**Comment by eugenecg** [comment]
Hi any news on this issue?

**Comment by GrumpyMeow** [comment]
Recently it still didn’t work

**Comment by GrumpyMeow** [comment]
I find it quite unfortunate that there's no news on this subject. It feels like ACR is lagging behind and will become end-of-life.
```
ltsc2022: Pulling from windows/servercore
no matching manifest for windows/amd64 10.0.19041 in the manifest list entries
20H2: Pulling from windows/servercore
no matching manifest for windows/amd64 10.0.19041 in the manifest list entries
```

**Comment by GrumpyMeow** [comment]
@SteveLasker what can we expect?
 20h2? Ltsc2022?

What is the expected time period? 
Week? Weeks? Month? Months?

looking forward to the updates…

**Comment by northtyphoon** [comment]
@GrumpyMeow the rollout will reach out worldwide by the end of next week. It will bring up the support for all windows versions including the latest ltsc2022. If you have registry in westcentralus/southcentralus/westus, you can already try it today.

**Comment by northtyphoon** [comment]
We have completed the rollout to support ws2022.
