### ISSUE TITLE
CONNECTIVITY_CHALLENGE_ERROR for container registry with private endpoint

### ISSUE THREAD

**Issue by NHLeo** [Azure/acr#533]
I have created an Azure Container Registry that is accessible only via a private endpoint.

- ACR:  <redacted>
- Private endpoint: <redacted>
- Private DNS zone: <redacted>
- Virtual networks linked to the private DNS zone: 

> - <redacted>
> - <redacted>
> 

When accessing the ACR from a VM on one of the linked vnets (<redacted>).  The following behavior is observed:
1) resolve-dnsname <redacted>.azurecr.io works from PowerShell and returns the correct private IP address
2) az acr login --name <redacted> (from the command prompt) fails saying that it can't connect to <redacted>.azurecr.io
3) az acr check-health -n <redacted> --yes fails (even though it returns the correct IP address) with this error:
Docker daemon status: available
Docker version: 'Docker version 20.10.5, build 363e9a8, platform linux/amd64'
Docker pull of 'mcr.microsoft.com/mcr/hello-world:latest' : OK
Azure CLI version: 2.20.0
DNS lookup to <redacted>.azurecr.io at IP 172.27.1.5 : OK
**An error occurred: CONNECTIVITY_CHALLENGE_ERROR
Registry '<redacted>.azurecr.io' did not issue a challenge.**

**Comment by yugangw-msft** [comment]
@NHLeo, our service log shows the request was rejected due to public access disabled. Could you please cross check whether the 2 vnets are peered together? And when you run "nslookup" does the private ip matches the ip of the network interface resource created with the private endpoint

**Comment by yugangw-msft** [comment]
@NHLeo, meanwhile please open a support ticket to avoid disclosing your registry details in public site

**Comment by NHLeo** [comment]
VNet peering was the answer.  Most/all of the documentation that I found had the private endpoint and the VM that was accessing it on the same vnet.  So, the virtual network links and vnet peering were never mentioned.  https://docs.microsoft.com/en-us/azure/container-registry/container-registry-private-link

**Comment by NHLeo** [comment]
Issue can be closed.
