### ISSUE TITLE
acr import --force to replace tag doesn't work replace tag

### ISSUE THREAD

**Issue by jabbera** [Azure/acr#536]
**Describe the bug**
Running: az acr import -n registry --source registry.azurecr.io/jupyter/minimal-notebook:20210420.7 -t minimal-notebook:preview --force

When the preview tag already exists doesn't actually replace the preview tag.

**Expected behavior**
Preview tag should be updated to point to new manifest

**Comment by iamjasonp** [comment]
@yugangw-msft could you please help take a look?

**Comment by yugangw-msft** [comment]
@jabbera, I am not able to reproduce this issue. How did you verify the tag was not replaced? Like using CLI `az acr repository show-tags -n registry --repository minimal-notebook --detail`?

**Comment by jabbera** [comment]
I used the portal and looked at the last update date/sha on the tag in the repository.

**Comment by jabbera** [comment]
What also might be a bit unusual: my use case is overwriting a tag on the same repository I'm sourcing from. IE in my example I'm just trying to overwrite the existing preview tag with the manifest from the same repository.

**Comment by yugangw-msft** [comment]
@jabbera, thanks for the detail, I assume `tag and docker re-push` isn't an option for you, so you are looking at `import`
CC @nathana1

**Comment by jabbera** [comment]
@yugangw-msft  That's what I'm doing as a workaround but the image is are 6+ GB

**Comment by Wwwsylvia** [comment]
Hi @jabbera, I tried the same operation in my registry but was not able to reproduce this issue. Here is my test:
```bash
$ az acr repository show -n $myregistry --image ubuntu:test
{
  "changeableAttributes": {
    "deleteEnabled": true,
    "listEnabled": true,
    "readEnabled": true,
    "writeEnabled": true
  },
  "createdTime": "2021-04-23T03:08:45.309393Z",
  "digest": "sha256:02521a2d079595241c6793b2044f02eecf294034f31d6e235ac4b2b54ffc41f3",
  "lastUpdateTime": "2021-04-23T03:12:32.471477Z",
  "name": "test",
  "quarantineState": "Passed",
  "signed": false
}

$ az acr import -n $myregistry --source $myregistry.azurecr.io/ubuntu:12.04 -t ubuntu:test --force
$ az acr repository show -n $myregistry --image ubuntu:test
{
  "changeableAttributes": {
    "deleteEnabled": true,
    "listEnabled": true,
    "readEnabled": true,
    "writeEnabled": true
  },
  "createdTime": "2021-04-23T03:08:45.309393Z",
  "digest": "sha256:18305429afa14ea462f810146ba44d4363ae76e4c8dfc38288cf73aa07485005",
  "lastUpdateTime": "2021-04-23T03:18:00.2510794Z",
  "name": "test",
  "quarantineState": "Passed",
  "signed": false
}
```

Did I miss something? Could you double check your manifests?

**Comment by jabbera** [comment]
Sigh... I should really learn how to spell. Many many apologies.
