### ISSUE TITLE
Unable to import some images from releases-docker.jfrog.io

### ISSUE THREAD

**Issue by Wwwsylvia** [Azure/acr#537]
**Describe the bug**
Image import from `releases-docker.jfrog.io` is stuck at running state and never finish

**To Reproduce**
```bash
$ az acr import -n anyregistry --source releases-docker.jfrog.io/jfrog/artifactory-pro:7.17.9 --image  artifactory-pro:7.17.9-2021.04.22
- Running ..
```
**Expected behavior**
Image import succeed or fail with explicit error message

**Screenshots**
![image](https://user-images.githubusercontent.com/8113721/116544691-0bfc5300-a922-11eb-9242-bed69ce72a47.png)

**Comment by terencet-dev** [comment]
Closing as this has been inactive for over three months. Please open a [support ticket](https://azure.microsoft.com/support/create-ticket/) with our team for assistance.
