### ISSUE TITLE
combain acr task with acr import to import images with --schedule flag

### ISSUE THREAD

**Issue by robLesniak** [Azure/acr#551]
Hi
I was wondering if there is a way to combine both `acr task` with `acr import` statement. Basically i am trying to periodically importing latest distroless image to my ACR. The --schedule flag is feature of `acr task` but it would perfectly fit to `acr import`. 
I have noticed that task create also have flag --cmd and i was trying to put import here to invoke it daily, but i think it's not designed in a way as i thought.

`az acr task create -n my_test -r my_acr  --cmd 'az acr import --name my_dev_acr.azurecr.io --source gcr.io/distroless/java:11-nonroot --image baseimages/distroless/java11-nonroot --force' -c /dev/null  --schedule "*/1 * * * *"`

logs:
Showing logs of the last created run for task 'my_test'.
Run ID: ch6v
2021/06/08 14:58:52 Alias support enabled for version >= 1.1.0, please see https://aka.ms/acr/tasks/task-aliases for more information.
2021/06/08 14:58:52 Creating Docker network: acb_default_network, driver: 'bridge'
2021/06/08 14:58:53 Successfully set up Docker network: acb_default_network
2021/06/08 14:58:53 Setting up Docker configuration...
2021/06/08 14:58:54 Successfully set up Docker configuration
2021/06/08 14:58:54 Logging in to registry: my_reg.azurecr.io
2021/06/08 14:58:55 Successfully logged into my_reg.azurecr.io
2021/06/08 14:58:55 Executing step ID: acb_step_0. Timeout(sec): 3600, Working directory: '', Network: 'acb_default_network'
2021/06/08 14:58:55 Launching container with name: acb_step_0
WARNING: The login server endpoint suffix '.azurecr.io' is automatically omitted.
ERROR: Please run 'az login' to setup account.
2021/06/08 14:59:00 Container failed during run: acb_step_0. No retries remaining.
failed to run step ID: acb_step_0: exit status 1

Run ID: ch6v failed after 10s. Error: failed during run, err: exit status 1

I was trying to append az login into cmd but with no luck

**Comment by sajayantony** [comment]
Have your tried creating a managed identity and giving it import permissions. This will automatically use the Managed identity to login to AZ and can also run the az acr import under that identity. 

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-authentication-managed-identity

/cc @shahzzzam

**Comment by sajayantony** [comment]
Here is a full sample to setup an hourly import for java non-root distroless 

## Create the multi-step acb.yaml
This can be used to create the task. 

```yaml
version: v1.1.0
steps:
  - cmd: az login --identity
  - cmd: az acr import --name my_registry --source gcr.io/distroless/java:11-nonroot --image baseimages/distroless/java:11-nonroot --force
```

## Create task with managed identity

```bash
export REGISTRY_NAME=my_registry
cat acb.yaml | \
    az acr task create -n scheduled-import -r $REGISTRY_NAME \
            -f - \
            -c /dev/null \
            --schedule "0 * * * *" \
            --assign-identity
```

## Provide permisssions to the invoke import

```bash
export ACR_RESOURCE_ID=$(az acr show -n $REGISTRY_NAME --query id -o tsv)
export ACR_TASK_PRINCIPALID=$(az acr task show -n scheduled-import -r sajay --query identity.principalId -o tsv)
az role assignment create \
                    --scope $ACR_RESOURCE_ID \
                   --assignee  $ACR_TASK_PRINCIPALID \
                   --role Contributor
```

## Test the task and check the image

```bash
az acr task run -n scheduled-import -r $REGISTRY_NAME
az acr repository show -n $REGISTRY_NAME -t baseimages/distroless/java:11-nonroot
```

**Comment by robLesniak** [comment]
@sajayantony
It works like a charm! Huge thanks!
