### ISSUE TITLE
Expansion layer issue  

### ISSUE THREAD

**Issue by Pragneshn** [Azure/acr#557]
For my image(centos image ) **./expansion-check.sh** give status 409 expanding layers continuously. what should i do ?

**Comment by estebanreyl** [comment]
That most likely indicates you hit an issue on our backend decompression service which is preventing the image from decompressing and thus it appears as stuck (it will do retries with a backoff time so it will be in that state for a while). To identify your particular case we would need the acr name. We do currently have a couple of limitations that would cause this : 1. A layer within the image is greater than 16GB , 2. The total size of expanded layers exceeds 100GB.  These limits are configurable and we  will be increasing them next nonetheless.

**Comment by northtyphoon** [comment]
@Pragneshn if you still encounter the issue, can you please open a support ticket https://aka.ms/acr/support/create-ticket?

**Comment by Pragneshn** [comment]
@northtyphoon solved thanks for support microsoft team

**Comment by terencet-dev** [comment]
Closing as this has been inactive for over three months. Please open a [support ticket](https://azure.microsoft.com/support/create-ticket/) with our team for assistance.

**Comment by pragnesh-ai** [comment]
Thanks
