### ISSUE TITLE
Error when trying to copy image from one acr to another

### ISSUE THREAD

**Issue by kumarunkulawardene** [Azure/acr#559]
Error when trying to copy image from one acr to another

**To Reproduce**
1. az Login
2. az acr login --name XXXXXX.azurecr.io
3. az acr import --name XXXXXX.azurecr.io --source YYYYYY.azurecr.io/xxxxxx:v7.9 -t xxxxxx:v7.9

**Expected behavior**

**Screenshots**

**Any relevant environment information**
 - OS: Windows 2019
 - Azure CLI/PowerShell/SDK version : 2.8.0
 - Docker version 
 - Datetime (UTC) when the issue occurred
 - Registry and image names

**Additional context**
I tried the sample you gave and it works;
az acr import --name xxxxxxx.azurecr.io --source mcr.microsoft.com/windows/servercore:ltsc2016 -t import-test/servercore:ltsc2016

But I'm getting error when I try to copy image from one of my other acr repos which allows anonymous access. I can pull from the source ACR and push to target ACR without no issues. But using the same account when I try to import the image from source acr I get the following error;

Deployment failed. Correlation ID: XXXXX-XXXX-XXXXX-XXXXX-XXXXXXXXXX. Operation registries-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX failed. Resource /subscriptions/XXXXX-XXXX-XXXX-XXXX-XXXXXXXX/resourceGroups/xxx-rg/providers/Microsoft.ContainerRegistry/registries/XXXcoe Invalid message Unauthorized Unauthorized {"errors":[{"code":"UNAUTHORIZED","message":"authentication required, visit https://aka.ms/acr/authorization for more information."}]}

![image](https://user-images.githubusercontent.com/60240127/126086112-24de0fdc-a551-40b4-bde6-e9426240bfa8.png)

**Comment by northtyphoon** [comment]
@kumarunkulawardene if you still encounter the issue, can you please open an support ticket https://aka.ms/acr/support/create-ticket? For the authorization failure you mentioned, we are unable to provide the support in public github forum as it's specific to your private registry resource which can include sensitive information.

**Comment by sajayantony** [comment]
Closing for now. We can re-open if this is an ongoing issue.
