### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jerbia** [Azure/acr#56]
The link to "azuredeploy.parameters.json" in https://github.com/Azure/acr/tree/master/docs/custom-domain page is broken.

**Comment by shhsu** [comment]
Thanks @jerbia. I also found a few more broken links https://github.com/Azure/acr/pull/58

**Comment by shhsu** [comment]
@SajayAntony @sivagms @DavidObando

**Comment by SajayAntony** [comment]
@shhsu - please link the PR here.

**Comment by shhsu** [comment]
https://github.com/Azure/acr/pull/58
