### ISSUE TITLE
Lock image: provide a solution to block updating an image but still allow deleting it

### ISSUE THREAD

**Issue by northtyphoon** [Azure/acr#561]
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-image-lock

Current ACR provide two lock mode,

1. write-enabled: block both update and delete
2. delete-enabled: allow update but block delete only

There is no solution to block update but allow delete

**Comment by shizhMSFT** [comment]
Basically, it is an archive mode.

**Comment by sajayantony** [comment]
@northtyphoon - should we close this since there is no plan to fix this issue. Changing the behavior of the write flag is a breaking change. @shizhMSFT's suggestion of archive sounds like an option. Azure storage does have an `archive status`
