### ISSUE TITLE
C# Sdk cannot find a way to enable Zone Redundancy  on Acr

### ISSUE THREAD

**Issue by digeler** [Azure/acr#562]
**Describe the bug**

**To Reproduce**
Looking at the method to create container registry in c# : 
IRegistriesOperations 
am not able to see how to create the acr with zone redundancy enabled.
This are the properties i see : 
  Sku sku,
      string location = null,
      string id = null,
      string name = null,
      string type = null,
      IDictionary<string, string> tags = null,
      string loginServer = null,
      DateTime? creationDate = null,
      string provisioningState = null,
      Status status = null,
      bool? adminUserEnabled = null,
      StorageAccountProperties storageAccount = null)
      : base(location, id, name, type, tags)
    {
      this.Sku = sku;
      this.LoginServer = loginServer;
      this.CreationDate = creationDate;
      this.ProvisioningState = provisioningState;
      this.Status = status;
      this.AdminUserEnabled = adminUserEnabled;
      this.StorageAccount = storageAccount;
    }

Provides Container Registry management (Fluent) capabilities for Microsoft Azure. 1.37.1
**Expected behavior**
cannot find the method to enable zone redundancy.

is there a newer sdk that support this method ?
thanks

**Comment by shizhMSFT** [comment]
The SDK is currently based on API version `2019-12-01-preview`. However, the availability zone is supported since API version `2020-11-01-preview`.

@luisdlp Do we have a plan to upgrade the dotnet SDK against the latest API version.

**Comment by shizhMSFT** [comment]
@digeler We are planning to publish a GA API this semester and will update all SDKs accordingly.
