### ISSUE TITLE
Unable to connect to ACR when connected to ATT network

### ISSUE THREAD

**Issue by nsadula** [Azure/acr#563]
**Describe the bug**

Unable to login to the ACR that is on the ATT subscription connected to a ATT network though enabled all the network can access the ACR.

![image](https://user-images.githubusercontent.com/53452205/127679167-b408c3d1-6557-4737-961f-fc9740023098.png)

**To Reproduce**
1. docker login <acr_name>

**Expected behavior**
 Should be able to connect to the ACR and tp pull and push images to it when connected to ATT network
**Screenshots**

![image](https://user-images.githubusercontent.com/53452205/127679475-9a4a4da4-1e2a-4dc5-a5fc-b427757598ab.png)

![image](https://user-images.githubusercontent.com/53452205/127679718-47626db3-bce9-4944-b28f-239e15652eda.png)

**Any relevant environment information**
 - OS: [e.g. Ubuntu, Windows]
 - Azure CLI/PowerShell/SDK version
 - Docker version
 - Datetime (UTC) when the issue occurred
 - Registry and image names

**Additional context**

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by sajayantony** [comment]
@nsadula please open a support case through the portal so that the issue can be handled compliantly without disclosing details on a public GitHub thread.

**Comment by terencet-dev** [comment]
Closing as this has been inactive for over three months. Please open a [support ticket](https://azure.microsoft.com/support/create-ticket/) with our team for assistance.
