### ISSUE TITLE
Task failed to set docker credentials for external registry

### ISSUE THREAD

**Issue by infbase** [Azure/acr#566]
**Describe the bug**
Using ACR tasks to build image where the dockerfile references a base image in another private ACR.
When the task runs the credentials for the other ACR are not loaded:

```
2021/08/12 11:49:57 Downloading source code...
2021/08/12 11:50:00 Finished downloading source code
2021/08/12 11:50:01 Using acb_vol_796e106b-4d18-42ec-b168-8a7abe4ada73 as the home volume
2021/08/12 11:50:03 Setting up Docker configuration...
2021/08/12 11:50:06 Successfully set up Docker configuration
2021/08/12 11:50:06 Logging in to registry: cscm1nacr001.azurecr.io
2021/08/12 11:50:07 Successfully logged into cscm1nacr001.azurecr.io
2021/08/12 11:50:07 Logging in to registry: cscm1hacr001.azurecr.io
failed to login, ran out of retries: failed to set docker credentials: Error: Cannot perform an interactive login from a non TTY device
: exit status 1
Run ID: cbry failed after 18s. Error: failed during run, err: exit status 1
```

**To Reproduce**
```Powershell
az acr task create `
    -n $taskName `
    -r $acrName `
    -t $acrTag `
    -c $gitPath `
    -f Dockerfile `
    --git-access-token $gitToken `
    --assign-identity $managedIdentity `
    --platform $platform `
    -o table

az acr task credential add `
    -n $taskName `
    -r $acrName `
    --login-server "cscm1hacr001.azurecr.io" `
    -u "AKV secret url" `
    -p "AKV secret url"

az acr task run `
    -n $taskName `
    -r $acrName
```

**Expected behavior**
The task should successfully load the additional credentials.

**Additional context**
The other ACR is in another tenant, if that's relevant.

**Comment by savaradh** [comment]
Hi @infbase,

When adding a task credential with keyvault url, you need to give access to the keyvault for the Task's identity. Can you please confirm if that is done already?

If not, please do the following steps to update the keyvault policy.

`
principalID=$(az acr task show \
  --name <task_name> --registry <registry_name> \
  --query identity.principalId --output tsv)

az keyvault set-policy --name mykeyvault \
  --resource-group myResourceGroup \
  --object-id $principalID \
  --secret-permissions get
`

Once this is done, update the task credential to use the system assigned identity when accessing keyvault.
`
az acr task credential add -n taskname -r registryname --login-server myregistry.docker.io \
    -u https://mykeyvault.vault.azure.net/secrets/secretusername -p https://mykeyvault.vault.azure.net/secrets/secretpassword \
    --use-identity [system]
`

Please let us know if it works after the changes. Also you can refer the documents https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-authentication-key-vault#grant-identity-access-to-key-vault-1 and https://docs.microsoft.com/en-us/cli/azure/acr/task/credential?view=azure-cli-latest for more information.

**Comment by infbase** [comment]
Hi @savaradh,

Yes, a user-assigned managed identity is used to retrieve those secrets. 
Also:

- If we pass the values instead of the AKV URLs we get the same error.
- Using a multistep task with the following code successfully connects to the other registry:

```yaml
version: v1.1.0
secrets:
  - id: username
    keyvault: https://...
  - id: password
    keyvault: https://...
steps:
  - cmd: az login --identity
  - cmd: docker login cscm1hacr001.azurecr.io --username {{.Secrets.username}} --password {{.Secrets.password}}
```

**Comment by savaradh** [comment]
We identified this to be an issue with the latest version of Azure Cli. We will do a hotfix on the next version soon. Meanwhile if you are stuck, I suggest you to go back on the AZ Version. I recommend version 2.25.0 or 2.23.0

**Comment by sajayantony** [comment]
Closing this for now. Please reopen if this is still a problem. @infbase
