### ISSUE TITLE
Updated cert for custom domain not taken from key vault

### ISSUE THREAD

**Issue by tgossler** [Azure/acr#568]
**Describe the bug**
We are in the private preview for the custom domain feature for ACR (see here: https://github.com/Azure/acr/tree/main/docs/custom-domain) and are using it successfully for about one year. Now, the certificate has expired and we need to update it. So, we have ordered a new certificate and uploaded it according to the manual in PEM format as a new version into the Key Vault. Nothing else changed. But, even after 10 minutes the new certificate is not taken. The web browser under the URL "https://<acrCustomDomain>/v2" is reporting an ERR_CERT_DATE_INVALID and the certificate details view of the browser is showing an old certificate yet.

**To Reproduce**
1. Upload new valid certificate in PEM format as new secret version in the key vault
2. Wait some time and then open web page "https://<acrCustomDomain>/v2" in a Microsoft Edge

**Expected behavior**
The server certificate should be valid and the web page be displayed.

**Additional context**
- The ACR and Key Vault are in different Azure subscriptions
- Custom domain name is managed in Azure DNS
- The certificate is a publicly trusted one (QuoVadis Global SSL ICA G3)

**Comment by avtakkar** [comment]
@tgossler , please open a [support request](https://azure.microsoft.com/support/create-ticket/) and we can assist you further after you provide your certificate's key vault identifier. Automatic certificate rotation is now supported in private preview. 
FYI - @sajayantony

**Comment by tgossler** [comment]
Ok, thanks. I have done that. Would be good to add this information to the documentation page.
Why is this feature in "private preview" for such a long time?

**Comment by toddysm** [comment]
Just to clarify, automatic cert rotation is NOT supported yet. To update the certificate, you can open a support ticket.

**Comment by toddysm** [comment]
@dlepow Can we update the documentation with the process for updating the certificate? During Private Preview this is done manually and customers need to open a Support Request and provide the secret identifier for the new certificate for the update to happen.

**Comment by toddysm** [comment]
@tgossler I followed up internally and your subscription will be enabled for automatic cert rotation (you can ignore my previous comment). From now on, the update should happen automatically if you upload the cert to the same Key Vault location. If there are any issues going forward, please don't hesitate to submit a support request or contact us.
