### ISSUE TITLE
Make --filter a global parameter

### ISSUE THREAD

**Issue by JayyTurakhia** [Azure/acr#573]
**What is the problem you're trying to solve**
 - **--filter** if added to _az acr repository show-tags --filter ".test-image"_ can be used to separate container images based on regex
 - **--filter** if added to _az acr repository list --filter ".my-awesome-image"_ can be used to separate repos based on regex

**Note** - This param is already implemented in az acr purge as documented [here](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auto-purge) 

**Describe the solution you'd like**
Make --filter a global parameter

**Comment by Wwwsylvia** [comment]
Hello @JayyTurakhia , thanks for the feature request! 
We would like to understand the E2E scenario your are interested in - What would you do with the filtered repositories/tags?

**Comment by JayyTurakhia** [comment]
@Wwwsylvia 

Sure. We tag some containers as "rc" meaning release candidates. It would be great to be able to list fetch these with a regex rather than having a filtering logic on client side.

Another use is to list containers having semver master. This could be again done via regex by filtering those having Major.Minor.Version as opposed to Major.Minor.Version-feature

At times, we also want to list repositories that belong to CICD, Helm and the business logic containers. This is done by having special naming for these, but then no way filter these out by reading back or referring

**Comment by Wwwsylvia** [comment]
Thanks @JayyTurakhia for the information.
@toddysm This is a feature request. Do we want to support `--filter` parameter in `az acr` commands?
