### ISSUE TITLE
ACR with Custom Domain - CloudFlare DNS

### ISSUE THREAD

**Issue by kubragogebakan** [Azure/acr#576]
Hello to everyone,

Our senario:
We want to use Azure Container Registry with our custom domain. Now, our domain records are located on the CloudFlare DNS. 

Steps:
To use ACR with custom domain, just have been done these following steps:
1- Created ACR with premium SKU. Data endpoint & system assigned identity were enabled on ACR.
2- DNS record created as CNAME record on CloudFlare
For example: myacrdns.xxx.com - myacrdns.azurecr.io 
3- Upload custom domain cert(s) to Azure Key Vault. Also integrated Azure Key Vault and Azure Container registry as described this document. System assigned identity was used and necessary permission assigned on Azure Key Vault.

Issue: 
After completed all steps, we are trying pull images via our custom domain like that:

docker pull  myacrdns.xxx.com/web:latest

The following error was occurred:

### Error response from daemon: error parsing HTTP 404 response body: unexpected end of JSON input: ""

Do you have any idea to fix the issue now?

Best wishes,
Regards.

**Comment by sajayantony** [comment]
@kubragogebakan - Since custom domains is a private preview feature and these are hard to support through GH issues, as there are customer details involved, hope you can follow up as a Azure support case. 

Closing this issue since the support channel is the recommended communication path here.
