### ISSUE TITLE
Images are not locked consistently in ACR repository

### ISSUE THREAD

**Issue by kumarg25** [Azure/acr#592]
**What is the problem you're trying to solve**
The registry has geo-replication enabled. The image was initially pushed to eastus2 and later replicated to other regions. When the customer manually checked the metadata from the terminal, it pulled the metadata from southeastasia. 
 
When the image and updated metadata were replicated from eastus2 to southeastasia, the log showed a _potential racing problem_ which caused the updated metadata to be overwritten, and the value was reverted. 

**Describe the solution you'd like**
To solve this racing problem and ensure that the image locks are not reverted

**Additional context**
This is to track the progress of the replication experience.

**Comment by sajayantony** [comment]
We are following up internally to see if/when we can prioritize this.
