### ISSUE TITLE
Failed image pull from private ACR

### ISSUE THREAD

**Issue by Chams91** [Azure/acr#594]
**Describe the bug**
When using a private ACR (with a private endpoint and private DNS resolution), AKS clusters attached to the ACR (acrPull role assignement is assigned) are unable to pull images. DNS resolution works and registry can be resolved internally both from cluster and other azure resources where peering  and network links are established. When pulling an image from the registry to the cluster, we get  the following error:
 `"[2021-12-29T14:41:37Z] Validating image pull permission: FAILED
[2021-12-29T14:41:37Z] ACR d*****.azurecr.io rejected token exchange: failed to send token exchange request: Post https://d*****.azurecr.io/oauth2/exchange: dial tcp 10.201.3.5:443: i/o timeout"`

**To Reproduce**
1. ACR health check:
`#az acr check-health --name d*****  --ignore-errors --yes
Docker daemon status: available
Docker version: 'Docker version 19.03.12, build 48a66213fe, platform linux/amd64'
Docker pull of 'mcr.microsoft.com/mcr/hello-world:latest' : OK
Azure CLI version: 2.31.0
DNS lookup to d*****.azurecr.io at IP 10.201.3.5 : OK
Challenge endpoint https://d*****.azurecr.io/v2/ : OK
Fetch refresh token for registry 'd*****.azurecr.io' : OK
Fetch access token for registry 'd*****.azurecr.io' : OK
Helm version: 3.5.2
Notary version: 0.6.1`

2. Pulling Image from the peered VM works as expected: 
`$ docker pull d*****.azurecr.io/hello-world
Using default tag: latest
latest: Pulling from hello-world
Digest: sha256:f54a58bc1aac5ea1a25d796ae155dc228b3f0e11d046ae276b39c4bf2f13d8c4
Status: Image is up to date for d*****.azurecr.io/hello-world:latest
d*****.azurecr.io/hello-world:latest` 
3. Pulling from the cluster results in timeout and cluster to registry health check is the following: `#az aks check-acr -n c******v -g c******v --acr d*****.azurecr.io
[2021-12-29T14:41:37Z] Validating image pull permission: FAILED
[2021-12-29T14:41:37Z] ACR d*****.azurecr.io rejected token exchange: failed to send token exchange request: Post https://d*****.azurecr.io/oauth2/exchange: dial tcp 10.201.3.5:443: i/o timeout
cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x7f74d33ea0d0>, <function _x509_from_base64_to_hex_transform at 0x7f74d33ea158>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult []
cli.knack.cli: Event: Cli.SuccessfulExecute []
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f74d34776a8>]`

**Expected behavior**
Pod should be created normally in cluster as resolution is fine and role assignement is configured.

**Comment by northtyphoon** [comment]
@Chams91 it looks like a connectivity issue in your cluster network that prevents the request reaching https://d*****.azurecr.io private endpoint. Since you could pull the image from another machine through the same private endpoint, it confirmed ACR was able to serve the request. You can open a support ticket and share your network topology so the support team can help you troubleshoot the network issue.
