### ISSUE TITLE
Docker push does not create tags in ACR

### ISSUE THREAD

**Issue by dpurge** [Azure/acr#597]
**Describe the bug**

I have a private container registry and testing pushing and pulling images.
After `docker push` I see my image in the registry, but it does not have any tags.
I cannot pull that image because tag is missing.

**To Reproduce**

1. Start with newly created ACR, I will call it xxx
2. `az login`
3. `az acr login --name xxx`
4. `docker pull mcr.microsoft.com/hello-world:latest`
5. `docker tag mcr.microsoft.com/hello-world:latest xxx.azurecr.io/hello-world:latest`
6. `docker push xxx.azurecr.io/hello-world:latest`

All the above commands should complete successfully.

```
PS C:\Windows\System32> docker push xxx.azurecr.io/hello-world:latest
The push refers to repository [xxx.azurecr.io/hello-world]
af0b15c8625b: Pushed
latest: digest: sha256:92c7f9c92844bbbb5d0a101b22f7c2a7949e40f8ea90c8b3bc396879d95e899a size: 524
```

7. Navigate to the ACR in portal.azure.com, and go to `Repositories`
8. Find `hello-world` listed there, navigate inside. See that `Manifest count` is 1, but `Tag count` is 0.
9. `docker pull xxx.azurecr.io/hello-world` gives an error: Error response from daemon: manifest for xxx.azurecr.io/hello-world:latest not found: manifest unknown: manifest tagged by "latest" is not found

**Expected behavior**
I expected two things:

1. After successful `docker push` in step 6 there should be a `latest` tag in the ACR
2. `docker pull` in step 9 should not return an error

**Screenshots**

**Any relevant environment information**
 - OS: Windows
 - azure-cli 2.32.0
 - Docker version 20.10.7, build f0df350
 - Datetime (UTC) when the issue occurred: 21:02 January 21, 2022

**Additional context**

Importing image with azure-cli works as expected.

`az acr import --name xxx --source mcr.microsoft.com/hello-world --image hello-world:latest`

This command completes successfully and after it completes, I can see the `latest` tag in the portal, and `docker pull` works as expected:

```
PS C:\Windows\System32> docker pull xxx.azurecr.io/hello-world
Using default tag: latest
latest: Pulling from hello-world
Digest: sha256:92c7f9c92844bbbb5d0a101b22f7c2a7949e40f8ea90c8b3bc396879d95e899a
Status: Image is up to date for xxx.azurecr.io/hello-world:latest
xxx.azurecr.io/hello-world:latest
```

**Comment by northtyphoon** [comment]
@dpurge can you check if you have enabled `quarantine` on your registry? https://github.com/Azure/acr/blob/main/docs/preview/quarantine/readme.md

**Comment by dpurge** [comment]
Thank you very much @northtyphoon , this is very helpful.

Indeed, `az acr show -n xxx` tells me that `quarantine` is enabled on my registry:

```
    "quarantinePolicy": {
      "status": "enabled"
    },
```

Sorry for opening a bug for this, I could not explain this behavior.
