### ISSUE TITLE
Action recommended: Review how you pull container images from Docker Hub

### ISSUE THREAD

**Issue by skhilliard** [Azure/acr#598]
Regarding this notification: Review your environments that may be affected by Docker Hub rate limiting before 30 June 2022

Does this apply to Azure DevOp builds also?  For example, we have this build step set up...

![image](https://user-images.githubusercontent.com/23263471/151572579-103eb4b7-035f-4274-8f7f-30555c1b96eb.png)

...the referenced dockerfile has the following...

![image](https://user-images.githubusercontent.com/23263471/151572827-2d7a454f-82d3-447e-b4dc-1601b1b4f930.png)

**Comment by SteveLasker** [comment]
Hi folks,
If your build was from a dedicated agent pool, running on Azure, this applies to you.
Microsoft had partnered with Docker to give time for people to transition to authenticated accounts or consume the images they depend upon into environments you manage. This "safety net" will end June 30, 2022. We wanted to provide time for users to either authenticate with docker hub, and/or promote the content they depend upon.

See
- [Best Practices for Consuming Public Content](https://opencontainers.org/posts/blog/2020-10-30-consuming-public-content/)
- [Azure specific guidance](https://aka.ms/consuming-public-content)

We are working on an ACR cache feature that will ease this, however, we do not have any additional announcements to make at this point.

**Comment by Korijn** [comment]
Question: does this affect AKS deployments? As in, will creation of a new AKS cluster cause many Docker Hub pulls? Should I be worried that AKS cluster creation will fail?

**Comment by palma21** [comment]
No, AKS doesn't use docker hub at all. Just MCR and internal mirrors.

**Comment by skhilliard** [comment]
Assuming that we have a Docker Hub account, is there some way to use a personal access token in the docker Dev Ops task (as shown above) to use that so that the FROM node:14-slim pull won't be anonymous?  Or is the only way to get around this to pull that image to an Azure Container registry?

**Comment by SteveLasker** [comment]
Please see: http://aka.ms/acr/cache
#close
