### ISSUE TITLE
Issue with ACR build task. tag not accepted when "--" is present

### ISSUE THREAD

**Issue by gianlucagravina** [Azure/acr#602]
**Describe the bug**
Running an acr build task with a tag like "myreg/myimage:v1--alpha" throws an error

**To Reproduce**
1. create an acr resource (myreg)
2. use a simple docker file
3. execute az acr build -t myimage:v1--alpha -r myreg .

**Expected behavior**
the image is built and pushed in acr repo

**Screenshots**
![image](https://user-images.githubusercontent.com/55887306/154633099-234da1ff-a7bb-4903-9e56-ae5fa571b903.png)

**Any relevant environment information**
No relevant info. it fails in several environments, always with the same error. The problems seems to be in the build executor agent in azure.

**Additional context**
--
Docker build works properly with the same tag that throw the exception in acr build.
Docker tag definition doesn't mention anything about the usage of "--"

![image](https://user-images.githubusercontent.com/55887306/154633459-4ac5b1d2-48f8-4eaa-a9d0-bd7940e40808.png)

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by juliusl** [comment]
Thanks for reporting this issue. I will work on a fix

**Comment by juliusl** [comment]
Ok I think I've found the issue, I wrote a fix and will begin testing. Should be live in the next two weeks if there are no interruptions

**Comment by juliusl** [comment]
@gianlucagravina  So I've tested this recently and looks like I'm able to push images with '--', let me know if there are any other issues and I can reopen the issue.
