### ISSUE TITLE
Issue with ACR Build with private endpoint and private registry.

### ISSUE THREAD

**Issue by gianlucagravina** [Azure/acr#603]
**Describe the bug**
When trying to execute an acr build task with a private repository and a private endpoint, the build task still tries to go through public internet.

**To Reproduce**
1. Create ACR with private Endpoint and Private registry
2. Create a vm in the vm that could reach and use the private endpoint.
3. try to execute an ACR build from the VM

**Expected behavior**
The build will happen using the endpoint and pushing the image in ACR withouth passing through public internet.

**Screenshots**
error message similar to this one:
denied: client with IP '<my public IP>' is not allowed access. Refer https://aka.ms/acr/firewall to grant access
The IP seems to be one IP from Azure (probably the agent which is running the azure build). Enabling public access just from these CIDR ranges, works properly.

<img width="398" alt="image" src="https://user-images.githubusercontent.com/55887306/154952118-ce668a01-17fc-419a-b2fb-87ab053f8e21.png">

**Any relevant environment information**
 - tried on Jumphost with Linux and latest version of az-cli 2.33

**Additional context**
Seems similar to a problem that were there with acr login. https://github.com/Azure/azure-cli/issues/17137 

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by jaysterp** [comment]
@gianlucagravina In order for the `az acr build` command to connect to the ACR through private endpoint, you must use a dedicated agent pool.  For more information on agent pool, please reference [Run an ACR task on a dedicated agent pool](https://docs.microsoft.com/azure/container-registry/tasks-agent-pools). Per the documentation, an agent pool provides:

**Virtual network support** - Assign an agent pool to an Azure VNet, providing access to resources in the VNet such as a container registry, key vault, or storage.

**Comment by gianlucagravina** [comment]
> 

Hi @jaysterp , 

thanks for the prompt reply. 

As far as I understood az acr build is not in preview, but the agentpools are still in preview. Other than that the agentpools are not available in every region (not in Southeastasia for sure).
Does it mean we just have to wait for the agentpool feature to be in GA and in southeastasia region? is there any public expected timeline for this feature ?

**Comment by jaysterp** [comment]
Hi @gianlucagravina. For customers using `az acr build` in regions where agent pool is not available, we recommend them to add the regional ACR IPs to the firewall rule. Please reference [Allow access by IP address range](https://docs.microsoft.com/azure/container-registry/container-registry-firewall-access-rules#allow-access-by-ip-address-range).

Another option is to enable Trusted Services on your ACR. You can create an ACR task with a managed identity, which can access your network restricted ACR and execute the build. The `az acr build` command does not support trusted mode. For more information, please reference [Allow trusted services to securely access a network-restricted container registry](https://docs.microsoft.com/azure/container-registry/allow-access-trusted-services#example-acr-tasks). 

cc @northtyphoon for agent pool GA timeline.

**Comment by gianlucagravina** [comment]
Hi @jaysterp, thanks again.

The IP open is the solution we have right now, but we do really want to leverage a full private environment with NO publi access enabled, if possible, in the future.

I am looking at the acr task solution you mentioned, the whole process for the Managed Identity is quite clear to me, what is not clear is how to pass the context to the task executor. The quick task compress the source folder and sent it over the acr agent to build the docker image, I cannot see how we could leverage a similar solution, I have seen option for public git repo as well but no samples with gzip (and how to send the archive to the agent), or a private azure devops repository.

Hope you can share few directions on those point.

Thanks !

**Comment by jaysterp** [comment]
Hi @gianlucagravina,

The task resource supports fetching build contexts from private git repositories, including those hosted on Azure DevOps and GitHub. Please see this tutorial for more details [Tutorial: Automate container image builds in the cloud when you commit source code](https://docs.microsoft.com/azure/container-registry/container-registry-tutorial-build-task).

You can also upload the local source folder to the ACR as an OCI artifact. The task can reference this artifact as the build context. For more information on this scenario, please see [Example: Build Docker image from OCI artifact](https://docs.microsoft.com/azure/container-registry/container-registry-oci-artifacts#example-build-docker-image-from-oci-artifact).

**Comment by terencet-dev** [comment]
Closing as this has been inactive for over three months. Please reopen this issue if you would like additional guidance.

**Comment by Xplz3d** [comment]
Same issue here, event by using deciated agent pools linked to subnet

**Comment by arnaud-tincelin** [comment]
Same issue, I was able to make it work with dedicated agent pools or by enabling Public internet access; but as soon as I disable public access, I get the error "client with IP 'xxxx' is not allowed access" when pushing the image

**Comment by Xplz3d** [comment]
@arnaud-tincelin with dedicated agent pool it's working for us now ! it was related to dns record issue in our case

**Comment by gcpvasu** [comment]
> @arnaud-tincelin with dedicated agent pool it's working for us now ! it was related to dns record issue in our case

Hello how it was resolved via dns zone.. Could you please give some clarification

**Comment by Xplz3d** [comment]
@gcpvasu , create a dedicated agent pool in a dedicated subnet.
Be sure that the subnet can resolve your acr internally (private endpoint), check if you created a virtual network link between private.azurecr.io and the vnet of the dedicated agent pool subnet.

**Comment by paul-michalik** [comment]
> Hi @jaysterp, thanks again.
> 
> The IP open is the solution we have right now, but we do really want to leverage a full private environment with NO publi access enabled, if possible, in the future.
> 
> I am looking at the acr task solution you mentioned, the whole process for the Managed Identity is quite clear to me, what is not clear is how to pass the context to the task executor. The quick task compress the source folder and sent it over the acr agent to build the docker image, I cannot see how we could leverage a similar solution, I have seen option for public git repo as well but no samples with gzip (and how to send the archive to the agent), or a private azure devops repository.
> 
> Hope you can share few directions on those point.
> 
> Thanks !

Although the documentation is not very clear on that, you can also upload the context as *.tag.gz to a container blob and reference it via https://*. with SaS token attached. If the storage account is behind a firewall, the access, at least in theory, could be granted the same way as for the registry itself - I am however struggling to make this work. Anyone?

**Comment by VGerris** [comment]
Still not working

**Comment by VGerris** [comment]
Check if your docker command is resolving properly. I noticed using --debug that az acr is using docker command like docker login and then the DNS resolution is done by docker and whatever env it is in. In my case I was using colima and the colima VM didn't have the DNS setup properly and as such docker login didn't work properly ( resolved in external IP).

**Comment by LazaUK** [comment]
Documented walkthrough process of using OCI artifact (with some samples) here: https://github.com/LazaUK/ACR-OCIArtifact-CLI
