### ISSUE TITLE
ACR Security Scan in CI/CD events triggered

### ISSUE THREAD

**Issue by gianlucagravina** [Azure/acr#604]
**What is the problem you're trying to solve**
I would like to have a way to react, in my CI/CD pipeline, to security issues found in ACR

**Describe the solution you'd like**
It would be useful having a webhook in ACR as we have for other events to be able to trigger when a scan in ACR is completed after push. I found a solution that use a polling of  5 minutes, that solution, unfortunately doesn't guarantee that the image I pushed is "clean" from a security perspective. If for some reason that scan is not completed yet, my pipeline could move the image into a production deployment exposing my environment to possible risks.
Another possible solution could be introducing an api to query the acr scan status (something like pending, running, complete) we can poll and check to understand if we can finally get the status of the last security scan.

**Additional context**

**Comment by Wwwsylvia** [comment]
@gianlucagravina Does this help? https://github.com/Azure/acr/tree/main/docs/preview/quarantine#image-pushed-webhook-notification
Once the image passed the scan, a Image Pushed webhook will triggered.

**Comment by gianlucagravina** [comment]
> @gianlucagravina Does this help? https://github.com/Azure/acr/tree/main/docs/preview/quarantine#image-pushed-webhook-notification Once the image passed the scan, a Image Pushed webhook will triggered.

This seems to be a good way to solve our problem. I will check this out. Thanks a lot for the super quick response!

**Comment by Wwwsylvia** [comment]
@gianlucagravina We don't have a public schedule yet, but we are trying to prioritize it. 
Please see https://github.com/Azure/acr/issues/499#issuecomment-989282061.

**Comment by dpaardenkooper** [comment]
Hi ACR product team, 
Any updates about going to GA status?

Kind regards, 
Dinant

**Comment by BenjaminNeale-Heritage** [comment]
I'm very interested in the Quarantine feature.  Is there any update on when the Quarantine feature will reach GA?

I've found Nexus Repository Firewall to be very useful which can quarantine software dependencies until they are confirmed 'safe'.  The Quarantine feature in ACR appears similar and would be a powerful tool to reduce chances of unsafe images being used.
