### ISSUE TITLE
Action Needed? Docker Hub rate limiting before 30 June 2022

### ISSUE THREAD

**Issue by v-sagoll** [Azure/acr#605]
We have a App Service which uses Azure Container Registry to pull images. We use Admin user of Container Registry to connect with App Service.

We got a mail from Microsoft azure saying "On 24 August 2020, Docker announced that they would implement rate limiting of container pull requests from Docker Hub for anonymous requests." with Subject line "Action recommended: Review how you pull container images from Docker Hub".

As we are making a anonymous call ? Request you to help us understand on any action item required from our side ?

App service:
![image](https://user-images.githubusercontent.com/100906255/156723270-cdb083ca-a151-46af-a5dc-8fe2dacdc156.png)

Container Registry:
![image](https://user-images.githubusercontent.com/100906255/156723015-f800cbdc-dd73-47d0-8ea6-c2224da22f03.png)

Build pipeline:
![image](https://user-images.githubusercontent.com/100906255/156737164-bf026e02-b16b-4d22-a8a0-6ddc857180f9.png)

App Service connects to registry using Admin user Access Key of Registry as below (App Service Configuration):
![image](https://user-images.githubusercontent.com/100906255/156739696-fe57c37e-d9ea-44f6-a8fb-3ab3e4b83fb0.png)

Thank You in advance.

**Comment by SteveLasker** [comment]
Nope, you're good to go as you have your dependencies on ACR, which operates within Azure. 
I would suggest moving off the Admin credentials to managed identities, but that's unrelated to the Docker Hub issue.

I am confused by the comment:

> As we are making a anonymous call ?

If that's a question, then you're not making anonymous calls to ACR as you are providing credentials.
Steve

**Comment by v-sagoll** [comment]
Thank You a lot for your response, it helped us understand the request and close it.
