### ISSUE TITLE
Negative Look ahead regex for inverse match of images with tags containing `release` is not working

### ISSUE THREAD

**Issue by Bhaskar1312** [Azure/acr#606]
**Describe the bug**
When attempting to execute the purge command in pipeline, it gives `commandError: unable to correctly parse filter flag`

**To Reproduce**
1.  create a image with tag that ends in `release` suffix
2.  Run the command with registry and image `az acr run -r myregistry --timeout 7200 --cmd "acr purge --dry-run --filter myorg/mycontainer:^((?!release).)*$ --ago 180d --untagged" /dev/null`
or I initially used `^(?:(?!release).)*$` and tried by putting quotes around it to delete images with tags that dont contain release. 
**Expected behavior**
To delete images with tags that dont contain `release` without any error

**Screenshots**

**Any relevant environment information**
 - OS: Red Hat 4.8.5-44
 - Azure CLI-  2.30.0*
core                              2.30.0 *
telemetry                          1.0.6
Extensions:
azure-devops                      0.22.0
Python location '/usr/bin/python3.6'
 - Datetime (UTC) when the issue occurred
 - Registry and image names

**Additional context**

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by juliusl** [comment]
golang's regexp engine doesn't natively support backtracking functions (lookahead/behind) because they want to guarantee constant time evaluation. I put up a PR just now to address this.

**Comment by Bhaskar1312** [comment]
If one want to gurantee linear time evaluation, inverse match (--inverse-filter) might be a good idea

**Comment by juliusl** [comment]
@Bhaskar1312 This fix has been merged into main, I'll update when it's been deployed to tasks.
