### ISSUE TITLE
az acr task run does not return exit code 1 if the task run fails

### ISSUE THREAD

**Issue by mracfa** [Azure/acr#608]
**Describe the bug**
Not sure if it's a bug or by design and the expected behavior, but whenever we run an "az acr task" we always get exit code 0 on our command, regardless if the tasks fail or not. 

I do understand that the command is successful, however, since the task fails, it should exit with the same return code.

Example:

![image](https://user-images.githubusercontent.com/52406590/160838375-171733d0-35e3-4de7-a703-ce7231d68e82.png)

**To Reproduce**
1. Run a task pointing to a file that does not exist:
az acr task run  --name example1 --registry $ACR_NAME  --context https://github.com/mracfa/acr-build-helloworld-node.git#main  --file taskmulti2.yaml --set DOCKER_FILE_NAME=Dockerfile.wrong --arg BRANCH="main" --arg TARGET_ENVIRONMENTS="dev"
2. Check the return code
echo $?
3.You should get 0 and not 1 

**Expected behavior**
I expect to have the exit status i have in my failed task (on this case 1).
For automation purpose it would help.

**Screenshots**
![image](https://user-images.githubusercontent.com/52406590/160838861-68b74b73-f7e1-4def-aebe-2d4ab23f22d1.png)

**Comment by northtyphoon** [comment]
OK. I checked the code today and realized the following cli code doesn't pass the right raise_on_error option.

https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/task.py#L918

**Comment by northtyphoon** [comment]
https://github.com/Azure/azure-cli/pull/21983

**Comment by northtyphoon** [comment]
the latest cli should have the fix
