### ISSUE TITLE
How to use the ACR-scoped managed identity?

### ISSUE THREAD

**Issue by andyrobbins** [Azure/acr#609]
I'm trying to figure out in which context I can authenticate as the ACR-scoped system- or user-assigned managed identity.

I can use the Azure portal or the az binary to create and view the managed identity, as documented here: https://docs.microsoft.com/en-us/cli/azure/acr/identity?view=azure-cli-latest

For example, I can see the principal ID of the identity with this command:

```
az acr identity show -n <name> --resource-group <resource_group>
{
  "principalId": "<id>",
  "tenantId": "<tenant id>",
  "type": "systemAssigned",
  "userAssignedIdentities": null
}
```

But I can't figure out how the ACR can actually authenticate using this identity.

When I create a task under my ACR, a new service principal is created associated with that task and I can successfully authenticate to, for example, AzureAD as that service principal within the task runner. But how do I authenticate as the managed identity scoped to the ACR? 

Thank you!

**Comment by juliusl** [comment]
In the context of az-cli you would first, 

`az login --identity --username <principal-Id>`

and then 

`az acr login --name <registry-name>` 

and then you should be able to docker pull/push. 

Does that answer you question?

**Comment by andyrobbins** [comment]
Yes it does @juliusl! Thank you! :)
