### ISSUE TITLE
Images tagged with an ending period ('.') cannot be untagged

### ISSUE THREAD

**Issue by msebrenes** [Azure/acr#612]
**Describe the bug**
After pushing an image with a period the image cannot be untagged neither from the CLI nor the Azure Portal

**To Reproduce**
1. Push an image to ACR with the following structure: <repository>:<tag>. 
2. Try to untag the image from CLI or Azure Portal
3. Tag keeps showing in the repository

**Expected behavior**
After removing the tag it should be gone from the repository

**Screenshots**
None

**Any relevant environment information**
 - Azure CLI latest version
 - Docker in latest version
 - Registry and image names: any name as long as it ends with a period.

**Additional context**
None.

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by juliusl** [comment]
We've investigated this issue and we're working on a fix.
