### ISSUE TITLE
Repository or Registry wide tag immutability

### ISSUE THREAD

**Issue by cvs79** [Azure/acr#616]
**What is the problem you're trying to solve**
I want to be able to prevent image tags from being overwritten. Currently you can disable writing on a repository or specific tag. However, to prevent people from forgetting to do that on an image tag level I would rather have immutability as a feature on registry or at least repository level.

**Describe the solution you'd like**
Deploy an ACR and enable registry wide tag immutability.

**Additional context**
Currently migrating a customer from AWS to Azure and this is a feature that is missing from Azure ACR.

**Comment by northtyphoon** [comment]
@cvs79 ACR allows lock on repository. Is it what you are looking for? 

Use the [az acr repository update](https://docs.microsoft.com/en-us/cli/azure/acr/repository#az_acr_repository_update) command to set repository attributes so you can:

**Lock an image version, or an entire repository**

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-image-lock#lock-a-repository

**Comment by cvs79** [comment]
I want to have repository immutability. So, I don't want to disable writes all together on a repository but rather having a setting that doesnt allow it.

Off course I can build something with a webhook / eventgrid that disables write for a specific tag after a new tag is pushed but it would be nice if it was out of the box functionality instead of needing to build a solution for that
