### ISSUE TITLE
"az acr import" from Docker Hub stuck in Running state

### ISSUE THREAD

**Issue by denisw** [Azure/acr#617]
**Describe the bug**

Since today (May 23, 2022), any attempt to import a container image with `az acr import` hangs forever in the `Running` state. An import with the same registry, image tags, and credentials worked perfectly on the Friday before.

**To Reproduce**

```sh
az acr login -n ${REGISTRY}

az acr import \ 
  --name ${REGISTRY} \
  --source docker.io/library/busybox:stable 
  --image library/busybox:stable \
  --subscription PT-BI-PJ-IOT-Fleet-Dev \
  --force
```

**Expected behavior**

The import finishes and succeeds in a timely manner.

**Any relevant environment information**

Tried both locally (macOS, Azure CLI v2.36.0) and through our Azure DevOps pipeline (managed agent pool, Ubuntu 20.04).

**Additional context**

Tried with several different Docker Hub images, so it is not limited to the `busybox` image mentioned in the example. `docker pull` and `docker push` to ACR works without any problems.

**Comment by northtyphoon** [comment]
@denisw thanks for the reporting the issue and sorry for the inconvenience. We have mitigated an issue that caused image import performance degradation in West Europe. Please check it again if you still run into the issue. Going forward, you can open the opportunity ticket in Azure to escalate such issue.
