### ISSUE TITLE
An error occurred: CONNECTIVITY_CHALLENGE_ERROR

### ISSUE THREAD

**Issue by uttarwar-yogesh** [Azure/acr#619]
**Describe the bug**

**To Reproduce**
1. An error occurred: CONNECTIVITY_CHALLENGE_ERROR
2. ACR 
3. 

**Expected behavior**

**Screenshots**

**Any relevant environment information**
 - OS: [e.g. Ubuntu, Windows] : centos
 - Azure CLI/PowerShell/SDK version : az cli
 - Docker version : 20.10.14
 - Datetime (UTC) when the issue occurred
 - Registry and image names : 

**Additional context**

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by uttarwar-yogesh** [comment]
Docker daemon status: available
Docker version: 'Docker version 20.10.14, build 87a90dc, platform linux/amd64'
Docker pull of 'mcr.microsoft.com/mcr/hello-world:latest' : OK
Azure CLI version: 2.37.0
DNS lookup to pdmcontainer.azurecr.io at IP 10.22.124.13 : OK
An error occurred: CONNECTIVITY_CHALLENGE_ERROR
Registry 'name.azurecr.io' did not issue a challenge.

Please refer to https://aka.ms/acr/errors#connectivity_challenge_error for more information.

**Comment by terencet-dev** [comment]
Hi @uttarwar-yogesh - Closing as this has been inactive for over three months. Please open a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) with our team for assistance.
