### ISSUE TITLE
ACR task fails on empty triggers array in ARM/Bicep template

### ISSUE THREAD

**Issue by nlasok1** [Azure/acr#621]
**Describe the bug**
ACR Task Run fail when ACR Task deployment is provided with empty triggers via ARM deployment.
```
"trigger": {
    "timerTriggers": [],
    "sourceTriggers": []
}

```
If I open logs in the portal I can see something like "_Failed to get run logs for run ID cby._"

**To Reproduce**
Create bicep/ARM template with empty triggers section 

```
resource acrTask 'Microsoft.ContainerRegistry/registries/tasks@2019-04-01' = {
  name: 'adoagent-build-task'
  parent: acr
  location: location
  properties: {
    status: 'Enabled'
    agentConfiguration: {
      cpu: 2
    }
    platform: {
      os: 'Linux'
      architecture: 'amd64'
    }
    step: {
      type: 'Docker'
      contextAccessToken: !empty(ghToken) ? ghToken : null
      contextPath: ghRepositoryUrl
      dockerFilePath: 'Dockerfile'
      imageNames:[
        fullImageName
      ]
      isPushEnabled: true
    }
    trigger: {
      timerTriggers: []
      sourceTriggers:  []
    }
  }
}

```
**Expected behavior**
I would expect the ACR resource provider to handle such cases the same way as if there are no triggers.

**Screenshots**

**Any relevant environment information**

**Additional context**
Advised by MS support. Case 2205200050001111 TrackingID#2205200050001111

**Comment by northtyphoon** [comment]
The fix has been deployed.
