### ISSUE TITLE
ACR deployment fails with zone redundancy enabled when using ARM/Bicep and deployment mode Complete

### ISSUE THREAD

**Issue by mhous** [Azure/acr#623]
**Describe the bug**
Attempted to deploy an ACR instance, with zone redundancy enabled and deployment mode Complete.  Activity logs for the deployment show many failed/successful events around Delete Replication, but deployment ultimately fails after an extended period.  In contrast, deployments work correctly and quickly with deployment mode Incremental, and deployment mode Complete does work with zone redundancy disabled.

**To Reproduce**
1. With the attached bicep, execute: az deployment group create --resource-group $resourceGroup --mode Complete --template-file acr.bicep --parameters acrName=$acrName acrSkuName=Premium acrZoneRedundancy=Enabled

**Expected behavior**
Expect a timely execution and successful deployment of an Azure Container Registry.

**Screenshots**
Screenshot of the deployment Activity Log:
![image](https://user-images.githubusercontent.com/14985478/171738243-044b2b35-e760-412f-a0ba-4fb30711ccbc.png)

**Any relevant environment information**
 - OS: Windows
 - Azure CLI: 2.37.0

**Additional context**
N/A
[acr.bicep.txt](https://github.com/Azure/acr/files/8827863/acr.bicep.txt)

**Comment by terencet-dev** [comment]
Hi @mhous - Closing as this has been inactive for over three months. Please open a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) with our team for assistance.
