### ISSUE TITLE
An error occurred: CONNECTIVITY_CHALLENGE_ERROR Registry '*****.azurecr.io' did not issue a challenge.

### ISSUE THREAD

**Issue by brightonk** [Azure/acr#628]
has anyone faced the issue. How did you resolve

== I used the below command. The output is below the command ==

$ az acr check-health -n ********Containers --yes
Docker daemon status: available
Docker version: 'Docker version 20.10.8, build 75249d8, platform linux/arm64'
Docker pull of 'mcr.microsoft.com/mcr/hello-world:latest' : OK
Azure CLI version: 2.37.0
DNS lookup to ********containers.azurecr.io at IP 52.236.191.0 : OK
An error occurred: CONNECTIVITY_CHALLENGE_ERROR
Registry '*********.azurecr.io' did not issue a challenge.

Please refer to https://aka.ms/acr/errors#connectivity_challenge_error for more information.

== the link above gave the details below ==

CONNECTIVITY_CHALLENGE_ERROR
This error means that the challenge endpoint of the target registry did not issue a challenge.

Potential solutions: Try again after some time. If the error persists, open an issue at https://aka.ms/acr/issues.

**Comment by hluckenbaugh** [comment]
I am having the same issue.

**Comment by OlaNystein** [comment]
I have the exact same problem. It worked on friday, but error suddenly happened when trying to login to acr this monday.

**Comment by williamcollin** [comment]
I'm having the same issue.

**Comment by OlaNystein** [comment]
It fixed itself after a day, still don't know why the error occured

**Comment by marouanabbessi** [comment]
I have the same exact problem, this has persisted for many days: I am trying to login to a private ACR through a private edpoint.

<img width="1264" alt="Screenshot 2022-08-22 at 15 45 46" src="https://user-images.githubusercontent.com/3102093/185936534-f25cb63c-e14d-4bb7-81aa-b9c2afc6875b.png">

**Comment by stevenpedroza** [comment]
I have the same error

**Comment by sajayantony** [comment]
Please open a support ticket through the portal and provide the details like region and the registry so that the issue can be routed and diagnosed.

**Comment by stevenpedroza** [comment]
I found my solution, try to put the agent inside the same subnet as the private point. If you don't have it like that, you have to create a link between the networks.

You have to check that in ACR->Networking->Private Access->Private endpoint (We click on it)

We go to DNS configuration, and copy the private ip that has the FQDN, example myacrr312.privatelink.azurecr.io = IP:10.0.0.5.

Later in the same window, in private DNS zone, you have to click on the name that appears in blue.

It has to be the Registry name and the IP 10.0.0.5 (in my case). If not, you have to add yours manually in the Record Set.

All the best.

**Comment by marouanabbessi** [comment]
I was accessing ACR through a user-assigned managed identity, it was working fine until all of the suddent , the registry no longer intitiate identity challenge which was failing the login, now I had to resort to enabling admin credentials (username and password) instead , so this does not seem to have a problem with the fact that it is accessed through a privare endpoint, verw eird situation with very cryptic error message

**Comment by terencet-dev** [comment]
Closing as this has been inactive for over two months. Please open a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) for additional support/guidance. Thanks

**Comment by marouanabbessi** [comment]
@terencet-dev you are quick to close this, could you offer an explanation why this error occurs ? this has occurred another time to me now, please check internally and provide an explanation  for why this error occurs intermittently

**Comment by helayoty** [comment]
Issue still occurs with az version 2.49.0 @terencet-dev
