### ISSUE TITLE
Warning: failed to get default registry endpoint from daemon

### ISSUE THREAD

**Issue by rich-davies** [Azure/acr#63]
I have created a new Container Registry and, using the Cloud Shell, am unable to connect to it using **az acr login --name <registryname>**.
I get the following message:
"Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?). Using system default: https://index.docker.io/v1/
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

**Comment by SajayAntony** [comment]
Cloud shell does not support docker commands and hence you cannot run any docker daemon related commands like `docker login` or `docker run`. ACR login command will actually call one of these and the error what you are seeing is the limitation of cloud shell. 
Was there documentation that indicates this would work? If so we should get that fixed.

**Comment by rich-davies** [comment]
I'm following the tutorial [here](https://docs.microsoft.com/en-us/azure/container-service/kubernetes/).  The Quicklab says that all actions can be done using the cloud shell but, to be fair, the tutorial doesn't make the same assertion.  Maybe an update to the tutorial pages to warn people off Cloud Shell?

**Comment by mmacy** [comment]
Thanks for the notification on this, @rich-davies.

As @SajayAntony mentions, this isn't an ACR issue, per se, but rather part of a larger issue we're addressing on the documentation side. We’ve removed the Cloud Shell messaging from some articles which cannot be completed totally within the Cloud Shell, and are continuing to do so where it makes sense.

I have a PR open in our documentation repo to address this issue.

**Comment by mmacy** [comment]
@rich-davies Hi Rich, we have added the following text to the first tutorial in both the ACS and ACI documentation sets. You can find it in the [Before you begin](https://docs.microsoft.com/azure/container-service/kubernetes/container-service-tutorial-kubernetes-prepare-app#before-you-begin) section of both.

`Azure Cloud Shell does not include the Docker components required to complete every step this tutorial. Therefore, we recommend using a full Docker development environment.`

Please let us know if this resolves this issue, thanks. -MM

Cc: @SajayAntony @neilpeterson

**Comment by SajayAntony** [comment]
ACS docs published. Closing for now.
