### ISSUE TITLE
Is it possible to set the default docker buildx step time-out higher then 600 seconds?

### ISSUE THREAD

**Issue by corwestermaniddink** [Azure/acr#630]
![image](https://user-images.githubusercontent.com/37871320/175300891-387eeb07-f2cc-4157-b5bc-77fd91761afb.png)

I'm building a multi-architectural (arm64 and amd64) docker image with buildx with a ACR quick-run. Unfortunately the time to build the arm64 (emulation done by QEMU on the ACR Build Agent) part is taking longer then 10min (one of the reasons we want todo this async by ACR).

Is there support to change the default time-out for this step in the building process? (I think it's a docker configuration setting)

**Comment by northtyphoon** [comment]
You can use the timeout property

- cmd: abc... 
  timeout: 1800

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-reference-yaml#task-step-properties

**Comment by corwestermaniddink** [comment]
```
version: v1.1.0

steps:
- cmd: buildx create --use 
- cmd: buildx build --platform linux/arm64 --build-arg MODE='development' -f dockerfiles/shell.Dockerfile -t {{.Run.Registry}}/fe-shell-acr:latest --push .
  timeout: 1800
```
Works 👍 

Thanks!
