### ISSUE TITLE
Cannot delete ACR repo with tag count and manifest count 0

### ISSUE THREAD

**Issue by Akshay04** [Azure/acr#631]
We regularly cleanup our ACR repositories using az cli and we started getting errors deleting repositories:
"azure.cli.command_modules.acr._docker_utils.RegistryException: Error: repository name not known to registry. Correlation ID: 530afbd4-2a76-4a52-b70f-890dac6b46ce"

When I opened the acr on azure portal and tried to delete the problematic repositories, I got this error:
<img width="371" alt="image" src="https://user-images.githubusercontent.com/12955023/176800028-d95a5803-87eb-4dcd-984c-fbe511d7efe8.png">

I noticed all the problematic repositories had tag count and manifest count 0. I could only delete the repository after pushing new images to these repositories.

**Comment by terencet-dev** [comment]
Closing as this has been inactive for over three months. Please reopen this issue if you would like additional guidance.
