### ISSUE TITLE
Import command response InvalidParameters, but no more details

### ISSUE THREAD

**Issue by jxnkwlp** [Azure/acr#632]
**Describe the bug**
import command response `Code: InvalidParameters` and message `Error copying blobs` , but no more error details . 

**To Reproduce**
use command ` az acr import  --name xxx --source xxx/library/xxxx:1.0  --image xxx:1.0   -u xxx  -p xxx   --debug`

**Expected behavior**
Can be show more error details.

**Screenshots**
![image](https://user-images.githubusercontent.com/8208357/177910035-00a0b115-b1a0-4467-906d-67b38f0e9376.png)

**Any relevant environment information**
 - OS: Windows 10
 - Azure CLI : 2.38.0
 - Docker version: none 
 - Datetime (UTC) when the issue occurred :  2022-07-08 3:18:28 AM

**Additional context**

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by Wwwsylvia** [comment]
Thanks @jxnkwlp for reporting this! We will review this experience and see if we can improve the error message.

**Comment by gangefors** [comment]
What are the root causes of this error? I am seeing this when I try to import an image from an external docker registry.

**Comment by Wwwsylvia** [comment]
Hi @gangefors, the root causes vary. To further investigate, you may create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to [acrsup@microsoft.com](mailto:acrsup@microsoft.com), and we can check our internal logs if we have the registry name, repository name, and timestamp, etc.
