### ISSUE TITLE
ACI connection to private ACR

### ISSUE THREAD

**Issue by romanzdk** [Azure/acr#633]
We need to set ACR to be available only to selected networks (not public access).

However, when we set this, ACI is not able to pull image from the ACR. 

How to solve this?

EDIT: 
ACI says: 
```
Failed to pull image "<acrname>.azurecr.io/<imagae-name>:02b6d84d635c3d9ff4182ad1c50d16364695d3d5": rpc error: code Unknown desc Error response from daemon: Head "https://<acrname>.azurecr.io/v2/<image-name>/manifests/02b6d84d635c3d9ff4182ad1c50d16364695d3d5": denied: client with IP 'x.x.x.x' is not allowed access. Refer https://aka.ms/acr/firewall to grant access.
```

Is there any way how to find out that IP address so I can add it to the allowed IPs of the ACR? I mean any "normal" way to get the address, not manually looking into ACI logs.

**Comment by sajayantony** [comment]
Please see if this works for you - https://docs.microsoft.com/en-us/azure/container-instances/using-azure-container-registry-mi#configure-registry-authentication
