### ISSUE TITLE
docker push unauthorized: authentication required even after successful login

### ISSUE THREAD

**Issue by LudwigNel** [Azure/acr#634]
**Describe the bug**
I am experiencing an issue pushing an updated image to an Azure Container Registry.
I was able to do this yesterday but I now keep getting unauthorized: authentication required when running the docker push command in the Azure CLI

I have tried az login
az acr login
docker login as well

None of those seem to make a difference

**To Reproduce**
1. az login
2. az acr login
3. docker images - to get the image name I want to push
4. docker push

The result being unauthorized: authentication required

**Screenshots**
<img width="610" alt="image" src="https://user-images.githubusercontent.com/14205687/179194134-12845b40-8f78-4cba-a30f-346ba26f0db9.png">

**Any relevant environment information**
 - OS: Windows 11
 - 
 - Azure CLI/PowerShell/SDK version
   "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}

 - Docker version
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:17:07 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.9.0 (80466)
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:15:42 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by Wwwsylvia** [comment]
Hi @LudwigNel, could you help to confirm the following:
* What is the result of running `az acr check-health -n $registry --debug`?
* Have you recently made any changes to the permission of your account?
* Are you able to pull images from the same registry?

Could you check if this article helps? [Troubleshoot registry login](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-troubleshoot-login)

**Comment by terencet-dev** [comment]
Closing as this has been inactive for over three months. Please reopen this issue if you would like additional guidance.
