### ISSUE TITLE
Is the ACR 200 private endpoint limitation a hard technical limit on the service?

### ISSUE THREAD

**Issue by LefeWareSolutions** [Azure/acr#643]
Hello I am currently working with a very large organization who has requested a limit closer to 1000 private endpoints for the ACR. 

They have over 700 clusters and wish to have a centralized container registry to pull common images such as NGINX, LinkerD etc. privately as opposed to going over the public internet. This way instead of doing a bunch of ugly and complicated peering, they can just establish private links via different networks and subscriptions.

I will go through proper channels to make this request, but before doing so I just want to ensure that the 200 limit is not a technical limit. As in upping this limit would require a product redesign? Or is this limit something that can be upped for certain clients?

**Comment by toddysm** [comment]
There are certain technical limitations that we need to deal with for higher numbers. We consider 200 a safe limit that customer can use without any impact on their registries. Would you mind submitting an official support request for this.
