### ISSUE TITLE
registry CONNECTIVITY_CHALLENGE_ERROR error

### ISSUE THREAD

**Issue by tetlika** [Azure/acr#645]
**Describe the bug**
We are getting CONNECTIVITY_CHALLENGE_ERROR when doing `az acr check-health -n nimblecr`

**To Reproduce**
From any server we see this:
az acr check-health -n nimblecr
Docker daemon status: available
Docker version: Docker version 19.03.9, build 9d988398e7
This will pull the image mcr.microsoft.com/mcr/hello-world:latest. Proceed? (y/n): y
Docker pull of 'mcr.microsoft.com/mcr/hello-world:latest' : OK
Azure CLI version: 2.4.0
DNS lookup to nimblecr.azurecr.io at IP 172.30.2.6 : OK
An error occurred: CONNECTIVITY_CHALLENGE_ERROR
Registry 'nimblecr.azurecr.io' did not issue a challenge.

Please refer to https://aka.ms/acr/errors#connectivity_challenge_error for more information.

**Any relevant environment information**
 - OS: ANY
 - Docker - any

**Comment by terencet-dev** [comment]
Hi @tetlika,

Have you opened a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) with our team yet?

Thanks,
-TT

**Comment by terencet-dev** [comment]
Closing as this has been inactive. Please open a [support ticket](https://azure.microsoft.com/support/create-ticket/) with our team for assistance.
