### ISSUE TITLE
How to use the v2 rest api?

### ISSUE THREAD

**Issue by jonathan-boudreau-work** [Azure/acr#646]
**Describe the bug**
Documentation seems to be out of date or inaccurate when it comes to the authentication steps.

**To Reproduce**
1. Read [documentation](https://github.com/Azure/acr/blob/main/docs/AAD-OAuth.md)
2. Authenticate azure-cli
3. Look for `$HOME/.azure/accessTokens.json` file
4. it is not there

**Expected behavior**
Documentation is accurate and up to date.

**Screenshots**

**Any relevant environment information**
 - OS: Mac
 - Azure CLI/PowerShell/SDK version 2.40.0
 - Docker version 20.10.17
 - Datetime (UTC) when the issue occurred Thu 15 Sep 2022 03:44:52 PM UTC
 - Registry and image names

**Additional context**

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by terencet-dev** [comment]
Closing as this has been inactive. Please open a [support ticket](https://azure.microsoft.com/support/create-ticket/) with our team for assistance.
