### ISSUE TITLE
Azure REST API reference regarding scope maps

### ISSUE THREAD

**Issue by Manbearpiet** [Azure/acr#652]
**Describe the bug**
In Microsoft Learn/Docs the examples are defined in az cli, however we can't find documentation on the Azure REST Interface about scope maps at [Learn/Docs](https://learn.microsoft.com/en-us/rest/api/containerregistry/)

**Expected behavior**
A clear and concise description of what functionality REST offers regarding to scope maps and some examples.

**Comment by Manbearpiet** [comment]
I did manage to dig up:
https://management.azure.com/subscriptions/c72a198b-214b-4356-bcd0-b5d8d1e523ff/resourceGroups/iamfalsified/providers/Microsoft.ContainerRegistry/registries/nosecrets4u/scopeMaps?api-version=2020-11-01-preview

I hope we can get some official docs soon though :)

**Comment by terencet-dev** [comment]
Hi @Manbearpiet,

Thanks for raising this to us. ACR Tokens and Scope Maps is still in Public Preview and are working towards adding additional documentation.

**Comment by johnsonshi** [comment]
Hi @Manbearpiet,

This feature is still in public preview and does not have public REST API docs yet. When this feature GAs, which will be in Q1-Q2 of the year, then we will publish REST API documentation. Thank you!
