### ISSUE TITLE
Registry caching

### ISSUE THREAD

**Issue by terencet-dev** [Azure/acr#656]
Registry Caching is an integrated way to cache public artifacts in your ACR instance, even if it's in a private network. This enables you to further secure your network (removing access to Docker Hub) and begin treating your artifacts in a secure manner.

**Comment by MSFTPM12** [comment]
Hello Everyone, 

I am on the Azure Container Registry PM Team. This feature is still on track.

**Comment by luisdlp** [comment]
Public preview is now available : https://techcommunity.microsoft.com/t5/apps-on-azure-blog/announcing-public-preview-of-caching-for-acr/ba-p/3744655

**Comment by Sidewinder53** [comment]
Docs state that during preview, the Caching features is not supported on CMK-enabled registries. Could you clarify when this limitation will be lifted or if this feature will be GA before end of September when Docker Hub rate limits come in effect? Thank you!

**Comment by kevinharing** [comment]
When this will become GA? Looking at the docker hub dead-line of September 30th, we'll need to use this in production soon. Is it ready for that?

**Comment by kleinmt** [comment]
@terencet-dev @JXavierMSFT @luisdlp 
We've reached out to Azure support and have been told that the PG doesn't have a date for GA of this feature. Does this mean, we'll have to implement a custom solution to avoid hitting rate limits with our CMK-enabled registries? We'd like to avoid issuing personalized access tokens to authenticate pulls from AKS.

**Comment by davidkarlsen** [comment]
It is annoying that you need to define a cache-rule for each and every repo - having a wildcard like docker.io/* mapping over to a prefix of docker.io/ within ACR would scale a lot better.

**Comment by m-soltani** [comment]
it seems that the docker hub credential sets are not working. I am seeing an error referring to a missing rate limit header

![Image](https://github.com/user-attachments/assets/c6be3d0d-dae4-4214-9d74-3d27fc8af982)
