### ISSUE TITLE
Unable to login to Azure Container registry

### ISSUE THREAD

**Issue by prasadaws10** [Azure/acr#659]
Hi Team, 

I am trying to login to my container registry and see the below error.

Could not connect to the registry login server 'myacr.azurecr.io'. Please verify that the registry exists and the URL 'https://myacr.azurecr.io/v2/' is reachable from your environment.
Try running 'az acr check-health -n myacr --yes' to diagnose this issue.

Health Check Log: 

2022-12-06 21:00:21.870449 An error occurred: CONNECTIVITY_CHALLENGE_ERROR
Registry 'myacr.azurecr.io' did not issue a challenge.

Please refer to https://aka.ms/acr/errors#connectivity_challenge_error for more information.

Thank You,
Prasad

**Comment by V3N3Z14** [comment]
Hi I have the same problem but I didnt fine solution I think it is a permition problem.

**Comment by terencet-dev** [comment]
Hi @prasadaws10, please open a [support ticket](https://azure.microsoft.com/support/create-ticket/) for our team to investigate. Thanks!

**Comment by terencet-dev** [comment]
Please open a [support ticket](https://azure.microsoft.com/support/create-ticket/) for our team to investigate. Thanks!
