### ISSUE TITLE
Linking Github check-ins to auto generate ACR images

### ISSUE THREAD

**Issue by sursani** [Azure/acr#66]
Can I link my github check-ins to automatically generate docker images in the azure container registry? This functionality is provided by Google Cloud Platform so I was wondering if Azure provides it as well.

**Comment by SajayAntony** [comment]
This is not currently supported but is mentioned in our roadmap- https://github.com/Azure/acr/blob/master/docs/acr-roadmap.md#auto-build-with-os--framework-patching

**Comment by sajayantony** [comment]
ACR Build is currently in preview and is planned for GA soon.

**Comment by SteveLasker** [comment]
Https://aka.ms/ACR/build
