### ISSUE TITLE
Allow anonymous `metadata/read` 

### ISSUE THREAD

**Issue by NinadKavimandan** [Azure/acr#663]
**What is the problem you're trying to solve**

ACR today allows anonymous pull, enabling customers to use their ACR as a public registry. As a consumer of such ACRs, I am trying to setup a process that would periodically list and pull newly updated image versions. The thing that blocks me from having such automation around is the inability to perform `v2/<image>/tags/list` without having some access on the ACR. While tried to reach out to the ACR owner, got to know there was no provision to allow anonymous `metadata/read`. That being said, I can get myself unblocked by getting access to the concerned ACRs, but having ability to list tags would be a great value add.

**Describe the solution you'd like**

Ability to allow anonymous `metadata/read`.

**Comment by nirmaldevi** [comment]
I am also interested in this feature.

**Comment by northtyphoon** [comment]
@NinadKavimandan you mentioned you want anonymous feature to support `v2/<image>/tags/list`. It is already supported. Can you clarify what issue you encountered? I shared a sample script you can try on your own registry with anonymous pull enabled. 

```
accept_header="Accept: application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, application/vnd.oci.artifact.manifest.v1+json,*/*"
registry="myregistry.azurecr.io"
repo="myrepro"
scope="repository:$repo:pull"

#curl -v -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=password&service=$registry&scope=$scope" "https://$registry/oauth2/token"

acr_access_token=$(curl -v -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=password&service=$registry&scope=$scope" "https://$registry/oauth2/token" | jq -r ".access_token")
curl -v -H "Authorization: Bearer $acr_access_token" -H "$accept_header" https://$registry/v2/$repo/tags/list | jq
```

**Comment by nirmaldevi** [comment]
Can you also send me the script. Just to confirm, we are talking about Anonymous read of contents in registry. Not anonymous pull of a tagged image.

**Comment by aednichols** [comment]
I am also interested in this feature. My "expected result" is that a request to my public repo like this one works without auth.

```
curl --request GET \
  --url https://workflowsdevpublic.azurecr.io/v2/cromwell/manifests/88-020fb1a-DEBUG \
  --header 'Accept: */*, application/vnd.oci.artifact.manifest.v1+json, application/vnd.cncf.oras.artifact.manifest.v1+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json' \
  --header 'Accept-Encoding: gzip, deflate' \
  --header 'Connection: keep-alive' \
  --header 'Host: workflowsdevpublic.azurecr.io'
```
```
{
	"errors": [
		{
			"code": "UNAUTHORIZED",
			"message": "authentication required, visit https://aka.ms/acr/authorization for more information.",
			"detail": [
				{
					"Type": "repository",
					"Name": "cromwell",
					"Action": "pull"
				}
			]
		}
	]
}
```
