### ISSUE TITLE
Microsoft.ContainerRegistry/registries/tokens incremental resource deployment is wiping token passwords

### ISSUE THREAD

**Issue by oleksandr9379992** [Azure/acr#667]
**Bicep version**
Bicep CLI version 0.13.1 (e3ac80d678)

**Describe the bug**
The following bicep code incremental deployment is wiping passwords for the tokens.
```bicep
targetScope = 'resourceGroup'

param acrTokenName string
param acrScopeMapName string
param acrName string


resource acr 'Microsoft.ContainerRegistry/registries@2021-09-01' existing = {
  name: acrName
}

resource adminScopeMap 'Microsoft.ContainerRegistry/registries/scopeMaps@2022-02-01-preview' existing = {
  name: acrScopeMapName
  parent: acr
}

resource acrAdminUserToken 'Microsoft.ContainerRegistry/registries/tokens@2022-02-01-preview' = {
  name: acrTokenName
  parent: acr
  properties: {
    scopeMapId: adminScopeMap.id
  }
}

```
```
module acrUserTokenAdmin '../modules/acr-token.bicep' = {
  scope: resourceGroup(acrRgName)
  name: 'acrUserTokenAdmin-${dateTimeToEpoch(dateTimeNow)}'
  params: {
    acrName: acrName
    acrScopeMapName: '_repositories_admin'
    acrTokenName: '${acrName}-user-admin'
  }
  dependsOn: [
    acr
  ]  
}

````

**To Reproduce**
1. Create the token with the code provided above. Any api version. ` az deployment sub create`
2. Open the portal and create password for the token:
![image](https://user-images.githubusercontent.com/121581428/216152890-ffd8c164-75d2-4267-a767-11039a46745d.png)
3. Run the same bicep code again ` az deployment sub create`
4. See that password disappeared.
![image](https://user-images.githubusercontent.com/121581428/216153604-74aa995b-93d7-418a-8829-2577cf2d7415.png)

**Additional context**
I would expect, that incremental deployments never wipe generated passwords.

**Comment by terencet-dev** [comment]
Closing as this issue is now inactive for over 7 days. Thanks!
