### ISSUE TITLE
ACR Taking Unwanted Space

### ISSUE THREAD

**Issue by ankit-unicloud** [Azure/acr#669]
Hi Team,

In our ACR we have only two images and size of each image has 1.5 GB but in ACR showing usage 62 GB please let me know how we can resolve this issue. Thanks

**Comment by terencet-dev** [comment]
Hi @ankit-unicloud,

Please open a [support ticket](https://azure.microsoft.com/support/create-ticket/)  with our team to investigate as this board is primarily used to provide roadmap updates. If you don’t have any additional questions here, this issue will close in 7 days. Thanks!

**Comment by terencet-dev** [comment]
Closing as this issue is now inactive for over 7 days. Thanks!
