### ISSUE TITLE
az acr login failing over a private endpoint

### ISSUE THREAD

**Issue by chammik** [Azure/acr#672]
**Describe the bug**
Executing az acr login --name acrname fails with below error.
Error response from daemon: Get "https://acrname.azurecr.io/v2/": writing response to acrname.azurecr.io:443: parsing port : strconv.ParseInt: parsing "": invalid syntax

A packet capture shows that the acr returning an HTTP 500 Internal Server Error.

**To Reproduce**
1. Execute az acr login --name acrname on PowerShell, with a container that has a private endpoint.

**Expected behavior**
Login to the acr successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/87511715/221105374-b6f0088c-96a9-4476-93c5-f8568eab58c4.png).
![image](https://user-images.githubusercontent.com/87511715/221105796-a8cf5593-33a5-40e2-a668-afcee1f22d1d.png)

**Any relevant environment information**
 - OS: Windows
 - PowerShell

**Additional context**
Logging into the same registry works fine over the public endpoint. No connectivity issues between the client and the private endpoint.

**Comment by terencet-dev** [comment]
Hi @chammik,

Please open a [support ticket](https://azure.microsoft.com/support/create-ticket/)  with our team to investigate as this board is primarily used to provide roadmap updates. If you don’t have any additional questions here, this issue will close in 7 days. Thanks!

**Comment by terencet-dev** [comment]
Closing as this issue is now inactive for over 7 days. Thanks!
