### ISSUE TITLE
Cannot list registry with metadata/read and content/read permissions

### ISSUE THREAD

**Issue by hayk99** [Azure/acr#675]
**Describe the bug**
I am doing a couple of tests with Azure Registry Container. My goal is to be able to list the whole registry with a token that has a scope map with the following setup. 

After creating this token I tried to list all the registry by triggering a get to the` /_catalog` and got this error
```
GET https://testregistryscanner.azurecr.io/v2/_catalog?n=1000: UNAUTHORIZED: authentication required, visit https://aka.ms/acr/authorization for more information.; [map[Action:* Name:catalog Type:registry]]
```
This workflow does not throw the above error if I use **_repositories_admin** (azure manged) scope map.

**To Reproduce**

1. Create a scope map and assign it to a token with the following setup
<img width="1474" alt="repo-by-repo" src="https://user-images.githubusercontent.com/21331737/222376763-04c9900f-c077-4655-9035-c3d08123a0e5.png">

> A small note regarding the scope map creation: it will be great to have wildcards like "*" so the user can specify the permission to the whole registry instead of going one repository by one (imaging large registries).
2. Use the token to authenticate against the API

**Expected behavior**
It would be great to be able to list the whole registry with `metada/read `and `content/read` permissions.

**Screenshots**

**Any relevant environment information**
 - OS: MacOS
 - SDK version 
 - Docker version 20.10.16
 - Registry and image names

**Additional context**
Trying to fetch repositories using the docker v2 API 

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by terencet-dev** [comment]
Hi @hayk99,

Please open a [support ticket](https://azure.microsoft.com/support/create-ticket/)  with our team to investigate as this board is primarily used to provide roadmap updates. If you don’t have any additional questions here, this issue will close in 7 days. Thanks!

**Comment by hayk99** [comment]
Thank you!

**Comment by terencet-dev** [comment]
Closing as this issue is now inactive for over 7 days. Thanks!
