### ISSUE TITLE
Expose dSTS-based endpoint for ACR authentication

### ISSUE THREAD

**Issue by kaitlynyang** [Azure/acr#677]
**What is the problem you're trying to solve**
My team is currently using the ACR supported username/password authentication model as a stopgap solution to read Docker credentials, where these credentials are stored in AKV. However, our service should not depend on AKV, and would like to also find a way to authenticate without needing an AAD token, which is needed for most of the AAD auth methods that are currently supported. 

**Describe the solution you'd like**
We're wondering if other mechanisms such as dSTS could be supported for 1P applications through exposing a dSTS-based endpoint.

**Comment by terencet-dev** [comment]
Closing this issue as we have a separate email thread about this
