### ISSUE TITLE
ACR Login Issue

### ISSUE THREAD

**Issue by kevinevans1** [Azure/acr#680]
**Describe the bug**
Unable to login into azure container registry using the 'az acr login command'

**To Reproduce**
1. az login (success)
2. running the az acr login command 'az acr login --name acrlab10'
3. receive the following error 'Error saving credentials: error storing credentials - err: exit status 1, out: `error getting credentials - err: exit status 1, out: `no usernames for acrlab10.azurecr.io`
Login failed.'

**Expected behavior**
Should be able to login to azure container registry using azure AD RBAC

**Screenshots**
screen shot attached

**Any relevant environment information**
 - OS: Fedora 37 (6.2.8-200.fc37.x86_64)
 - Azure CLI/PowerShell/SDK version : 2.46.0
 - Docker version 23.0.2, build 569dd73
 - Datetime (UTC) when the issue occurred: 12:00 PM
 - Registry and image names : acrlab10
![Screenshot from 2023-04-02 12-04-12](https://user-images.githubusercontent.com/68919619/229370694-28248906-a93e-42b2-8b08-1ffecdfadd4e.png)

**Comment by kevinevans1** [comment]
resolved by installing the ACR helper
https://github.com/Azure/acr-docker-credential-helper

**Comment by sajayantony** [comment]
@kevinevans1 - That credential helper is not being maintained and should not be required. Could you please open a support ticket so that we can follow up.

**Comment by kevinevans1** [comment]
@sajayantony re-opened as requested

**Comment by terencet-dev** [comment]
Hi @kevinevans1,

Please open a [[support ticket](https://azure.microsoft.com/support/create-ticket/)](https://azure.microsoft.com/support/create-ticket/) with our team to investigate as this board is primarily used to provide roadmap updates. Closing this issue here so we can track through the support ticket.

**Comment by sumit-anantwar** [comment]
Behaving the same for me. 
I was struggling for a few hours to login, finally succeeded using the helper.
OS: Ubuntu 22.04.3 LTS
az-cli version
```
$ az -v
azure-cli                         2.53.1

core                              2.53.1
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/leo/.azure/cliextensions'

Python (Linux) 3.10.10 (main, Oct 24 2023, 06:10:14) [GCC 11.4.0]

Legal docs and information: aka.ms/AzureCliLegal
```
