### ISSUE TITLE
Cache Harbor Repositories

### ISSUE THREAD

**Issue by JXavierMSFT** [Azure/acr#682]
Caching for ACR will soon allow users to cache repositories from Harbor. This functionality is scheduled for release in late July 2023.

**Comment by JXavierMSFT** [comment]
Hello Everyone, 

Unfortunately, we won't be able to ship Harbor as an available upstream this month. I will update this thread when I have a new accurate Timeline.

**Comment by ncrmro** [comment]
@JXavierMSFT any word on this?
