### ISSUE TITLE
Cannot connect to ACR

### ISSUE THREAD

**Issue by yargolan** [Azure/acr#691]
**Describe the bug**
I have a '**contributor**' access over the relevant subscription.
However, when I try to get the list of the repositories in the ACR, I get the following error message:
Could not connect to the registry login server 'MY_ACR_NAME.azurecr.io'. Please verify that the registry exists and the URL 'https://MY_ACR_NAME.azurecr.io/v2/' is reachable from your environment.

**To Reproduce**
1. az login
2. az account set --subscription MY_SUB_ID
3. az acr repository list --name MY_ACR_NAME

**Expected behavior**
A json holding the names of the repositories under the relevant ACR

**Any relevant environment information**
 - OS: mac 12.6.5 (Montrye) 
 - Azure CLI/PowerShell/SDK version: 2.46.0
 - Docker version:  2.0.10.23
 - Datetime (UTC) when the issue occurred: 13:00 (GMT+3)
 - Registry and image names

**Additional context**

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by trisavo** [comment]
What is the name of your registry? I will investigate this issue.

**Comment by yargolan** [comment]
Update:
The command runs flawlessly from the CLI.
When I try to run the same command from PyCharm using subprocess library it fails.
When running the python code from CLI, it runs as needed as well.
I figured out that the issue is based in the PyCharm.

You may close the ticket.
