### ISSUE TITLE
Creating container registry in UK South

### ISSUE THREAD

**Issue by gustavo-armenta** [Azure/acr#70]
I get this error

    "properties": {
        "statusCode": "BadRequest",
        "serviceRequestId": null,
        "statusMessage": "{\"error\":{\"code\":\"NoRegisteredProviderFound\",\"message\":\"No registered resource provider found for location 'uksouth' and API version '2016-06-27-preview' for type 'registries'. The supported api-versions are '2016-06-27-preview, 2017-03-01, 2017-10-01, 2017-06-01-preview'. The supported locations are 'westus, eastus, southcentralus, westeurope, northeurope, uksouth, ukwest, australiaeast, australiasoutheast, centralindia, eastasia, japaneast, japanwest, southeastasia, southindia, brazilsouth, canadaeast, canadacentral, centralus, eastus2, northcentralus, westcentralus, westus2'.\"}}"
    },

**Comment by gustavo-armenta** [comment]
I was using 2016-06-27-preview, it worked fine after updating to 2017-10-01

**Comment by sajayantony** [comment]
Closing as the API version should be `2017-10-01`
