### ISSUE TITLE
ACR Webhook getting 401 while calling app service Webhook URL integrated with vnet

### ISSUE THREAD

**Issue by sanjaydebnath** [Azure/acr#701]
**Describe the bug**
We have an app service running docker image inside a vnet/subnet. The app service pulls image from a network restricted ACR via private endpoint using MSI, the image pull works fine. But now we tried to configure a webhook in the ACR that will push the latest image as on when available. But it seems the ACR webhook is not able to reach the SCM endpoint of the web app and failing with 401 unauthorized. 

**To Reproduce**
1. Create a ACR & disable public access. Enable private link with private dns zone etc in the app service vnet
2. Configure app service to pull image from acr using a predefined MSI (e.g. this blog has details: https://azure.github.io/AppService/2021/07/03/Linux-container-from-ACR-with-private-endpoint.html)
3. Create a web hook in the ACR using the app service deployment webhook endpoint & try to ping the web hook

**Expected behavior**
ACR web hook should be able to reach the app service webhook endpoint (SCMendpoint eventually)

Is there any way today for ACR to reach the SCM endpoint if we are using vnet integration for app service?

Non vnet one works fine as described here: https://learn.microsoft.com/en-us/azure/app-service/tutorial-custom-container?tabs=azure-cli&pivots=container-linux

![image](https://github.com/Azure/acr/assets/28987981/8c651782-1f6b-481d-a069-b9a0c29fa646)

**Edit:** It seems this issue has no relation with vnet, even a simple web app with docker image linked with an ACR fails to ping the web app's webhook. Any idea what's missing here?

Simple web app with ACR integrated using admin key...
![image](https://github.com/Azure/acr/assets/28987981/c5475313-76d6-423e-a044-158e31aa1682)

ACR with the hook end point copied from above
![image](https://github.com/Azure/acr/assets/28987981/90d62ca8-f61c-4cda-9cf2-bdd1cb26effa)

**Comment by terencet-dev** [comment]
Hi @sanjaydebnath,

Apologies for the delayed response. Please open a [[support ticket](https://azure.microsoft.com/support/create-ticket/)](https://azure.microsoft.com/support/create-ticket/) with our team to investigate as this board is primarily used to provide roadmap updates. If you don’t have any additional questions here, this issue will close in 7 days. Thanks!
