### ISSUE TITLE
Begin managing public content with Azure Container Registry

### ISSUE THREAD

**Issue by kmmdev** [Azure/acr#702]
Hi,

MS has suggested to use Cache for ACR. •	
If you use Docker Hub, you may be affected by Docker rate limiting beginning 30 September 2023.

I have azure pipelines (Self-Hosted agents) building Docker images which pulls various base images based on requirements from third-party registries. Does this change affect the pipelines too ?

**Comment by luisdlp** [comment]
If your pipelines are pulling directly from DockerHub, yes, they could be impacted.  We recommend caching these images like suggested here: https://learn.microsoft.com/en-us/azure/container-registry/tutorial-registry-cache

**Comment by terencet-dev** [comment]
Closing as this has been inactive for over 30 days. Please open a [support ticket](https://azure.microsoft.com/support/create-ticket/) with our team for assistance.
