### ISSUE TITLE
Provide feedback on cache feature

### ISSUE THREAD

**Issue by madeiza** [Azure/acr#704]
Posting this here for those who are using ACR cache or are interested in cache. 

We are looking for a few folks to provide feedback on their experience of using cache in ACR and/or features they would like to see in future releases. 

Please complete this form if interested: https://forms.office.com/r/raEfsAiJG8.

**Comment by mdenhoedt** [comment]
When does this feature leave 'preview'?

**Comment by DeyvsonL** [comment]
I has helped my team a lot, we just expect to be able to cache other sources like ghcr and gcr.

**Comment by madeiza** [comment]
Study completed
