### ISSUE TITLE
az acr repository delete --tag ... not working as expected

### ISSUE THREAD

**Issue by ccanizares** [Azure/acr#71]
Probably more a question than an issue... when trying to delete some old tags within az acr repository client, doesn't work and I don't get any response from az acr client. 

The command I'm using: 

`az acr repository delete -n myacr --resource-group=myrg --repository myrepo --tag mytag --manifest -y`

If I don't pass the --manifest param the tag gets deleted but I don't get free space... when passing --manifest as param some times it deletes the image (and I get free space) and sometimes it gets 'freeze', don't get any response, the tag isn't deleted and my script fails... Happens to me with many tags... i'm missing something or it's an acr bug?

I don't find any suitable doc that can help me to understand what happens with this tags, if anyone here can help..

**Comment by ccanizares** [comment]
Hi, any idea? providing more info.. For example if I try this command I never get a response.

`az acr repository show-manifests -n myacr --resource-group=myrg --repository myrepo`

**Comment by digeler** [comment]
1.	If you execute  “az acr repository delete —username <username> —password “<password>” —name recognize --repository digler/workshop-php --tag 0.1.0”. This will just un tag the image but will not reclaim the space. You  have to add the parameter manifest to the command “az acr repository delete —username <username> —password “<password>” —name recognize –repository/digeler/workshop-php --tag 0.1.0 --manifest” to allow for actual delete of image and space reduction. 
2.	When an image deletion is initiated, the amount of space that can be reclaimed depends on the layers within the image. All the layers that are not referenced by any other image of any other repository within the registry will be deleted and its space will be reclaimed. The space used by shared layers will not be reclaimed. (just like the GC in the Framework)
3.	Also, the quota limit will be enforced when you exceed the SKU size limit by more than 10%. They have a buffer of 10% above the size limit before their push is blocked. 
4.	Our space collection service is based on asynchronous model and hence there will few minutes before they can see the updated size.

**Comment by ccanizares** [comment]
Thanks @digeler for the explanation. Now I have no doubt that should be an acr problem within my repositories, asked for support directly a few days ago let see...
