### ISSUE TITLE
Create an option for deleting "ALL" untagged images (manifests)

### ISSUE THREAD

**Issue by DanielTimLee** [Azure/acr#73]
If pushing with same tag, the older one's get untagged.
```sh
  {
    "digest": "sha256:<your-some-sha-hash>",
    "tags": [],
    "timestamp": "2017-12-26T11:02:03Z"
  },
```
and which means you can't delete with tag option cause it doesn't have tags.

```sh
az acr repository delete -n <CR_NAME> --repository <REPO_NAME> --tag  --manifest
#az acr repository delete: error: argument --tag: expected one argument

az acr repository delete -n <CR_NAME> --repository <REPO_NAME> --tag '' --manifest
# Please specify either a tag name with --tag or a manifest digest with --manifest.

az acr repository delete -n <CR_NAME> --repository <REPO_NAME> --tag [] --manifest
# 404 page not found
# (404? what the hell)
```

The only option to delete this untagged images is just deleting the repo.

Is there is any way to delete these untagged repos?

**Comment by sajayantony** [comment]
You can list all your manifests in a repository. In the following case the first repo was tagged as latest and was overwritten. 

```
 az acr repository show-manifests --repository todelete
[
  {
    "digest": "sha256:8072a54ebb3bc136150e2f2860f00a7bf45f13eeb917cca2430fcd0054c8e51b",
    "tags": [],
    "timestamp": "2017-12-27T18:41:59Z"
  },
  {
    "digest": "sha256:8b68f4c0ad64bf0bc55d1df84ef22b96ccaf9b08182437612ee591d6f7cf4c40",
    "tags": [
      "latest"
    ],
    "timestamp": "2017-12-27T18:44:33Z"
  }
]
```

**Comment by djyou** [comment]
As the error message suggested you can specify either a tag or a manifest digest to delete. In your case you can use
```
az acr repository delete -n MyRegistry --repository MyRepository --manifest sha256:8072a54ebb3bc136150e2f2860f00a7bf45f13eeb917cca2430fcd0054c8e51b
```

**Comment by DanielTimLee** [comment]
Thanks, but I may be right wrong title for my question.
I was wondering if there is any way that I can delete all my untagged images at once.
Not by fetching all manifests, and deleting it one by one.

But Thanks for the tip!

**Comment by sajayantony** [comment]
This is currently not supported and we are considering an Auto purge option but there is no plan as to when we will enable this.

**Comment by sajayantony** [comment]
Given that ACR is going down an image policy route, this would most likely be implemented as "Auto-purge untagged images"

**Comment by LukeRH** [comment]
@sajayantony Do you have an estimated date for when the auto purge option will be available?

**Comment by michaeldz** [comment]
My workaround:

```bash
az acr repository show-manifests -n $ACR_NAME --repository $name --query "[?tags==null].digest" -o tsv | while read -r digest; do az acr repository delete -n $ACR_NAME --image $name@$digest --yes; done;
```

**Comment by sajayantony** [comment]
Closing this since this is being implemented right now and will announce at the end of this year.

**Comment by fuglede** [comment]
For anyone else coming across this thread, [here are the docs](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-retention-policy) for `acr purge`, describing how to purge untagged images. 

As far as I can tell, the functionality is rather dangerous to use, though, and in all of my runs, it would remove _ALL_ images, not just the untagged ones, even though `--untagged` was specified; https://github.com/MicrosoftDocs/azure-docs/issues/81172

**Comment by mohag** [comment]
> As far as I can tell, the functionality is rather dangerous to use, though, and in all of my runs, it would remove _ALL_ images, not just the untagged ones, even though `--untagged` was specified; [MicrosoftDocs/azure-docs#81172](https://github.com/MicrosoftDocs/azure-docs/issues/81172)

`--untagged` is confusing, if you specify `--filter` as well, everything matching the filter is untagged first and then all untagged images are cleaned up... (it is an additional untagged cleanup step, instead only deleting untagged images matching the filter) (My workaround is to use a filter with a non-existent tag)
