### ISSUE TITLE
Please reopen either #446 or #169

### ISSUE THREAD

**Issue by StingyJack** [Azure/acr#730]
#446 was closed prematurely and the person who closed it is AWOL. 

#169 was closed because the person who closed was optimistic that it may be addressed at some time in the future, but it has not.  The request to reopen it has 30 upvotes. The closer's last comment looks like they also misunderstand the actual request. 

FWIW I dont like having to put in separate tickets to get things reopened any more than maintainers probably want to see this kind of "bug", but the handling of these two issues has been inappropriate, each for different reasons.

**Comment by terencet-dev** [comment]
Hi @StingyJack - both issues have been reopened. Thanks for the feedback!
