### ISSUE TITLE
Cannot create cache rule for public docker image `python:3.11-bookworm` due to naming rules

### ISSUE THREAD

**Issue by xec-abailey** [Azure/acr#766]
**Describe the bug**
I am pulling in the dockerhub `python:3.11-bookworm` image and want to add a cache rule. Despite following the documentation instructions I am unable to create due to an issue with the repository path name. 

**To Reproduce**
1. Go to acr
2. Open cache
3. + create rule
4. in "Repository path" enter `docker.io/library/python:3.11-bookworm`
5. Receive error `Repository names should follow the standardized docker repository naming conventions. All characters should be lowercase. For more information, please visit https://aka.ms/acr/cache.`

**Expected behavior**
Given that this is the correct address of the image I would expect it to be a valid repository path. 

**Screenshots**
Create rule screen: 
![image](https://github.com/Azure/acr/assets/73495852/aad82df3-6128-4db0-877d-2ada4bf52eef)

Docker hub path:
![image](https://github.com/Azure/acr/assets/73495852/c3c0e82d-591e-4f90-a24c-860ce0b7c735)

**Any relevant environment information**
 - OS: [e.g. Ubuntu, Windows]
 - Azure CLI/PowerShell/SDK version
 - Docker version
 - Datetime (UTC) when the issue occurred
 - Registry and image names

**Additional context**

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by xec-abailey** [comment]
Important to note that when I first open the "Create rule" window I see this: 

![image](https://github.com/Azure/acr/assets/73495852/dcc8c7b6-6c56-4e34-887a-a1b06c8edd20)

If I just delete `/` then re-type it I get the same error: 

![image](https://github.com/Azure/acr/assets/73495852/2c52cbbe-18fe-47ca-a670-e2fa1df4fb4e)

**Comment by vladimirjk** [comment]
@xec-abailey You can't cache any specific tag, just the whole repo. You need point `docker.io/library/python `-> `<your_repo_name>`, then pull any tag available in library/python e.g. `<your_registry>.azurecr.io/<your_repo_name>:3.11-bookworm`

**Comment by xec-abailey** [comment]
> @xec-abailey You can't cache any specific tag, just the whole repo. You need point `docker.io/library/python `-> `<your_repo_name>`, then pull any tag available in library/python e.g. `<your_registry>.azurecr.io/<your_repo_name>:3.11-bookworm`

Ah, makes sense thanks

**Comment by luisdlp** [comment]
@xec-abailey As mentioned, the repo path should be a path to a tag, do not include the tag name.
