### ISSUE TITLE
Issues with buildx cache & attest

### ISSUE THREAD

**Issue by LiamLeane** [Azure/acr#775]
**Describe the bug**
Using buildx directly for bake support. It appears that since ACR incorporated cache directly configuration of the ACR service has changed so buildx no longer supports cache (or attest) options.

**To Reproduce**

```
version: v1.1.0
steps:
  - cmd: |
      {{.Run.Registry}}/buildx bake \
        --file ".build.hcl" \
        --set "*.platform=linux/amd64" \
         --set "*.cache-from=type=registry,ref={{.Run.Registry}}/image:cache" \
        --set "*.cache-to=type=registry,ref={{.Run.Registry}}/image:cache,mode=max" \
        --push \
        default
    env:
      - BUILDX_EXPERIMENTAL=1
      - REGISTRY={{.Run.Registry}}
      - VERSION_TAG={{.Values.VERSION_TAG}}
```

```
variable "REGISTRY" {
  type = string
}

variable "VERSION_TAG" {
  type = string
  default = "local"
}

variable "IMAGE_NAME_BASE" {
  type = string
  default = "image"
}

group "default" {
  targets = ["main"]
}

target "main" {
  dockerfile = "Dockerfile"
  context = "."
  platforms = ["linux/amd64"]
  tags = ["${REGISTRY}/${IMAGE_NAME_BASE}:${VERSION_TAG}"]
  attest = [
    "type=provenance,mode=max",
    "type=sbom"
  ]
}
```

Output:
```
ERROR: Cache export is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
```

Output with cache removed:
```
ERROR: Attestation is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
```

**Comment by juliusl** [comment]
Looks like this issue, https://github.com/Azure/acr/issues/351 ?

**Comment by juliusl** [comment]
Have you tried passing --provenance=true? 

https://docs.docker.com/build/metadata/attestations/

**Comment by LiamLeane** [comment]
Looking through acr-builder I can see why this doesn't work. https://github.com/Azure/acr-builder/blob/main/builder/builder.go#L108 creates the worker but as no driver is specified it will use the default docker driver which doesn't support attestations. https://docs.docker.com/build/builders/drivers/ https://docs.docker.com/build/builders/drivers/docker/

It also appears to be using either an old or customized version of buildkit that doesn't support those options too.

```
Error: unknown flag: --attest
Usage:
  /buildx build [OPTIONS] PATH | URL | - [flags]

Aliases:
  build, b

Flags:
      --add-host strings         Add a custom host-to-IP mapping (host:ip)
      --allow strings            Allow extra privileged entitlement, e.g. network.host, security.insecure
      --build-arg stringArray    Set build-time variables
      --cache-from stringArray   External cache sources (eg. user/app:cache, type=local,src=path/to/dir)
      --cache-to stringArray     Cache export destinations (eg. user/app:cache, type=local,dest=path/to/dir)
  -f, --file string              Name of the Dockerfile (Default is 'PATH/Dockerfile')
  -h, --help                     help for build
      --iidfile string           Write the image ID to the file
      --label stringArray        Set metadata for an image
      --load                     Shorthand for --output=type=docker
      --network string           Set the networking mode for the RUN instructions during build (default "default")
      --no-cache                 Do not use cache when building the image
  -o, --output stringArray       Output destination (format: type=local,dest=path)
      --platform stringArray     Set target platform for build
      --progress string          Set type of progress output (auto, plain, tty). Use plain to show container output (default "auto")
      --pull                     Always attempt to pull a newer version of the image
      --push                     Shorthand for --output=type=registry
      --secret stringArray       Secret file to expose to the build: id=mysecret,src=/local/secret
      --ssh stringArray          SSH agent socket or keys to expose to the build (format: default|<id>[=<socket>|<key>[,<key>]])
  -t, --tag stringArray          Name and optionally a tag in the 'name:tag' format
      --target string            Set the target build stage to build.

Global Flags:
      --builder string   Override the configured builder instance
```

with

```
---
version: v1.1.0
steps:
  - build: |
      --platform linux \
      --tag {{.Run.Registry}}/{{.Values.REPOSITORY_NAME}}:{{.Values.VERSION_TAG}} \
      --tag {{.Run.Registry}}/{{.Values.REPOSITORY_NAME}}:{{.Values.VERSION_TAG_MAJOR}} \
      --tag {{.Run.Registry}}/{{.Values.REPOSITORY_NAME}}:latest \
      --attest=type=provenance \
      --attest=type=sbom,generator=image \
      --file image/Dockerfile.temp \
      --push \
      image
    cache: enabled
```

I thought about just setting up a Task agent pool so I can change the default docker driver buildkit uses but there doesn't appear to be any way to change the configuration of those VM's I can spot.

Am I right to assume my options are basically:

* Contrib a way to set driver to acr-builder and hope/wait it makes it to ACR
* Not use ACR tasks for container builds

Is there a third option I am not aware of that would let me self-host acb and get ACR to use it?

**Comment by juliusl** [comment]
@LiamLeane 

> Contrib a way to set driver to acr-builder and hope/wait it makes it to ACR

I'll be more than happy to review and get this fix in if you make a contribution. We update this about every 2 or so weeks so it wouldn't be that long of a turn around.

**Comment by juliusl** [comment]
> Is there a third option I am not aware of that would let me self-host acb and get ACR to use it?

Another option would be to build buildx inside of the task and then using it to run the build. I think you could encapsulate it into your dockerfile as well via, https://github.com/docker/buildx?tab=readme-ov-file#dockerfile, https://hub.docker.com/r/docker/buildx-bin

I haven't tried this myself but I can do some scouting to see if that works

**Comment by juliusl** [comment]
@LiamLeane So I got this working and I created an example that you can try, https://github.com/juliusl/buildx-in-docker-on-tasks

**Comment by juliusl** [comment]
Closing the issue since we haven't heard back and I provided a fix, let us know if you need anymore help @LiamLeane

**Comment by jbiel** [comment]
Theanks @juliusl. The above is an interesting workaround, but it's overly complex and difficult to pass other parameters due to the use of the entrypoint script that was provided. It'd be nice if the default AzDo builders were updated with a version of Docker that supported buildx out of the box.

**Comment by jason-johnson** [comment]
Yes, can this be reopened please?  A workaround is not a fix.
