### ISSUE TITLE
Enable ACR to store metadata for Repositories and Tags

### ISSUE THREAD

**Issue by sajayantony** [Azure/acr#79]

**Comment by yuwaMSFT2** [comment]
# Repository APIs
## List repositories: 
_GET /acr/v1/_repositories_

>>>Success:
Status: 200
Body:
_{
  "repositories": [
    "mytest",
    "mytest/subtest",
    "mytest/subtest/sub2",
    "testimage1",
    "testimage2"
  ]
}_


## Delete repository: 
_DELETE /acr/v1/_repositories/{repository}_

>>>Success:
Status: 202
Body:
_{
  "manifestsDeleted": [
    "sha256:9fa82f24cbb11b6b80d5c88e0e10c3306707d97ff862a3018f22f9b49cef303a",
    "sha256:c6328a5b98b858e9a71cc58da093432692d9b7994c30e6253a1d5d38ff28d458"
  ],
  "tagsDeleted": [
    "2",
    "latest",
    "windows"
  ]
}_

>>>Fail:
Status: 404
Body:
_{
  "errors": [
    {
      "code": "NAME_UNKNOWN",
      "message": "repository name not known to registry",
      "detail": {
        "name": "erwerwer"
      }
    }
  ]
}_

## List repository metadata: 
_GET /acr/v1/_repositories/{repository}/_metadata_

>>>Success:
Status: 200
Body:
_{
  "registry": "yuwatest12-msft.azurecr-test.io",
  "imagename": "testimage1",
  "metadata": [
    "mytest",
    "mytest2"
  ]
}_

>>>Fail:
Status: 404
Body:
_{
  "errors": [
    {
      "code": "NAME_UNKNOWN",
      "message": "repository name not known to registry"
    }
  ]
}_

## Get/Set/Delete repository metadata: 
_GET/PUT/DELETE /acr/v1/_repositories/{repository}/_metadata/{name}_

***GET:
>>>Success: 
Status: 200

***PUT:
>>>Success: 
Status: 201

***Delete:
>>>Success: 
Status: 202


## List repository properties: 
_GET /acr/v1/_repositories/{repository}/_properties_
>>>Success:
Status: 200
Body:
_{
  "registry": "yuwatest12-msft.azurecr-test.io",
  "imagename": "testimage1",
  "manifestcount": 4,
  "tagcount": 2,
  "nodelete": false,
  "nochange": false,
  "nolist": false,
  "noread": false
}_

## Get/Set repository properties: 
_GET/PUT /acr/v1/_repositories/{repository}/_properties/{name}_
***GET:
>>>Success:
Status: 200
Body: _false_

***PUT:
>>>Success: 
Status: 201

# Tag APIs
## List tags: 
_GET /acr/v1/_repositories/{repository}/_tags_
>>>Success:
Status: 200
Body:
_{
  "registry": "yuwatest12-msft.azurecr-test.io",
  "imageName": "testimage1",
  "tags": [
    {
      "name": "azurecli",
      "digest": "sha256:1bce822ce3c234b07c4036ead05c464e7972a565b63779c37d0efd25b69d188a",
      "createdtime": "2017-12-15T21:42:44Z",
      "lastupdatetime": "2017-12-15T21:42:44Z",
      "signaturerecord": "{signer: test@mytest.org}",
      "nodelete": false,
      "nochange": false,
      "nolist": false,
      "noread": false
    },
    {
      "name": "latest",
      "digest": "sha256:1bce822ce3c234b07c4036ead05c464e7972a565b63779c37d0efd25b69d188a",
      "createdtime": "2017-12-15T21:42:48.2943219Z",
      "lastupdatetime": "2017-12-15T21:42:48.2943219Z",
      "nodelete": false,
      "nochange": false,
      "nolist": false,
      "noread": false
    }
  ]
}_

## Delete tag: 
_DELETE /acr/v1/_repositories/{repository}/_tags/{tag}_
>>>Success:
Status: 202

## List tag metadata: 
_GET /acr/v1/_repositories/{repository}/_tags/{tag}/_metadata_
>>>Success:
Status: 200
Body:
_{
  "registry": "yuwatest12-msft.azurecr-test.io",
  "imageName": "testimage1",
  "tagName": "azurecli",
  "metadata": [
    "description"
  ]
}_

## Get/Set/Delete tag metadata: 
_GET/PUT/DELETE /acr/v1/_repositories/{repository}/_tags/{tag}/_metadata/{name}_
***GET
>>>Success
Status: 200
Body: _this is a test_

***PUT
>>>Success
Status: 201

***DELETE
>>>Success
Status: 202

## List tag properties: 
_GET /acr/v1/_repositories/{repository}/_tags/{tag}/_properties_
>>>Success
Status: 200
Body:
_{
  "registry": "yuwatest12-msft.azurecr-test.io",
  "imageName": "testimage1",
  "tags": [
    {
      "name": "azurecli",
      "digest": "sha256:1bce822ce3c234b07c4036ead05c464e7972a565b63779c37d0efd25b69d188a",
      "createdtime": "2017-12-15T21:42:44Z",
      "lastupdatetime": "2017-12-15T21:42:44Z",
      "signaturerecord": "{signer: test@mytest.org}",
      "nodelete": false,
      "nochange": false,
      "nolist": false,
      "noread": false
    }
  ]
}_

## Get/Set tag properties: 
_GET/PUT /acr/v1/_repositories/{repository}/_tags/{tag}/_properties/{name}_
***GET
>>>Success
Status: 200
Body: _false_

***PUT
>>>Success
Status: 201

# Manifest APIs
## List manifests: 
_GET /acr/v1/_repositories/{repository}/_manifests_
>>>Success:
Status: 200
Body:
_{
  "registry": "yuwatest12-msft.azurecr-test.io",
  "imagename": "testimage1",
  "manifests": [
    {
      "digest": "sha256:1bce822ce3c234b07c4036ead05c464e7972a565b63779c37d0efd25b69d188a",
      "lastupdatetime": "2017-12-15T21:42:43.3144771Z",
      "architecture": "amd64",
      "os": "linux",
      "mediatype": "application/vnd.docker.distribution.manifest.v2+json",
      "nodelete": false,
      "nochange": false,
      "nolist": false,
      "noread": false
    },
    {
      "digest": "sha256:343054fdce616fc428094e2f6d3b97c6ae62f82fe9f8e54b0b1937e8a0297e68",
      "lastupdatetime": "2017-11-13T23:58:50Z",
      "architecture": "amd64",
      "mediatype": "application/vnd.docker.distribution.manifest.v1+json",
      "nodelete": false,
      "nochange": true,
      "nolist": false,
      "noread": false
    },
    {
      "digest": "sha256:9fa82f24cbb11b6b80d5c88e0e10c3306707d97ff862a3018f22f9b49cef303a",
      "lastupdatetime": "2017-11-16T20:02:08Z",
      "mediatype": "application/vnd.docker.distribution.manifest.v2+json",
      "nodelete": false,
      "nochange": false,
      "nolist": false,
      "noread": false
    },
    {
      "digest": "sha256:c6328a5b98b858e9a71cc58da093432692d9b7994c30e6253a1d5d38ff28d458",
      "lastupdatetime": "2017-11-13T23:24:41Z",
      "architecture": "amd64",
      "os": "linux",
      "mediatype": "application/vnd.docker.distribution.manifest.v2+json",
      "nodelete": false,
      "nochange": false,
      "nolist": false,
      "noread": false
    }
  ]
}_

## List manifest metadata: 
_GET /acr/v1/_repositories/{repository}/_manifests/{digest}/_metadata_
>>>Success
Status: 200
Body:
_{
  "registry": "yuwatest12-msft.azurecr-test.io",
  "imagename": "testimage1",
  "digest": "sha256:343054fdce616fc428094e2f6d3b97c6ae62f82fe9f8e54b0b1937e8a0297e68",
  "metadata": [
    "metadata2",
    "testmetadata1"
  ]
}_

## Get/Set/Delete manifest metadata: 
_GET/PUT/DELETE /acr/v1/_repositories/{repository}/_manifests/{digest}/_metadata/{name}_
***GET
>>>Success:
Status: 200
Body: _test content_

***PUT
>>>Success:
Status: 201

***DELETE
>>>Success:
Status: 202

## List manifest properties: 
_GET /acr/v1/_repositories/{repository}/_manifests/{digest}/_properties_
>>>Success:
Status: 200
Body:
_{
  "registry": "yuwatest12-msft.azurecr-test.io",
  "imagename": "testimage1",
  "manifests": [
    {
      "digest": "sha256:343054fdce616fc428094e2f6d3b97c6ae62f82fe9f8e54b0b1937e8a0297e68",
      "lastupdatetime": "2017-11-13T23:58:50Z",
      "architecture": "amd64",
      "mediatype": "application/vnd.docker.distribution.manifest.v1+json",
      "nodelete": false,
      "nochange": false,
      "nolist": false,
      "noread": false
    }
  ]
}_

## Get/Set manifest properties: 
_GET/PUT /acr/v1/_repositories/{repository}/_manifests/{digest}/_properties/{name}_
***GET
>>>Success:
Status: 200
Body: _false_

***PUT
>>>Success:
Status: 201

***DELETE
>>>Success:
Status: 202

**Comment by sajayantony** [comment]
Would recommend submitting a readme and swagger as a PR so we can review individual elements there. 
/cc @SteveLas
