### ISSUE TITLE
Documentation: Authenticate to ACR with Federated Credentials

### ISSUE THREAD

**Issue by worldwideward** [Azure/acr#791]
It's easy to use a federated credential and Azure CLI to authenticate to an ACR.

But as we all now AZ CLI is a ridiculously large utility if you only need a command or two.

So I am trying to use authenticate against the ACR using oauth.

I can't manage to get this working, and in my opinion this is because the documentation is confusing and incomplete. Even ChatGPT is unable to figure it out correctly, so that's not helpful.

For the purpose of testing, I used AZ CLI to generate a valid login token. But with this valid token (works when using docker login) , it seems inpossible to authenticate using REST.

```bash
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" 'https://reg.azurecr.io/oauth2/token' \
        -d "grant_type=refresh_token&refresh_token='$ACCESS_TOKEN'&service=reg.azurecr.io" -v
```

This command is based upon the docs:

```bash
registry="contosoregistry.azurecr.io"
acr_refresh_token="eyJ...L7a"
scope="registry:catalog:*"
curl -v -X POST -H "Content-Type: application/x-www-form-urlencoded" -d \
"grant_type=refresh_token&service=$registry&scope=$scope&refresh_token=$acr_refresh_token" \
https://$registry/oauth2/token
```

Fortunately my client is wasting thousands of dollars on this, otherwise I would never touch this bs platform.

So to conclude, I don't need help, I need Microsoft to create *useful* and *clear* documentation that is *not* all over the place.

**Comment by worldwideward** [comment]
Nevermind, I found a solution.

**Comment by keisari-ch** [comment]
> Nevermind, I found a solution.

good for you. :)
