### ISSUE TITLE
ACR does not support logging in with an application identifier_uri

### ISSUE THREAD

**Issue by colemickens** [Azure/acr#8]
**Summary:**
ACR does not support logging in with an application `identifier_uri` (aka, a non-GUID `client_id`).

**Observation:**
```
$ docker login --username http://colemick-acs-kube-sp --password '[redacted]' testperma1registry-microsoft.azurecr.io
Error response from daemon: login attempt to https://testperma1registry-microsoft.azurecr.io/v2/ failed with status: 401 Unauthorized

$ docker login --username '4e814388-d2e5-4045-9c54-0afb2e8a5e65' --password '[redacted]' testperma1registry-microsoft.azurecr.io
Login Succeeded
```

**Problem:**
Those are both valid `client_id`s for the same application. ACR should allow me to login with both identifiers.

**Comment by SajayAntony** [comment]
One challenges here seems to be the scheme separator `:` . 
The basic authentication header uses the first `:` as the username and password separator since passwords can contain `:`. We need to handle the fact that if the first `:` might be prefixed with a scheme and then use the next `:` in this specific case.

**Comment by colemickens** [comment]
Why does it not take a JSON blob and then deserialize and pull out the values?

The problem gets even harder than you describe since my password could contain a `:` (colon) character, right?

**Comment by SajayAntony** [comment]
I guess the issue is how the Basic Auth header is created by the CLI . The docker CLI just joins the username and password with a `:`. So basically we need to handle the client_id as a special case.

**Comment by SajayAntony** [comment]
Given that we are going to support AAD auth, I don't think we might not fix this at this point. Might be worth coming back at some point.
