### ISSUE TITLE
Docker login is not working on windows to my container registry

### ISSUE THREAD

**Issue by aumanjoa** [Azure/acr#80]
When I try a docker login I get this error on my windows 10 machine:

> Error response from daemon: Get https://<myreg>.azurecr.io/v2/: net/http: request canceled while waiting for a connection (Client.Timeout exceeded while awaiting headers)

Doing the same docker login command on ubuntu works seamlessly. 

Any idea? Docker version of Windows
>  Docker version 17.12.0-ce, build c97c6d6

**Comment by sajayantony** [comment]
Does this error still show up? We had a transient issue in one region, yesterday.

**Comment by aumanjoa** [comment]
Issue is solved. After the newest update of Windows Docker I neede to do a "setting reset" after this it started working again

**Comment by SamirFarhat** [comment]
I'm getting the issue now
Error response from daemon: Get https://xxxx.azurecr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).

It was working yesterday. I have not updated docker (Version 18.03.1-ce-win65 (17513))

**Comment by palmerabollo** [comment]
Same error here. Azure [status page](https://azure.microsoft.com/en-us/status/) shows everything green/good.

**Comment by sivagms** [comment]
@palmerabollo  could you send your registry name and outbound IP address to sivag@microsoft.com , so that we can investigate further..

**Comment by nheinbaugh** [comment]
@sivagms I am having this problem on my machine now. Are you still on this project? If so I can contact you with the information. I don't know what the above user meant by "settings reset" and I would love to help get the clear info out :)

**Comment by nheinbaugh** [comment]
Apparently it might mean a factory reset of the Docker settings. Seems to work now.

**Comment by sajayantony** [comment]
Next time you can try https://aka.ms/acr/health-check

**Comment by ngcdev** [comment]
I'm having this issue right now in Ubuntu (same error message) and I did the health-check and everything is fine.
Not sure what/how to do a "factory reset of the Docker settings".

Running Docker 18.03.1-ce

**Comment by ngcdev** [comment]
Although I did a `dig` with my default DNS and with 8.8.8.8 and both returned exactly the same, changing my /etc/resolve.conf and put 8.8.8.8 first (as suggested in other posts), solved the issue (at least for now). I'm starting to think that this is an issue in the docker client, perhaps some cache of prior login

**Comment by saad-hassanDS** [comment]
Hi, Output of "az acr check-health --name myregistry --ignore-errors" says all good:

""""
Docker daemon status: available
Docker version: Docker version 18.09.7, build 2d0083d
This will pull the image mcr.microsoft.com/mcr/hello-world:latest. Proceed? (y/n): y
Docker pull of 'mcr.microsoft.com/mcr/hello-world:latest' : OK
Azure CLI version: 2.3.1
DNS lookup to testregistoryml.azurecr.io at IP 40.112.242.160 : OK
Challenge endpoint https://testregistoryml.azurecr.io/v2/ : OK
Fetch refresh token for registry 'testregistoryml.azurecr.io' : OK
Fetch access token for registry 'testregistoryml.azurecr.io' : OK
Helm version: version.BuildInfo{Version:"v3.1+unreleased", GitCommit:"f89d985cb8248be7db0850c018505836d303ff1c", GitTreeState:"clean", GoVersion:"go1.13.10"}
Notary version: notary
Version:
Git commit:
""""

But I am still getting this timeout error,
