### ISSUE TITLE
az acr repository show-manifests very, very slow

### ISSUE THREAD

**Issue by DonMartin76** [Azure/acr#83]
For larger repositories in an ACR, the Azure CLI command `az acr repository show-manifests` is extremely slow. While show-tags is fairly quick (under 30 seconds), show-manifests sometimes takes several minutes to finish. In some cases, I had to cancel the request after almost 30 minutes.

Granted, those repositories have never been cleaned up (see issue #82), and that's what I am currently trying to do. Some repositories have several hundred tags, and as such also an amount of manifests in the same order of magnitude.

Still, this seems to be too slow. Is this a known issue, is there something one can do about it?

**Addendum**: It seems as if it's really the call to `GET //v2/_acr/<repository>/manifests/list?n=20` which is really slow for certain of the larger repositories. This means I currently can't really clean things up efficiently. For the smaller repos, it works, but there seems to be some kind of O(n^2) thing in here (or even worse) which makes it too slow for repos having lots of manifests.

**Comment by DonMartin76** [comment]
OK, thanks for the heads up. I need to find a different solution for the time being then - I have let it sit for two hours now, and it still didn't answer the request. I guess it's cut off somewhere in the backend.

**Comment by SteveLasker** [comment]
We'll make sure this particular manifest listing api gets fixed in our next deployment. We can shim it over the new metadata services that improve perf. It should be out by ~23rd.
Hopefully the current api you're running doesn't take that long to return...  Sorry. We've been working on the metedata api to fix the indexing for a bit as we've seen latency become a problem. You're just a front runner. We'd love to have you in the preview. 
Steve

**Comment by DonMartin76** [comment]
Thanks for your efforts, looking forward to the performance improvements. Registered for the preview.

**Comment by DonMartin76** [comment]
There seems to have been a fix, or at least a change for this - it actually returns data now. Can you confirm that you have rolled out a fix?

**Comment by sajayantony** [comment]
There have been a large number of fixes and improvements being rolled out - 
/cc @yuwaMSFT2 @djyou

**Comment by sajayantony** [comment]
Feel free to reopen if we see performance degradation.

**Comment by DonMartin76** [comment]
This is sufficiently fast now. Sorry for not closing this myself earlier.

**Comment by SteveLasker** [comment]
No worries. Just happy we were able to resolve. Thanks for taking the time to post the info. If you have any other feedback, please do reach out. 
Steve
