### ISSUE TITLE
build-task -n should support - and _

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr#85]
should be able to create a build-task with a name of baseimage-foo or base_image_foo

**Comment by SteveLasker** [comment]
Hi @kheiakiyama 
You can find an overview of our goals here: https://blogs.msdn.microsoft.com/stevelasker/2017/12/20/os-framework-patching-with-docker-containers-paradigm-shift/
And the docs for `ACR Build` here: https://aka.ms/acr/build
We'll have more official announcements at the //build conference.

**Comment by sajayantony** [comment]
ACR is moving to tasks and this is supported in the new API set.
