### ISSUE TITLE
Improve error message for not found

### ISSUE THREAD

**Issue by codingoutloud** [Azure/acr#87]
When `az acr repository list --name myreg` is run when myreg is not in the current subscription, the following error is returned:

> No resource with type Microsoft.ContainerRegistry/registries can be found with name: myreg

It would be more helpful if the error also mentioned the Subscription in question. For example:

> No resource with type Microsoft.ContainerRegistry/registries can be found with name: myreg from Subscription: MySubscription.

This will help users much more quickly understand the source of the problem in cases where this is caused by an incorrect default subscription, a scenario mention on the [troubleshooting guide](https://github.com/Azure/acr/blob/master/docs/Troubleshooting%20Guide.md).

**Comment by SteveLasker** [comment]
@sajayantony is this something we can fix in `az acr`, or is this in the `az` cli?

**Comment by djyou** [comment]
We fixed the scenario when `-g` is not specified and the printed message now is 
```
The resource with name 'MyRegistry' and type 'Microsoft.ContainerRegistry/registries' could not be found in subscription 'My Subscription (00000000-0000-0000-0000-000000000000)'.
```

When `-g` is specified, the CLI prints message from ARM directly which we don't have control.

**Comment by sajayantony** [comment]
@djyou - Do we even need to support -g . Is  it for scoping? this is repository subgroup.

**Comment by djyou** [comment]
`-g` is just to follow convention, all Azure resources belong to some resource group and ACR is a special case where resource group can be resolved due to it's unique name.

**Comment by SteveLasker** [comment]
Would really like to see this removed as these are nested resources, and ACR already has global uniqueness. I

**Comment by sajayantony** [comment]
@djyou can we close this?

**Comment by djyou** [comment]
Close as the fix has been merged in.

**Comment by rtaylor72** [comment]
I ran into this and found another issue.  The service provider (SP) I was using only had the "Acr Push" role.  I had to add the "Contributor" role to resolve the issue.  So it appears "Acr Push" does not have enough permissions to see the ACR resource.  Hope this helps someone else that sees this error and is confused knowing that the ACR is in the specified subscription.
