### ISSUE TITLE
What's the registry solution for regions ACR not available? #150

### ISSUE THREAD

**Issue by VincentLiu028** [Azure/acr#9]
ACR is in preview in limited region. What's the recommended way for regions that ACR are not available like Mooncake?

**Comment by sivagms** [comment]
Lighting up ACR in Mooncake is in plan, but till then hosting the open source version is an alternative.

**Comment by sivagms** [comment]
Vincent, let me know if you have any other questions on this. closing this issue.

**Comment by VincentLiu028** [comment]
@sivagms , do we have a schedule for Mooncake?

**Comment by sivagms** [comment]
we don't have a schedule yet, but we are already working on the pre-requisites for that such as compliance...

**Comment by VincentLiu028** [comment]
Thanks for the the information. Really hope ACR can light up on Mooncake soon.
