### ISSUE TITLE
running az acr build-task create doesn't fail when -n already exists

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr#90]
Running this script multiple times simply updates the build-task.  Somewhat interesting, but shouldn't this fail as I wouldn't want to override an existing build task
```
az acr build-task create \
  -n demo42quotesapi \
  --context https://github.com/demo42/quotes -t demo42/quotes-api:{{.Build.ID}} \
  -f ./src/QuoteService/Dockerfile \
  --git-access-token <redacted> \
  --build-arg NAME=VALUE \
  --registry jengademos 
```

**Comment by sajayantony** [comment]
Build task is a resource and hence recreation of the same resource when it exists doesn't fail.
