### ISSUE TITLE
Webhook - Play it again...

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr#91]
When troubleshooting build/release issues, it would be great to run the same webhook again.
## reasoning
A release is likely based on the image:tag combination. So, you can't just trigger a release without the information it needs.
In the idempotent, unlreiable microservice world, it would be great to right-click on a specific webhook execution, and say, 'play again'
This would save me from having to docker pull, docker push the same tag again.

**Comment by YvonneArnoldus** [comment]
Because of the problems with auto deployment webhook to Web App for Containers it would be nice to trigger the webhook again, instead of a new deployment

**Comment by sajayantony** [comment]
@SteveLas  - do you want to create this in user voice instead of here?
