### ISSUE TITLE
acr-build to support Date as a build-arg

### ISSUE THREAD

**Issue by SteveLasker** [Azure/acr#94]
Would like to use various date formats in build args, or for image tags
```
az acr build-task create \
  -n myBuildTask \
  --context https://github.com/demo42/deploy \
  -t baseimages/microsoft/dotnet-sdk:linux-2.1 \
  --build-arg IMAGE_BUILD_DATE=`date +%Y%m%d-%H%M%S` 
```

**Comment by ehotinger** [comment]
https://github.com/Azure/acr-builder/pull/159

**Comment by sajayantony** [comment]
@ehotinger  - has this been deployed already?

**Comment by ehotinger** [comment]
@sajayantony nope, deploy to dogfood this Thursday.

**Comment by ehotinger** [comment]
@SteveLas  + @sajayantony  FYI this change is globally available as of last Friday (`{{.Build.Date}}`). However, it should be noted that we're actively changing this to `.Run.Date`, so nobody should keep a dependency on `.Build.Date`, and this isn't available for Windows builds.

**Comment by SteveLasker** [comment]
Thanks Eric, good to know about the change to Run.

**Comment by sajayantony** [comment]
Closing since we are moving to tasks
