### ISSUE TITLE
Call ACR APIs using empty GUID and refresh token via basic auth

### ISSUE THREAD

**Issue by LazarusX** [Azure/acr#98]
I just acquired an ACR refresh token programmatically, and I can do `docker login` and `docker pull` with empty GUID and this refresh token. However, when I try to call ACR APIs using these credentials, such as `https://${registryUrl}/v2/_catalog`, I still encounter "401 unauthorized" error. Does ACR support calling APIs using empty GUID and refresh token via basic auth? Or did I miss something?

**Comment by djyou** [comment]
An `access_token` is required for accessing ACR APIs and it can be obtained using `refresh_token`

https://github.com/Azure/acr/blob/master/docs/AAD-OAuth.md#calling-post-oauth2token-to-get-an-acr-access-token

Once you have an `access_token`, calling ACR APIs can be followed here https://github.com/Azure/acr/blob/master/docs/AAD-OAuth.md#calling-an-azure-container-registry-api

**Comment by LazarusX** [comment]
Thanks for the clarification!
