### ISSUE TITLE
No overview of how geo-redundancy in ACR is effected?

### ISSUE THREAD

**Issue by williamayerst** [Azure/acr#99]
HI there,

I'm looking to adopt ACR as a registry of choice and will be going with a geo-redundant option for our most crucial images, however I am not clear on the actual mechanics of the geo-redundancy: is the 99.9% availability per geographically discrete registry, or as a whole? Is it entirely managed by the Azure back end?

**Comment by sajayantony** [comment]
Each region is independent once setup in the replication ring. Images are synchronized with an eventual consistency model since its a Multi-master. SLA's apply to each region and routed by TM performance profile. 

Webhooks are region affinitized so you should leverage regional webhooks to trigger workflows. 

I believe @SteveLasker  is writing this up and probably was inspired by this issue.

**Comment by SteveLasker** [comment]
I'm writing up a blog post on how and why we generate the ACR Build ID's.  Which supports independently, fail over/fault tolerant regions. I'll get it out tomorrow. But, I was adding some "failure as a design principal" background. You might find this post helpful: https://blogs.msdn.microsoft.com/stevelasker/2018/01/29/working-with-acr-geo-replication-notifications/

**Comment by SteveLasker** [comment]
Adding @mmacy to enhance the docs a bit.

**Comment by SteveLasker** [comment]
@williamayerst , here's the post I was referring to: https://blogs.msdn.microsoft.com/stevelasker/2018/05/18/how-acr-build-ids-are-generated/ 
I'll leave this issue open, pending some doc updates to clarify in the official docs.

**Comment by sajayantony** [comment]
@williamayerst  - would you like to reach out to sajaya at microsoft and stevelas at microsoft for more details so that we can understand your scenario more?

**Comment by SteveLasker** [comment]
@dlepow, can we add some content to the docs to round this out?

**Comment by dlepow** [comment]
@SteveLasker @sajayantony  - Added notes to backlog doc item around mining blogs for best practices. Thx.

**Comment by dlepow** [comment]
@SteveLasker @sajayantony - I updated 'official' geo-replication docs per above PR with related guidance. I think this issue is ready to close. Thx.

**Comment by msyihchen** [comment]
@williamayerst  Does this thread help you resolve your questions? If so, can we close this thread?

**Comment by sajayantony** [comment]
Closing for now since we have official docs and can open issues there for any doc details.
